import {NextResponse} from "next/server";
import {getCustomerSession} from "../../../../../lib/auth";
import {supabaseAdmin} from "../../../../../lib/supabase-admin";
export const runtime="nodejs";export const maxDuration=300;
const OPENAI="https://api.openai.com/v1";
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms))}
export async function POST(req:Request){
 const session=await getCustomerSession();if(!session)return NextResponse.json({error:"Iniciá sesión."},{status:401});
 const db=supabaseAdmin();const {data}=await db.auth.admin.getUserById(session.userId);const userPlan=String(data.user?.user_metadata?.plan||session.plan||"");if(userPlan!=="escala"&&userPlan!=="ai")return NextResponse.json({error:"Mockup Premium requiere Escala o VYRAL AI."},{status:403});
 const key=process.env.VYRAL_CREATOR_PRODUCTION;if(!key)return NextResponse.json({error:"Falta configurar la API de OpenAI."},{status:503});
 try{
  const b=await req.json();const title=String(b.title||"").trim();const brief=String(b.brief||"").trim();const style=String(b.style||"").trim();const coverUrl=String(b.coverUrl||"").trim();if(!title||!coverUrl)return NextResponse.json({error:"Falta la portada o el título del ebook."},{status:400});
  const cover=await fetch(coverUrl,{cache:"no-store"});if(!cover.ok)throw new Error("No se pudo leer la portada original.");const coverType=cover.headers.get("content-type")||"image/jpeg";const coverBytes=new Uint8Array(await cover.arrayBuffer());const coverFile=new Blob([coverBytes],{type:coverType.startsWith("image/")?coverType:"image/jpeg"});
  const prompt=`VYRAL PREMIUM EBOOK PRODUCT PHOTOGRAPHY ENGINE. Create ONE spectacular hyper-realistic advertising photograph of the ebook described below as a premium physical hardcover book. The attached image is the ACTUAL FRONT COVER and is authoritative: preserve its artwork, title, typography, colors, hierarchy and imagery as faithfully as possible. Do NOT redesign the cover, do NOT replace its title, do NOT add a second title overlay, do NOT create floating text, pseudo-text, labels, stickers or marketing copy outside the existing cover. The existing cover must appear physically printed into the book surface with correct perspective, material texture, edge behavior, subtle reflections and realistic lighting — never pasted on like a flat Paint overlay.\n\nMake the book itself physically convincing: premium hardcover construction, realistic thickness, spine, page block, tiny natural edge imperfections, contact shadow, global illumination, accurate perspective and lens behavior. Create a cinematic high-end commercial product photograph, not a generic 3D mockup. The surrounding environment must be intelligently derived from the SUBJECT OF THIS SPECIFIC EBOOK and feel unmistakably related to its content. Use meaningful real-world props, surfaces, atmosphere and background storytelling from the topic; never use a generic office unless the subject truly requires it. Background should support the book without overpowering it. Shallow depth of field, premium editorial lighting, tactile materials, photorealistic textures, natural shadows, sophisticated composition, realistic camera optics, advertising-campaign quality. The final result should feel photographed by an elite commercial product photographer with a real book on a real set. No people unless strongly justified by the ebook subject. No hands holding the book. No open-book spread. One hero book as the clear focal product.\n\nEBOOK TITLE: ${title}\nEBOOK CONTEXT / BRIEF: ${brief.slice(0,6000)}\nVISUAL DNA: ${style.slice(0,2500)}\n\nOutput a single premium HERO product photograph suitable for a landing page, checkout, paid advertisement or social campaign. Landscape/square-friendly composition with breathing room, but the book cover must remain large, readable and dominant.`;
  const form=new FormData();form.append("model",process.env.VYRAL_EBOOK_IMAGE_MODEL||"gpt-image-2.5-flare");form.append("prompt",prompt);form.append("image",coverFile,"cover.jpg");form.append("size","1536x1024");form.append("quality","medium");form.append("output_format","jpeg");
  let r:Response|null=null,j:any=null;for(let attempt=0;attempt<4;attempt++){r=await fetch(OPENAI+"/images/edits",{method:"POST",headers:{Authorization:`Bearer ${key}`},body:form});const raw=await r.text();try{j=JSON.parse(raw)}catch{j={error:{message:`Respuesta inválida del generador (HTTP ${r.status}).`}}}if(r.ok)break;if(![408,409,429,500,502,503,504].includes(r.status)||attempt===3)break;await sleep(4000*Math.pow(2,attempt))}
  if(!r?.ok)throw new Error(j?.error?.message||"No se pudo generar el mockup premium.");const b64=j?.data?.[0]?.b64_json;if(!b64)throw new Error("El generador no devolvió el mockup.");const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const path=`${session.userId}/creator-ai/ebooks/mockups/${crypto.randomUUID()}.jpg`;const up=await db.storage.from("scheduled-media").upload(path,bytes,{contentType:"image/jpeg",upsert:false});if(up.error)throw new Error(up.error.message);const signed=await db.storage.from("scheduled-media").createSignedUrl(path,86400);if(signed.error||!signed.data?.signedUrl)throw new Error("No se pudo preparar el mockup.");return NextResponse.json({image:signed.data.signedUrl,storagePath:path});
 }catch(e:any){return NextResponse.json({error:e.message||"No se pudo generar el mockup premium."},{status:500})}
}
