"use client";
import {useEffect,useMemo,useState} from "react";
type Slot={name:string;url:string;value:string;description:string};
type Props={brief:string;plan:any;mockup?:string;offerData?:any};
const empty=():Slot=>({name:"",url:"",value:"",description:""});
const inputStyle={width:"100%",padding:"11px 12px",borderRadius:10,border:"1px solid #303044",background:"#09090f",color:"#fff"};
const buttonStyle={padding:"13px 19px",border:"1px solid #b99cff66",borderRadius:12,background:"linear-gradient(135deg,#6547ff,#9c4dff)",boxShadow:"0 9px 28px #7650ff42, inset 0 1px #ffffff55",color:"#fff",fontWeight:900,cursor:"pointer"} as const;
const Logo=({height=22}:{height?:number})=><img src="/impultienda.png" alt="ImpulTienda" style={{height,width:"auto",maxWidth:170,objectFit:"contain",verticalAlign:"middle"}}/>;
export default function ImpulTiendaLanding({brief,plan,mockup,offerData}:Props){
 const [main,setMain]=useState("");const [bonuses,setBonuses]=useState<Slot[]>(()=>Array.from({length:5},empty));const [upsells,setUpsells]=useState<Slot[]>(()=>Array.from({length:3},empty));const [heroDesktop,setHeroDesktop]=useState("");const [heroMobile,setHeroMobile]=useState("");const [html,setHtml]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [copied,setCopied]=useState(false);
 useEffect(()=>{if(mockup&&!main)setMain(mockup)},[mockup,main]);
 useEffect(()=>{if(!offerData)return;setBonuses(Array.from({length:5},(_,i)=>{const x=offerData?.bonuses?.[i];return x?{name:x.title||"",url:"",value:"",description:x.hook||x.role||x.brief||""}:empty()}));setUpsells(Array.from({length:3},(_,i)=>{const x=offerData?.upsells?.[i];return x?{name:x.title||"",url:"",value:"",description:x.hook||x.nextStep||x.brief||""}:empty()}))},[offerData]);
 const bonusCount=useMemo(()=>bonuses.filter(x=>x.name||x.url).length,[bonuses]);const upsellCount=useMemo(()=>upsells.filter(x=>x.name||x.url).length,[upsells]);
 function patch(kind:"bonus"|"upsell",i:number,key:keyof Slot,value:string){const setter=kind==="bonus"?setBonuses:setUpsells;setter(xs=>xs.map((x,n)=>n===i?{...x,[key]:value}:x))}
 async function generate(){setLoading(true);setError("");setCopied(false);try{const r=await fetch("/api/creator-ai/ebook/impultienda",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brief,plan,heroDesktop,heroMobile,assets:{main,bonuses:bonuses.filter(x=>x.name||x.url),upsells:upsells.filter(x=>x.name||x.url)}})});const j=await r.json();if(!r.ok)throw new Error(j.error||"No se pudo generar el HTML");setHtml(j.html||"")}catch(e:any){setError(e.message)}finally{setLoading(false)}}async function copy(){if(!html)return;await navigator.clipboard.writeText(html);setCopied(true)}
 return <section style={{marginTop:24,border:"1px solid #403767",borderRadius:22,padding:22,background:"linear-gradient(145deg,#0d0d16,#0a0910)"}}><div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap",alignItems:"flex-start"}}><div><div style={{display:"flex",alignItems:"center",gap:9}}><small style={{color:"#a98cff",fontWeight:900,letterSpacing:1}}>VYRAL ·</small><Logo height={25}/><small style={{color:"#a98cff",fontWeight:900,letterSpacing:1}}>LANDING</small></div><h3 style={{fontSize:28,margin:"9px 0 8px",display:"flex",alignItems:"center",gap:9,flexWrap:"wrap"}}>Landing HTML para <Logo height={30}/></h3><p style={{color:"#aaa",maxWidth:820,margin:0,lineHeight:1.55,display:"flex",alignItems:"center",gap:6,flexWrap:"wrap"}}>Exclusivo para <Logo height={18}/>. VYRAL ya detectó los nombres y descripciones del producto, bonos y upsells desde el ecosistema creado. Vos solamente cargás las URLs públicas de las imágenes.</p></div><div style={{padding:"8px 12px",borderRadius:999,background:"#1c1730",fontSize:12,color:"#c8baff"}}>Créditos solo al generar HTML</div></div>
 <div style={{marginTop:20,padding:18,borderRadius:16,background:"#12121c",border:"1px solid #30294c"}}><b>¿Cómo obtengo la URL de una imagen?</b><ol style={{color:"#bbb",lineHeight:1.7,marginBottom:0}}><li>Descargá o guardá el mockup generado por VYRAL.</li><li><span style={{display:"inline-flex",alignItems:"center",gap:6}}>Entrá a <Logo height={17}/> → Recursos y subí la imagen.</span></li><li><span style={{display:"inline-flex",alignItems:"center",gap:6}}>Copiá la <b>URL pública</b> que te entrega <Logo height={17}/>.</span></li><li>Pegala únicamente en el campo URL correspondiente de abajo. Los nombres y descripciones ya vienen completados automáticamente.</li><li><span style={{display:"inline-flex",alignItems:"center",gap:6,flexWrap:"wrap"}}>Cuando estén las imágenes que quieras usar, tocá <b>Generar HTML</b> <Logo height={17}/> y pegá el resultado en el editor HTML de tu tienda.</span></li></ol></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:12,marginTop:18}}><label><b>{plan?.title||"Producto principal"} *</b><input style={inputStyle} value={main} onChange={e=>setMain(e.target.value)} placeholder="Pegá la URL pública del mockup"/></label><label><b>Fondo hero desktop</b><input style={inputStyle} value={heroDesktop} onChange={e=>setHeroDesktop(e.target.value)} placeholder="URL opcional"/></label><label><b>Fondo hero celular</b><input style={inputStyle} value={heroMobile} onChange={e=>setHeroMobile(e.target.value)} placeholder="URL opcional"/></label></div>
 <h4 style={{margin:"24px 0 10px"}}>Bonos detectados · {bonusCount}/5</h4><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:10}}>{bonuses.map((x,i)=><div key={i} style={{padding:13,border:"1px solid #302b45",borderRadius:14,opacity:x.name?1:.55}}><b>{x.name||`Bono ${i+1} · opcional`}</b>{x.description&&<p style={{color:"#8f8f9c",fontSize:11,lineHeight:1.45}}>{x.description}</p>}<input style={{...inputStyle,marginTop:7}} value={x.url} onChange={e=>patch("bonus",i,"url",e.target.value)} placeholder="Pegá URL pública de la imagen"/><input style={{...inputStyle,marginTop:7}} value={x.value} onChange={e=>patch("bonus",i,"value",e.target.value)} placeholder="Valor/precio de referencia (opcional)"/></div>)}</div>
 <h4 style={{margin:"24px 0 6px"}}>Upsells detectados · {upsellCount}/3</h4><p style={{color:"#888",fontSize:12,marginTop:0}}>VYRAL los reconoce automáticamente como parte del ecosistema. Siguen siendo post-compra y no entran en la landing principal.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:10}}>{upsells.map((x,i)=><div key={i} style={{padding:13,border:"1px solid #302b45",borderRadius:14,opacity:x.name?1:.55}}><b>{x.name||`Upsell ${i+1} · opcional`}</b>{x.description&&<p style={{color:"#8f8f9c",fontSize:11,lineHeight:1.45}}>{x.description}</p>}<input style={{...inputStyle,marginTop:7}} value={x.url} onChange={e=>patch("upsell",i,"url",e.target.value)} placeholder="Pegá URL pública de la imagen"/><input style={{...inputStyle,marginTop:7}} value={x.value} onChange={e=>patch("upsell",i,"value",e.target.value)} placeholder="Precio (opcional)"/></div>)}</div>
 <div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:20}}><button onClick={generate} disabled={loading||!plan||!main.trim()} style={{...buttonStyle,opacity:loading||!main.trim()?.55:1,display:"inline-flex",alignItems:"center",gap:8}}>{loading?<>✦ Generando landing…</>:<>✦ Generar HTML <Logo height={19}/></>}</button>{html&&<button onClick={copy} style={buttonStyle}>{copied?"✓ HTML copiado":"Copiar HTML"}</button>}</div>{error&&<p style={{color:"#ff6b6b"}}>{error}</p>}{html&&<div style={{marginTop:18}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center"}}><b style={{display:"inline-flex",alignItems:"center",gap:7}}>HTML listo para <Logo height={18}/></b><small style={{color:"#888"}}>{html.length.toLocaleString()} caracteres</small></div><textarea readOnly value={html} style={{...inputStyle,marginTop:8,minHeight:420,fontFamily:"monospace",fontSize:12,lineHeight:1.45}}/></div>}</section>
}
