"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import "./crypto-checkout.css";
const coins=[{id:"btc",name:"Bitcoin",ticker:"BTC",icon:"/crypto/bitcoin.svg",network:"Bitcoin"},{id:"usdttrc20",name:"Tether",ticker:"USDT",icon:"/crypto/usdt.svg",network:"TRON (TRC20)"},{id:"eth",name:"Ethereum",ticker:"ETH",icon:"/crypto/ethereum.svg",network:"Ethereum"},{id:"sol",name:"Solana",ticker:"SOL",icon:"/crypto/solana.svg",network:"Solana"}];
type Payment={paymentId:string;status:string;payAddress:string;payAmount:string;payCurrency:string};
export default function CryptoCheckout({plan}:{plan:string;label?:string}){const[open,setOpen]=useState(false),[mounted,setMounted]=useState(false),[coin,setCoin]=useState("btc"),[payment,setPayment]=useState<Payment|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[qr,setQr]=useState(""),[copied,setCopied]=useState(false),[status,setStatus]=useState("");
 useEffect(()=>setMounted(true),[]);
 const selected=useMemo(()=>coins.find(x=>x.id===coin)!,[coin]);
 useEffect(()=>{if(!payment?.payAddress)return;setQr(`https://quickchart.io/qr?size=420&margin=1&text=${encodeURIComponent(payment.payAddress)}`)},[payment?.payAddress]);
 useEffect(()=>{if(!payment?.paymentId)return;let alive=true;const check=async()=>{try{const r=await fetch("/api/payments/nowpayments/status/"+payment.paymentId,{cache:"no-store"}),d=await r.json();if(alive&&r.ok)setStatus(String(d.status||""))}catch{}};check();const t=setInterval(check,7000);return()=>{alive=false;clearInterval(t)}},[payment?.paymentId]);
 async function start(id=coin){setLoading(true);setError("");setPayment(null);setQr("");setStatus("");try{const r=await fetch("/api/payments/nowpayments/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan,payCurrency:id})}),d=await r.json();if(!r.ok||!d.paymentId)throw Error(d.error||"No pudimos crear el pago");setPayment(d);setStatus(d.status||"waiting")}catch(e){setError(e instanceof Error?e.message:"No pudimos crear el pago")}finally{setLoading(false)}}
 function close(){setOpen(false);setPayment(null);setError("");setQr("");setStatus("")}
 const done=["finished"].includes(status),detected=["confirming","confirmed","sending","finished"].includes(status),partial=status==="partially_paid";
 if(plan!=="escala")return <div className="ccSoon">Pagar con criptomonedas <b>PRÓXIMAMENTE</b></div>;
 const modal=open&&mounted?createPortal(<div className="ccBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="ccModal"><button className="ccClose" onClick={close}>×</button><header><div className="ccBrand">V<span>Y</span>RAL <i>PAY</i></div><small>CRYPTO CHECKOUT · PLAN ESCALA</small><h2>{done?"Pago confirmado.":payment?"Completá tu transferencia.":"Elegí cómo querés pagar."}</h2><p>{done?"Tu pago fue confirmado. Tu plan se activará automáticamente.":payment?"Escaneá el QR o copiá la dirección exacta. No salís de VYRAL.":"Seleccioná el activo y VYRAL generará los datos exactos del pago."}</p></header>{!payment&&!done&&<><div className="ccCoins">{coins.map(c=><button key={c.id} className={coin===c.id?"active":""} onClick={()=>{setCoin(c.id);setError("")}}><img src={c.icon} alt=""/><span><b>{c.ticker}</b><small>{c.network}</small></span><i>{coin===c.id?"✓":""}</i></button>)}</div><div className="ccOrder"><span><small>PLAN</small><b>VYRAL Escala</b></span><span><small>TOTAL</small><b>US$ 19,99</b></span><span><small>PAGÁS CON</small><b>{selected.ticker}</b></span></div><button className="ccCreate" disabled={loading} onClick={()=>start()}>{loading?"GENERANDO PAGO SEGURO…":`CONTINUAR CON ${selected.ticker} →`}</button></>}{payment&&<div className="ccPayment"><div className="ccQr">{qr?<img src={qr} alt="QR de pago"/>:<span>GENERANDO QR…</span>}<i><img src={selected.icon} alt=""/></i></div><div className="ccDetails"><div className="ccAmount"><small>IMPORTE EXACTO</small><strong>{payment.payAmount} <i>{selected.ticker}</i></strong><span>≈ US$ 19,99 · {selected.network}</span></div><div className="ccAddress"><small>DIRECCIÓN DE PAGO</small><code>{payment.payAddress}</code><button onClick={async()=>{await navigator.clipboard.writeText(payment.payAddress);setCopied(true);setTimeout(()=>setCopied(false),1400)}}>{copied?"COPIADO ✓":"COPIAR"}</button></div><div className={"ccStatus "+(done?"done":detected?"detected":partial?"partial":"")}><span className="ccPulse"/><div><b>{done?"PAGO COMPLETADO":detected?"PAGO DETECTADO":partial?"PAGO PARCIAL":"ESPERANDO PAGO"}</b><small>{done?"Fondos confirmados por el procesador.":detected?"La blockchain está confirmando tu transferencia.":partial?"Se recibió menos del importe solicitado.":"Esta pantalla se actualiza automáticamente."}</small></div></div><div className="ccTimeline"><span className="on">1<b>Pago creado</b></span><i/><span className={detected?"on":""}>2<b>Detectado</b></span><i/><span className={done?"on":""}>3<b>Confirmado</b></span></div><button className="ccChange" onClick={()=>{setPayment(null);setQr("");setStatus("")}}>← Elegir otra criptomoneda</button></div></div>}{error&&<div className="ccError">{error}<button onClick={()=>start()}>Reintentar</button></div>}<footer><span>◆ PROCESADO DE FORMA SEGURA POR NOWPayments</span><b>VYRAL nunca almacena tus claves privadas.</b></footer></section></div>,document.body):null;
 return <><button className="ccLaunch" onClick={()=>setOpen(true)}>Pagar con criptomonedas <b>→</b></button>{modal}</>}