import { redirect } from "next/navigation";
import { getCustomerSession } from "../../lib/auth";
import PromoCodeBox from "./PromoCodeBox";
import "../registro/auth-flow.css";
import "./plans-polish.css";

const plans = [
  { id:"inicio", name:"Inicio", listPrice:"US$ 9,98", promoPrice:"US$ 4,99", cadence:"/ mes", accounts:"Hasta 2 cuentas", description:"Para empezar con VYRAL y centralizar publicaciones de forma simple.", features:["Hasta 2 cuentas conectadas","50 videos por mes","Publicación multicuentas","Panel centralizado","Historial de publicaciones","Soporte 24/7"], unavailable:["Top 5 de videos virales bloqueado","Sin Analytics","Sin VYRAL AI"], checkout:"https://vyralmulticuentas.lemonsqueezy.com/checkout/buy/084513ad-2a9c-453a-ae56-1ee76c73bb40" },
  { id:"pro", name:"Crecimiento", listPrice:"US$ 19,98", promoPrice:"US$ 9,99", cadence:"/ mes", accounts:"Hasta 5 cuentas", description:"Para creadores y negocios que quieren medir lo que funciona y tomar mejores decisiones.", features:["Hasta 5 cuentas conectadas","200 videos por mes","Publicación multicuentas","Top 5 de videos más virales","Analytics estándar: vistas, likes, comentarios y seguidores","Filtros por red y período","Comparativa de rendimiento por cuenta","VYRAL AI","Historial completo","Soporte 24/7"], unavailable:["Sin VYRAL Intelligence avanzado","Sin predicción ni recomendaciones premium"], featured:true, checkout:"https://vyralmulticuentas.lemonsqueezy.com/checkout/buy/1637355e-15b2-49ca-8bd1-1d5137d8e30b" },
  { id:"escala", name:"Escala", listPrice:"US$ 39,98", promoPrice:"US$ 19,99", cadence:"/ mes", accounts:"Hasta 30 cuentas", description:"Para operaciones que quieren convertir datos en decisiones, velocidad y crecimiento sostenido.", features:["Hasta 30 cuentas conectadas","500 videos por mes","Publicación multicuentas","Top 5 de videos más virales","Todo Analytics de Crecimiento","VYRAL Intelligence avanzado","Viral Momentum Score","Recomendaciones accionables con VYRAL AI","Content Intelligence: captions y formatos ganadores","Detección de patrones de contenido","Predicción de crecimiento y oportunidades","Alertas de rendimiento y próximas acciones","VYRAL AI completo","Historial completo","Soporte 24/7","Prioridad en nuevas funciones"], unavailable:[], checkout:"https://vyralmulticuentas.lemonsqueezy.com/checkout/buy/fbf20548-29e5-40af-8627-b52224bb3ed8" }
];

export default async function PlansPage({ searchParams }: { searchParams: Promise<{ error?: string; expired?: string }> }) {
  const session = await getCustomerSession();
  if (!session) redirect("/login");
  const q = await searchParams;
  const hasPlan = Boolean(session.plan);
  return (
    <main className="vyralPlansPage"><div className="vyralPlansWrap">
      <div style={{display:"flex",justifyContent:"flex-end",marginBottom:12}}><form action="/api/logout" method="post"><button type="submit" style={{border:"1px solid rgba(255,255,255,.12)",background:"rgba(5,10,13,.72)",color:"#9baab3",borderRadius:999,padding:"10px 16px",fontSize:11,fontWeight:700,letterSpacing:".04em",cursor:"pointer"}}>← Volver al login</button></form></div>
      <header className="vyralPlansTop"><div className="vyralAuthBrand">V<span>Y</span>RAL</div><small>PASO 03 / PLAN</small><h1>{hasPlan ? "Cambiá tu plan cuando lo necesites." : "Elegí cuántas cuentas querés activar."}</h1><p>A más cuentas conectadas, más puntos de distribución para cada video. Una sola carga consume 1 crédito mensual, aunque la distribuyas en varias cuentas.</p><div className="vyralPlansClaim">Hacerse viral nunca fue tan fácil.</div><div className="vyralSocialCluster" aria-label="Redes compatibles"><span className="vyralSocialLine" /><div className="vyralSocialNode"><img src="/tiktok.png" alt="TikTok" /></div><div className="vyralSocialNode"><img src="/instagram.png" alt="Instagram" /></div><div className="vyralSocialNode"><img src="/facebook.png" alt="Facebook" /></div><span className="vyralSocialLine" /></div></header>
      {q.expired === "1" && <div className="vyralAuthError" style={{maxWidth:700,margin:"0 auto 18px",textAlign:"center"}}>Tu plan finalizó. Elegí uno para volver a activar VYRAL.</div>}
      {q.error && <div className="vyralAuthError" style={{maxWidth:600,margin:"0 auto 18px",textAlign:"center"}}>No pudimos iniciar el pago. Probá nuevamente.</div>}
      <PromoCodeBox userId={session.userId} />
      <section className="vyralPlanGrid">{plans.map(plan=><article className={`vyralPlanCard${plan.featured?" featured":""}`} key={plan.id}>{plan.featured&&<div className="vyralPlanBadge">MÁS ELEGIDO</div>}<small>PLAN VYRAL</small><h2>{plan.name}</h2><div className="vyralPlanListPrice"><span>Precio de lista</span><del>{plan.listPrice}</del></div><div className="vyralPlanPrice"><strong>{plan.promoPrice}</strong><span>{plan.cadence}</span></div><div className="vyralPromoHint">Beneficio promocional con código válido · hasta 50% OFF</div><div className="vyralPlanAccounts">{plan.accounts}</div><p>{plan.description}</p><div className="vyralPlanFeatures">{plan.features.map(f=><span key={f}>{f}</span>)}{plan.unavailable.map(f=><span className="off" key={f}>{f}</span>)}</div><a className="vyralPlanCheckout" data-vyral-checkout={plan.checkout} href={plan.checkout}>{hasPlan ? `Cambiar a ${plan.name}` : `Elegir ${plan.name}`} →</a></article>)}</section>
      <footer className="vyralPlansTrust"><div className="vyralTrustLinks"><span className="vyralSecure">⌁ Pago seguro</span><a href="/terms">Términos y condiciones</a><span>·</span><a href="/privacy">Política de privacidad</a></div><p>Facturación mensual. Los créditos de video se renuevan cada mes. Los códigos promocionales válidos se aplican en el checkout.</p><div className="vyralPlansPowered"><span>Powered by</span><strong>Tobias Carrizo</strong></div></footer>
    </div></main>
  );
}
