"use client";

import { useEffect,useMemo,useState } from "react";

const base:Record<string,{views:number;likes:number;comments:number;followers:number;shares:number}>={all:{views:284750,likes:31420,comments:2840,followers:4680,shares:8210},tiktok:{views:198400,likes:24100,comments:2110,followers:3310,shares:6280},instagram:{views:51200,likes:4680,comments:410,followers:730,shares:1090},facebook:{views:21400,likes:1640,comments:190,followers:390,shares:520},youtube:{views:13750,likes:1000,comments:130,followers:250,shares:320}};
const factors:Record<string,number>={"7d":.27,"30d":1,"90d":2.7,"custom":1};
const fmt=(v:number)=>new Intl.NumberFormat("es-AR").format(Math.round(v));

export default function AnalyticsFilterPanel(){
 const [visible,setVisible]=useState(false);const [network,setNetwork]=useState("all");const [period,setPeriod]=useState("30d");const [from,setFrom]=useState("");const [to,setTo]=useState("");
 useEffect(()=>{const sync=()=>{const a=document.querySelector(".vdNav button.active");setVisible((a?.textContent||"").toLowerCase().includes("analytics"));};sync();const nav=document.querySelector(".vdNav");const obs=new MutationObserver(sync);if(nav)obs.observe(nav,{attributes:true,subtree:true,attributeFilter:["class"]});document.addEventListener("click",sync,true);return()=>{obs.disconnect();document.removeEventListener("click",sync,true)}},[]);
 const d=useMemo(()=>{let f=factors[period]||1;if(period==="custom"&&from&&to){const days=Math.max(1,(new Date(to).getTime()-new Date(from).getTime())/86400000);f=Math.min(6,days/30)}const b=base[network];return Object.fromEntries(Object.entries(b).map(([k,v])=>[k,v*f])) as typeof b;},[network,period,from,to]);
 if(!visible)return null;
 return <section className="userAnalyticsAddon"><div className="userAnalyticsToolbar"><div><small>FILTROS DE RENDIMIENTO</small><h3>Analizá tu crecimiento por red y período.</h3></div><div className="userAnalyticsControls"><select value={network} onChange={e=>setNetwork(e.target.value)}><option value="all">Todas las redes</option><option value="tiktok">TikTok</option><option value="instagram">Instagram</option><option value="facebook">Facebook</option><option value="youtube">YouTube</option></select><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="7d">Últimos 7 días</option><option value="30d">Últimos 30 días</option><option value="90d">Últimos 90 días</option><option value="custom">Fecha a fecha</option></select>{period==="custom"&&<><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></>}</div></div><div className="userAnalyticsMetrics"><article><span>Vistas</span><b>{fmt(d.views)}</b><i>↑ 18,4%</i></article><article><span>Me gusta</span><b>{fmt(d.likes)}</b><i>↑ 11,0%</i></article><article><span>Comentarios</span><b>{fmt(d.comments)}</b><i>↑ 8,2%</i></article><article><span>Seguidores</span><b>+{fmt(d.followers)}</b><i>↑ 12,6%</i></article><article><span>Compartidos</span><b>{fmt(d.shares)}</b><i>↑ 9,3%</i></article></div><div className="userAnalyticsFoot">Los filtros ya están preparados para consolidar TikTok, Instagram, Facebook y YouTube a medida que se habiliten sus conectores de métricas.</div></section>;
}
