"use client";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import "./automation-studio.css";
import "./automation-agent-pro.css";

type Platform="instagram"|"facebook"|"tiktok";
type Goal="sell"|"whatsapp"|"book"|"lead"|"support"|"resource";
type Automation={id?:string;name:string;enabled:boolean;platforms:Platform[];contentLabel:string;triggerMode:"exact"|"contains"|"ai_intent";keywords:string[];excludeKeywords:string[];publicReplyEnabled:boolean;publicReply:string;dmEnabled:boolean;dmMessage:string;dmLink:string;resourceName:string;resourceUrl:string;aiEnabled:boolean;aiTone:string;aiInstructions:string;aiConfidence:number;humanHandoff:boolean;collectLead:boolean;leadTag:string;cooldownMinutes:number;maxRepliesPerUser:number;smartGuard:boolean;conversionGoal:"link_click"|"dm_started"|"lead"|"none";conversationGoal:Goal;autonomy:"guided"|"balanced"|"high";personalizeName:boolean;continueConversation:boolean;qualifyLead:boolean;whatsappTarget:string;ctaText:string;voiceEnabled:boolean;voiceAssetName:string;voiceAssetUrl:string;voiceWhen:"never"|"hot"|"manual"};
type SimMsg={role:"user"|"assistant";text:string;stage?:string;confidence?:number;action?:string;audio?:boolean;resource?:boolean};
const fresh=():Automation=>({name:"VYRAL Sales Agent",enabled:true,platforms:["instagram","facebook"],contentLabel:"",triggerMode:"ai_intent",keywords:["precio","info","quiero","guia"],excludeKeywords:[],publicReplyEnabled:true,publicReply:"¡Te escribí por privado! 👋",dmEnabled:true,dmMessage:"¡Hola! Vi tu comentario. ¿Qué te gustaría saber?",dmLink:"",resourceName:"",resourceUrl:"",aiEnabled:true,aiTone:"Cercano, profesional y natural",aiInstructions:"Conversá de forma breve y útil. Hacé una pregunta por vez. No inventes datos. Detectá intención de compra y avanzá hacia el objetivo sin presionar.",aiConfidence:.78,humanHandoff:true,collectLead:true,leadTag:"vyral-qualified",cooldownMinutes:15,maxRepliesPerUser:20,smartGuard:true,conversionGoal:"lead",conversationGoal:"sell",autonomy:"high",personalizeName:true,continueConversation:true,qualifyLead:true,whatsappTarget:"",ctaText:"",voiceEnabled:false,voiceAssetName:"",voiceAssetUrl:"",voiceWhen:"hot"});
const goals:{id:Goal;icon:string;title:string;desc:string}[]=[{id:"sell",icon:"◎",title:"Vender",desc:"Califica y guía al cierre"},{id:"whatsapp",icon:"↗",title:"Llevar a WhatsApp",desc:"Detecta el momento ideal"},{id:"book",icon:"◫",title:"Agendar",desc:"Conduce hacia una reserva"},{id:"lead",icon:"◇",title:"Captar lead",desc:"Identifica oportunidades"},{id:"support",icon:"?",title:"Resolver consultas",desc:"Responde y escala"},{id:"resource",icon:"↓",title:"Entregar recurso",desc:"Catálogo, guía o archivo"}];
const socials={instagram:["Instagram","/instagram.png"],facebook:["Facebook","/facebook.png"],tiktok:["TikTok","/tiktok.png"]} as const;
export default function AutomationStudio(){
 const[mount,setMount]=useState<HTMLElement|null>(null),[open,setOpen]=useState(false),[draft,setDraft]=useState<Automation>(fresh()),[saved,setSaved]=useState<Automation[]>([]),[saving,setSaving]=useState(false),[notice,setNotice]=useState(""),[test,setTest]=useState("Hola, vi el video y me interesa. ¿Cuánto sale?"),[testing,setTesting]=useState(false),[filename,setFilename]=useState(""),[sim,setSim]=useState<SimMsg[]>([]),[resourceFile,setResourceFile]=useState<File|null>(null),[audioUrl,setAudioUrl]=useState(""),[recording,setRecording]=useState(false);
 const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]);
 useEffect(()=>{const sync=()=>{const b=document.querySelector(".vdPublishBtn");const c=b?.closest(".vdCard") as HTMLElement|null;if(c)setMount(c);const i=c?.querySelector('input[type="file"]') as HTMLInputElement|null;if(i?.files?.[0])setFilename(i.files[0].name)};sync();const t=setInterval(sync,300);return()=>clearInterval(t)},[]);
 useEffect(()=>{fetch("/api/automations").then(r=>r.json()).then(j=>setSaved((j.automations||[]).map((x:Automation)=>({...fresh(),...x})))).catch(()=>{})},[]);
 const set=<K extends keyof Automation>(k:K,v:Automation[K])=>setDraft(d=>({...d,[k]:v}));
 const toggle=(p:Platform)=>{if(p==="tiktok")return;set("platforms",draft.platforms.includes(p)?draft.platforms.filter(x=>x!==p):[...draft.platforms,p])};
 async function save(){setSaving(true);setNotice("");try{const r=await fetch("/api/automations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const j=await r.json();if(!r.ok)throw new Error(j.error);setDraft({...fresh(),...j.automation});setSaved((j.automations||[]).map((x:Automation)=>({...fresh(),...x})));setNotice("✓ Agente guardado y listo para conectar al canal.")}catch(e:any){setNotice(e.message||"No se pudo guardar")}finally{setSaving(false)}}
 async function sendSimulation(){if(!test.trim()||testing)return;const user:SimMsg={role:"user",text:test.trim()};const history=[...sim,user];setSim(history);setTest("");setTesting(true);try{const r=await fetch("/api/ai/automation-agent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({automation:draft,username:"tobias.demo",incoming:user.text,history:history.slice(0,-1).map(x=>({role:x.role,text:x.text})),businessContext:"Simulación VYRAL. Usá solamente la configuración del agente y los datos cargados; no inventes precios ni condiciones.",publicationContext:draft.contentLabel||filename||"Publicación actual"})});const j=await r.json();if(!r.ok)throw new Error(j.error);const a=j.result||{};const shouldAudio=draft.voiceEnabled&&!!audioUrl&&(draft.voiceWhen==="manual"||(draft.voiceWhen==="hot"&&a.leadStage==="hot"));const shouldResource=!!resourceFile&&(a.suggestedAction==="send_resource"||draft.conversationGoal==="resource"&&["qualified","hot","converted"].includes(a.leadStage));setSim(x=>[...x,{role:"assistant",text:a.reply||"",stage:a.leadStage,confidence:a.confidence,action:a.suggestedAction,audio:shouldAudio,resource:shouldResource}])}catch(e:any){setSim(x=>[...x,{role:"assistant",text:e.message||"VYRAL Intelligence no está disponible en este momento."}])}finally{setTesting(false)}}
 function resetSimulation(){setSim([]);setTest("Hola, vi el video y me interesa. ¿Cuánto sale?")}
 async function toggleRecord(){if(recording){recorder.current?.stop();setRecording(false);return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);chunks.current=[];r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=()=>{const blob=new Blob(chunks.current,{type:r.mimeType||"audio/webm"});if(audioUrl)URL.revokeObjectURL(audioUrl);const url=URL.createObjectURL(blob);setAudioUrl(url);set("voiceEnabled",true);set("voiceAssetName","Audio grabado en VYRAL");stream.getTracks().forEach(t=>t.stop())};recorder.current=r;r.start();setRecording(true)}catch{setNotice("No pudimos acceder al micrófono. Revisá el permiso del navegador.")}}
 const compact=<div className="vaCompact vaCompactPro"><div className="vaCompactTop"><div><span className="vaPulse"/><small>VYRAL AUTOMATIONS · AI SALES AGENT</small><strong>Convertí comentarios en conversaciones que avanzan solas.</strong><p>VYRAL Intelligence, memoria conversacional, calificación de leads, objetivos comerciales, voz y handoff humano.</p></div><button className="vaOpen" onClick={()=>setOpen(true)}>{draft.id?"Editar agente":"+ Crear agente IA"}</button></div>{saved.length>0&&<div className="vaQuickRow"><span>✦ VYRAL Intelligence online</span><span>◎ {saved.length} agente{saved.length===1?"":"s"}</span><span className="vaSavedCount">Meta · pendiente de API</span></div>}</div>;
 const modal=open?<div className="vaOverlay" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><div className="vaModal vaAgentModal"><header className="vaHeader"><div><small>VYRAL AUTOMATION STUDIO</small><h2>AI Sales Agent <em>2.1</em></h2><p>Diseñá un agente que entiende, conversa, califica y persigue un objetivo comercial.</p></div><div className="vaAgentBadges"><span>✦ VYRAL INTELLIGENCE</span><span className="pending">META READY</span></div><button className="vaClose" onClick={()=>setOpen(false)}>×</button></header><div className="vaAgentGrid"><main>
 <section className="vaAgentSection"><div className="vaSectionTitle"><span>01</span><div><b>Canales y activación</b><small>Preparado para operar por publicación cuando conectemos Meta.</small></div></div><div className="vaPlatformRow">{(["instagram","facebook","tiktok"] as Platform[]).map(p=>{const [n,icon]=socials[p],off=p==="tiktok";return <button key={p} disabled={off} className={`${draft.platforms.includes(p)?"active":""} ${off?"disabled":""}`} onClick={()=>toggle(p)}><span className="vaSocialIcon"><img src={icon} alt=""/></span><b>{n}</b>{off?<em>PRÓXIMAMENTE</em>:<small>{draft.platforms.includes(p)?"ACTIVO":"ACTIVAR"}</small>}</button>})}</div><label className="vaLabel">Nombre del agente</label><input className="vaInput" value={draft.name} onChange={e=>set("name",e.target.value)}/><div className="vaIntentChoice"><button className={draft.triggerMode==="ai_intent"?"active":""} onClick={()=>set("triggerMode","ai_intent")}>✦ Detectar intención con IA</button><button className={draft.triggerMode==="contains"?"active":""} onClick={()=>set("triggerMode","contains")}>Palabras clave</button></div>{draft.triggerMode!=="ai_intent"&&<input className="vaInput" value={draft.keywords.join(", ")} onChange={e=>set("keywords",e.target.value.split(",").map(x=>x.trim()).filter(Boolean))} placeholder="precio, info, catálogo"/>}</section>
 <section className="vaAgentSection"><div className="vaSectionTitle"><span>02</span><div><b>Objetivo del agente</b><small>VYRAL cambia su estrategia según lo que querés conseguir.</small></div></div><div className="vaGoalGrid">{goals.map(g=><button key={g.id} className={draft.conversationGoal===g.id?"active":""} onClick={()=>set("conversationGoal",g.id)}><i>{g.icon}</i><b>{g.title}</b><small>{g.desc}</small></button>)}</div>{draft.conversationGoal==="whatsapp"&&<><label className="vaLabel">WhatsApp destino</label><input className="vaInput" value={draft.whatsappTarget} onChange={e=>set("whatsappTarget",e.target.value)} placeholder="+54 9 11..."/></>}<label className="vaLabel">CTA / resultado deseado</label><input className="vaInput" value={draft.ctaText} onChange={e=>set("ctaText",e.target.value)} placeholder="Ej: llevarlo a WhatsApp cuando muestre intención real"/></section>
 <section className="vaAgentSection"><div className="vaSectionTitle"><span>03</span><div><b>VYRAL Intelligence</b><small>El cerebro que mantiene la conversación y decide el siguiente paso.</small></div></div><div className="vaBrain"><div className="vaBrainOrb">✦</div><div><b>VYRAL Intelligence Core</b><p>Contexto del negocio + publicación + historial + intención + objetivo, dentro de una sola estrategia conversacional.</p></div><span>ONLINE</span></div><div className="vaControlGrid">{[["personalizeName","Usar nombre / @user","Personaliza cuando el canal lo provea"],["continueConversation","Conversación continua","No se detiene después del primer DM"],["qualifyLead","Lead Scoring IA","New → Curious → Qualified → Hot"],["humanHandoff","Human Handoff","Escala casos sensibles o inciertos"],["smartGuard","Smart Guard","Evita loops, spam y duplicados"],["collectLead","Opportunity Memory","Conserva señales de intención"]].map(([k,t,d])=><label key={k} className={(draft as any)[k]?"on":""}><input type="checkbox" checked={(draft as any)[k]} onChange={e=>setDraft(x=>({...x,[k]:e.target.checked}))}/><b>{t}</b><small>{d}</small></label>)}</div><div className="vaAiSettings"><div className="vaTwo"><div><label className="vaLabel">Autonomía</label><select className="vaInput" value={draft.autonomy} onChange={e=>set("autonomy",e.target.value as any)}><option value="guided">Guiada</option><option value="balanced">Balanceada</option><option value="high">Alta · recomendada</option></select></div><div><label className="vaLabel">Tono</label><input className="vaInput" value={draft.aiTone} onChange={e=>set("aiTone",e.target.value)}/></div></div><label className="vaLabel">Instrucciones y reglas del negocio</label><textarea className="vaTextarea" value={draft.aiInstructions} onChange={e=>set("aiInstructions",e.target.value)}/></div></section>
 <section className="vaAgentSection"><div className="vaSectionTitle"><span>04</span><div><b>Recursos del agente</b><small>Cargá el material que VYRAL podrá entregar cuando corresponda.</small></div></div><div className="vaUploadBox"><b>Archivo / catálogo</b><small>{resourceFile?`✓ ${resourceFile.name}`:"PDF, imagen, catálogo o recurso comercial"}</small><label className="vaUploadButton">{resourceFile?"Cambiar archivo":"+ Cargar archivo"}<input type="file" hidden onChange={e=>{const f=e.target.files?.[0]||null;setResourceFile(f);if(f)set("resourceName",f.name)}}/></label></div></section>
 <section className="vaAgentSection"><div className="vaSectionTitle"><span>05</span><div><b>Voice Studio</b><small>Último paso: prepará audios después de definir estrategia, objetivo y recursos.</small></div></div><div className="vaVoiceCard"><div className="vaVoiceIntro"><span>◉</span><div><b>Audio inteligente</b><small>Grabalo dentro de VYRAL. El simulador puede reproducirlo cuando el lead llegue al momento configurado.</small></div></div><button className={`vaRecord ${recording?"recording":""}`} onClick={toggleRecord}>{recording?"■ Detener grabación":"● Grabar audio en VYRAL"}</button>{audioUrl&&<div className="vaRecorded"><audio controls src={audioUrl}/><span>✓ Audio listo</span></div>}<label className="vaLabel">¿Cuándo usarlo?</label><select className="vaInput" value={draft.voiceWhen} onChange={e=>set("voiceWhen",e.target.value as any)}><option value="hot">Cuando el lead esté HOT</option><option value="manual">Cuando la estrategia lo indique</option><option value="never">No usar audio</option></select></div></section>
 </main><aside className="vaAgentAside"><div className="vaSticky"><div className="vaLabHead"><div><small>LIVE AI LAB</small><h3>Simulación completa</h3></div>{sim.length>0&&<button onClick={resetSimulation}>Reiniciar</button>}</div><p>Conversá con VYRAL como si fueras un cliente real. Mantiene memoria y simula texto, audio, archivos y siguiente acción.</p><div className="vaDemoUser"><span>@</span><div><b>@tobias.demo</b><small>Instagram · simulación</small></div></div><div className="vaChatSim">{sim.length===0&&<div className="vaEmptyChat">Escribí el primer mensaje para iniciar la conversación completa.</div>}{sim.map((m,i)=><div key={i} className={`vaBubble ${m.role}`}><small>{m.role==="user"?"@tobias.demo":"VYRAL"}</small>{m.text&&<p>{m.text}</p>}{m.audio&&audioUrl&&<div className="vaSimAsset"><span>🎙 Audio inteligente</span><audio controls src={audioUrl}/></div>}{m.resource&&resourceFile&&<div className="vaSimFile"><span>▣</span><div><b>{resourceFile.name}</b><small>Archivo enviado por VYRAL</small></div></div>}{m.role==="assistant"&&m.stage&&<div className="vaSimMeta"><span>{m.stage}</span><span>{Math.round((m.confidence||0)*100)}%</span><span>{m.action}</span></div>}</div>)}{testing&&<div className="vaThinking">✦ VYRAL está pensando…</div>}</div><div className="vaComposer"><textarea className="vaTextarea" value={test} onChange={e=>setTest(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendSimulation()}}} placeholder="Respondé como el cliente…"/><button className="vaTestAI" disabled={testing||!test.trim()} onClick={sendSimulation}>{sim.length?"Enviar siguiente mensaje":"✦ Iniciar simulación"}</button></div><div className="vaSimReady"><span className={audioUrl?"ready":""}>🎙 {audioUrl?"Audio cargado":"Sin audio"}</span><span className={resourceFile?"ready":""}>▣ {resourceFile?"Archivo cargado":"Sin archivo"}</span></div><div className="vaJourney"><b>Journey en vivo</b><div><span>1</span>Comentario / mensaje</div><div><span>2</span>Respuesta contextual</div><div><span>3</span>Conversación + memoria</div><div><span>4</span>Lead scoring</div><div><span>5</span>Audio / archivo / CTA / humano</div></div><div className="vaReadiness"><div><b>VYRAL Intelligence</b><span className="ok">ONLINE</span></div><div><b>Instagram / Facebook</b><span>ESPERANDO API META</span></div><div><b>TikTok</b><span>PRÓXIMAMENTE</span></div></div></div></aside></div><footer className="vaFooter"><div>{notice||"Los cambios se guardan en tu cuenta VYRAL."}</div><button className="vaSave" disabled={saving} onClick={save}>{saving?"Guardando…":"Guardar AI Sales Agent"}</button></footer></div></div>:null;
 return <>{mount&&createPortal(compact,mount)}{open&&typeof document!=="undefined"&&createPortal(modal,document.body)}</>;
}
