"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import "./bulk-publisher.css";

type Item={id:string;file:File;status:"queued"|"processing"|"ready"|"error";context:string;goal:string;caption:string;score?:number;error?:string};
const goals=["VYRAL decide","Ventas","Leads","WhatsApp","Crecimiento"];
export default function BulkPublisher({enabled}:{enabled:boolean}){
 const[open,setOpen]=useState(false),[items,setItems]=useState<Item[]>([]),[running,setRunning]=useState(false),[globalGoal,setGlobalGoal]=useState("VYRAL decide"),[publishTarget,setPublishTarget]=useState<HTMLElement|null>(null);
 useEffect(()=>{const sync=()=>setPublishTarget(document.querySelector<HTMLElement>(".isPublishSection .vdGrid .vdCard:first-child"));sync();const obs=new MutationObserver(sync);obs.observe(document.body,{subtree:true,attributes:true,attributeFilter:["class"]});return()=>obs.disconnect()},[]);
 const ready=items.filter(x=>x.status==="ready").length;
 const summary=useMemo(()=>({total:items.length,ready,agents:items.filter(x=>x.status==="ready"&&/coment|cta|whatsapp|recurso|lead/i.test(x.context)).length}),[items,ready]);
 function add(files:FileList|null){if(!files)return;const next=Array.from(files).filter(f=>f.type.startsWith("video/")).map(file=>({id:crypto.randomUUID(),file,status:"queued" as const,context:"",goal:globalGoal,caption:""}));setItems(v=>[...v,...next])}
 async function processOne(item:Item){
  setItems(v=>v.map(x=>x.id===item.id?{...x,status:"processing"}:x));
  try{
   const prep=await fetch("/api/ai/automation-voice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"assembly-prepare",fileName:item.file.name,fileSize:item.file.size,mimeType:item.file.type})}),pj=await prep.json().catch(()=>({}));
   if(!prep.ok||!pj.signedUrl)throw Error(pj.error||"No se pudo preparar el video.");
   const up=await fetch(pj.signedUrl,{method:"PUT",headers:{"Content-Type":item.file.type||"application/octet-stream"},body:item.file});if(!up.ok)throw Error("Falló la carga del video.");
   const tr=await fetch("/api/ai/automation-voice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"openai-transcribe-stored",path:pj.path})}),tj=await tr.json().catch(()=>({}));if(!tr.ok)throw Error(tj.error||"No se pudo entender la voz.");
   const fd=new FormData();fd.set("mode","understand-video");fd.set("transcript",String(tj.transcript||""));const ur=await fetch("/api/ai/automation-voice",{method:"POST",body:fd}),uj=await ur.json().catch(()=>({}));if(!ur.ok)throw Error(uj.error||"No se pudo generar contexto.");
   const context=String(uj.context||"").trim();setItems(v=>v.map(x=>x.id===item.id?{...x,status:"ready",context,goal:x.goal==="VYRAL decide"?(/whatsapp/i.test(context)?"WhatsApp":/vend|precio|compr/i.test(context)?"Ventas":/lead|coment|recurso/i.test(context)?"Leads":"Crecimiento"):x.goal}:x));
  }catch(e:any){setItems(v=>v.map(x=>x.id===item.id?{...x,status:"error",error:e.message||"Error"}:x))}
 }
 async function processAll(){if(running)return;setRunning(true);const pending=items.filter(x=>x.status==="queued"||x.status==="error");for(let i=0;i<pending.length;i+=3)await Promise.all(pending.slice(i,i+3).map(processOne));setRunning(false)}
 const entry=!enabled?<div className="vbEntry locked"><div><small>ESCALA · VYRAL BULK</small><b>Publicación masiva con inteligencia</b><span>Procesá y organizá muchos videos en una sola sesión.</span></div><a href="/mi-plan#upgrade">Desbloquear Escala ↗</a></div>;
 return <><div className="vbEntry"><div><small>ESCALA · VYRAL BULK</small><b>Publicación masiva con inteligencia</b><span>Subí un lote: VYRAL entiende cada video por separado. ⚡ Horas de operación convertidas en minutos.</span></div><button onClick={()=>setOpen(true)}>✦ Abrir VYRAL Bulk</button></div>;
 return <>{publishTarget&&createPortal(entry,publishTarget)}{open&&<div className="vbBack" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><div className="vbModal"><header><div><small>VYRAL BULK INTELLIGENCE · ESCALA</small><h2>Un lote. Contextos distintos. Una sola operación.</h2><p>Cargá videos y VYRAL escucha, entiende y propone un objetivo individual para cada uno. Menos horas operativas, menos herramientas y más contenido trabajando por vos.</p></div><button onClick={()=>setOpen(false)}>×</button></header><div className="vbToolbar"><label>+ Agregar videos<input hidden type="file" accept="video/*" multiple onChange={e=>add(e.target.files)}/></label><select value={globalGoal} onChange={e=>setGlobalGoal(e.target.value)}>{goals.map(g=><option key={g}>{g}</option>)}</select><button disabled={!items.length||running} onClick={processAll}>{running?"✦ Analizando lote…":"✦ Analizar todos"}</button></div><div className="vbStats"><span><b>{summary.total}</b> videos</span><span><b>{summary.ready}</b> entendidos</span><span><b>{summary.agents}</b> agentes sugeridos</span></div><main className="vbList">{!items.length&&<div className="vbDrop"><strong>Arrastrá tu biblioteca de contenido acá</strong><span>o usá “Agregar videos”. Cada archivo conserva su propio contexto y objetivo.</span></div>}{items.map((x,i)=><article key={x.id}><div className="vbNum">{String(i+1).padStart(2,"0")}</div><div className="vbInfo"><b>{x.file.name}</b><small>{x.status==="queued"?"Esperando análisis":x.status==="processing"?"✦ Escuchando y entendiendo…":x.status==="ready"?"✓ Contexto listo":"⚠ "+x.error}</small>{x.context&&<p>{x.context}</p>}</div><select value={x.goal} onChange={e=>setItems(v=>v.map(y=>y.id===x.id?{...y,goal:e.target.value}:y))}>{goals.map(g=><option key={g}>{g}</option>)}</select><button className="vbRemove" onClick={()=>setItems(v=>v.filter(y=>y.id!==x.id))}>×</button></article>)}</main><footer><span>{ready===items.length&&ready>0?"✓ Lote entendido. Próximo paso: revisar y organizar calendario.":"VYRAL procesa hasta 3 videos en paralelo para mantener estabilidad."}</span><button disabled={!ready}>Continuar al calendario →</button></footer></div></div>}</>
}