"use client";
import { useEffect,useState } from "react";
import { createPortal } from "react-dom";
import "./vyral-ai.css";

type AIResult={caption:string;hashtags:string[];viralScore:number;hook:string;cta:string;strengths:string[];improvements:string[];platformTips?:Record<string,string>};
async function frame(file:File){return new Promise<string>((resolve,reject)=>{const video=document.createElement("video");const url=URL.createObjectURL(file);video.muted=true;video.preload="metadata";video.onloadedmetadata=()=>{video.currentTime=Math.min(Math.max(video.duration*.18,.1),2)};video.onseeked=()=>{try{const c=document.createElement("canvas");const max=720;const scale=Math.min(1,max/video.videoWidth);c.width=Math.max(1,Math.round(video.videoWidth*scale));c.height=Math.max(1,Math.round(video.videoHeight*scale));c.getContext("2d")?.drawImage(video,0,0,c.width,c.height);const out=c.toDataURL("image/jpeg",.72);URL.revokeObjectURL(url);resolve(out)}catch(e){URL.revokeObjectURL(url);reject(e)}};video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("No pude leer el video."))};video.src=url})}
function notice(title:string,message:string,tone="info"){window.dispatchEvent(new CustomEvent("vyral:notify",{detail:{title,message,tone}}))}
export default function VyralAI(){const [mount,setMount]=useState<HTMLElement|null>(null);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [result,setResult]=useState<AIResult|null>(null);
 useEffect(()=>{const sync=()=>{const area=document.querySelector<HTMLElement>(".vdTextarea");const card=area?.closest<HTMLElement>(".vdCard")||null;if(card!==mount)setMount(card)};sync();const t=setInterval(sync,500);return()=>clearInterval(t)},[mount]);
 async function analyze(){const input=document.querySelector<HTMLInputElement>('.vdUpload input[type="file"]');const file=input?.files?.[0];const caption=(document.querySelector<HTMLTextAreaElement>(".vdTextarea")?.value||"").trim();if(!file&&!caption){notice("VYRAL AI necesita contenido","Subí un video o escribí una descripción para analizar.","warning");return}setBusy(true);try{let image="";if(file)image=await frame(file);const r=await fetch("/api/ai/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({caption,image,language:localStorage.getItem("vyral-lang")||"es"})});const j=await r.json();if(!r.ok)throw new Error(j.error||"No se pudo ejecutar VYRAL AI.");setResult(j.result);setOpen(true)}catch(e:any){notice("VYRAL AI",e.message||"No se pudo analizar el contenido.","warning")}finally{setBusy(false)}}
 function apply(){if(!result)return;const area=document.querySelector<HTMLTextAreaElement>(".vdTextarea");if(area){const text=`${result.caption}${result.hashtags?.length?"\n\n"+result.hashtags.map(x=>`#${String(x).replace(/^#/,"")}`).join(" "):""}`.slice(0,2200);const setter=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,"value")?.set;setter?.call(area,text);area.dispatchEvent(new Event("input",{bubbles:true}));area.dispatchEvent(new Event("change",{bubbles:true}))}notice("VYRAL AI aplicado","La descripción y los hashtags fueron actualizados.","success");setOpen(false)}
 if(!mount)return null;return createPortal(<><div className="vaiBar"><div><small>✦ VYRAL AI</small><strong>Potenciá este contenido antes de publicarlo</strong><span>Analiza el video, mejora el caption y propone hooks, CTA y hashtags.</span></div><button type="button" onClick={analyze} disabled={busy}>{busy?"Analizando…":"✦ Mejorar con IA"}</button></div>{open&&result&&<div className="vaiBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="vaiModal"><button className="vaiClose" onClick={()=>setOpen(false)}>×</button><div className="vaiTitle"><div><small>VYRAL INTELLIGENCE</small><h2>Análisis de contenido</h2></div><div className="vaiScore"><b>{result.viralScore}</b><span>/100</span></div></div><div className="vaiHero"><small>HOOK RECOMENDADO</small><strong>{result.hook}</strong><p>{result.caption}</p></div><div className="vaiCols"><div><small>LO QUE FUNCIONA</small>{result.strengths?.map((x,i)=><p key={i}>✓ {x}</p>)}</div><div><small>PARA MEJORAR</small>{result.improvements?.map((x,i)=><p key={i}>↗ {x}</p>)}</div></div><div className="vaiTips"><div><b>TikTok</b><span>{result.platformTips?.tiktok}</span></div><div><b>Instagram</b><span>{result.platformTips?.instagram}</span></div><div><b>Facebook</b><span>{result.platformTips?.facebook}</span></div></div><div className="vaiFooter"><span>CTA: {result.cta}</span><button onClick={apply}>Aplicar a la publicación ↗</button></div></div></div>}</>,mount)}
