"use client";
import {useState} from "react";
import "./vyral-coach.css";

type Tool={id:string;icon:string;title:string;desc:string;placeholder:string};
const tools:Tool[]=[
{id:"strategy",icon:"◈",title:"¿Qué publico hoy?",desc:"Ideas de contenido alineadas a tu negocio, objetivo y audiencia.",placeholder:"Ej: vendo indumentaria mayorista y quiero conseguir revendedores"},
{id:"script",icon:"✎",title:"Guionista IA",desc:"Hooks, desarrollo y CTA listos para grabar.",placeholder:"Contame qué querés vender o comunicar"},
{id:"hooks",icon:"⚡",title:"Generador de hooks",desc:"Aperturas diseñadas para ganar atención en los primeros segundos.",placeholder:"Pegá tu idea, tema o caption actual"},
{id:"repurpose",icon:"↻",title:"Reutilizador viral",desc:"Convierte una idea ganadora en nuevas variantes sin repetirla.",placeholder:"Describí el video o idea que querés reutilizar"},
{id:"calendar",icon:"▦",title:"Calendario IA",desc:"Construye un plan de contenidos accionable para los próximos días.",placeholder:"Ej: 2 videos diarios durante 7 días para una inmobiliaria"},
{id:"comments",icon:"◇",title:"Asistente de comentarios",desc:"Propone respuestas, detecta intención de compra y preguntas frecuentes.",placeholder:"Pegá comentarios o preguntas de tu audiencia"}
];
function notify(title:string,text:string,tone:"good"|"info"|"warn"="info"){window.dispatchEvent(new CustomEvent("vyral:notify",{detail:{title,text,tone}}))}
export default function VyralCoach({enabled}:{enabled:boolean}){const [active,setActive]=useState<Tool|null>(null);const [prompt,setPrompt]=useState("");const [busy,setBusy]=useState(false);const [answer,setAnswer]=useState("");async function run(){if(!active||!prompt.trim())return;setBusy(true);setAnswer("");try{const r=await fetch("/api/ai/coach",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:active.id,prompt:prompt.trim(),language:localStorage.getItem("vyral-lang")||"es"})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"No se pudo ejecutar VYRAL Coach.");setAnswer(j.result||"")}catch(e:any){notify("VYRAL Coach",e.message||"No se pudo generar la estrategia.","warn")}finally{setBusy(false)}}return <section className="vcRoot"><div className="vcTop"><div><small>✦ VYRAL INTELLIGENCE · ESCALA</small><h1>VYRAL Coach</h1><p>Tu copiloto de crecimiento. Idea, crea, optimiza y aprende desde un solo lugar.</p></div><div className="vcStatus"><i/> AI ONLINE</div></div>{!enabled?<div className="vcLocked"><span>✦</span><h2>Inteligencia de crecimiento avanzada</h2><p>VYRAL Coach está reservado para el plan Escala.</p><a href="/mi-plan#upgrade">Desbloquear con Escala ↗</a></div>:<><div className="vcInsight"><div><small>COACH DE LA SEMANA</small><strong>Convertí tus datos en próximas acciones.</strong><p>A medida que VYRAL reciba métricas reales, este espacio va a comparar tus publicaciones, detectar patrones y recomendar qué repetir, qué cambiar y qué probar después.</p></div><div className="vcScore"><b>AI</b><span>Growth engine</span></div></div><div className="vcGrid">{tools.map(t=><button key={t.id} onClick={()=>{setActive(t);setPrompt("");setAnswer("")}}><span>{t.icon}</span><div><strong>{t.title}</strong><p>{t.desc}</p></div><b>ABRIR ↗</b></button>)}</div><div className="vcRoadmap"><div><small>PRÓXIMA CAPA</small><strong>Aprendizaje continuo</strong><p>Analytics → patrones → recomendaciones → nuevo contenido → publicación → nuevos datos.</p></div><div><small>MEMORIA DE MARCA</small><strong>Contexto permanente</strong><p>Negocio, audiencia, tono, productos, objetivos y CTA para que cada generación sea realmente tuya.</p></div><div><small>AUTOPILOT</small><strong>De estrategia a ejecución</strong><p>Preparado para conectar las recomendaciones con programación y distribución.</p></div></div></>}{active&&enabled&&<div className="vcBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setActive(null)}}><div className="vcModal"><button className="vcClose" onClick={()=>setActive(null)}>×</button><small>✦ VYRAL COACH</small><h2>{active.title}</h2><p>{active.desc}</p><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={active.placeholder}/><button className="vcRun" disabled={busy||!prompt.trim()} onClick={run}>{busy?"Pensando…":"Generar con VYRAL AI ↗"}</button>{answer&&<div className="vcAnswer"><small>RESULTADO</small><div>{answer}</div></div>}</div></div>}</section>}
