"use client";
import { useEffect,useRef,useState } from "react";import { createPortal } from "react-dom";import "./vyral-ai.css";
type AIResult={caption:string;hashtags:string[];viralScore:number;hook:string;cta:string;strengths:string[];improvements:string[];platformTips?:Record<string,string>};
async function frame(file:File){return new Promise<string>((resolve,reject)=>{const video=document.createElement("video"),url=URL.createObjectURL(file);video.muted=true;video.playsInline=true;video.preload="auto";video.onloadedmetadata=()=>video.currentTime=Math.min(Math.max(video.duration*.18,.1),2);video.onseeked=()=>{try{const c=document.createElement("canvas"),max=720,scale=Math.min(1,max/video.videoWidth);c.width=Math.max(1,Math.round(video.videoWidth*scale));c.height=Math.max(1,Math.round(video.videoHeight*scale));c.getContext("2d")?.drawImage(video,0,0,c.width,c.height);const out=c.toDataURL("image/jpeg",.72);URL.revokeObjectURL(url);resolve(out)}catch(e){URL.revokeObjectURL(url);reject(e)}};video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("No pude leer el video."))};video.src=url;video.load()})}

async function transcript(file:File){
  try{
    window.dispatchEvent(new CustomEvent("vyral:video-processing",{detail:{stage:"uploading",text:"1/4 · Subiendo video de forma segura…"}}));
    const prep=await fetch("/api/ai/automation-voice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"assembly-prepare",fileName:file.name,fileSize:file.size,mimeType:file.type})}),pj=await prep.json().catch(()=>({}));
    if(!prep.ok||!pj.signedUrl)throw Error(pj.error||`No se pudo preparar la carga (HTTP ${prep.status}).`);
    const up=await fetch(pj.signedUrl,{method:"PUT",headers:{"Content-Type":file.type||"application/octet-stream"},body:file});
    if(!up.ok)throw Error(`La carga directa del video falló (HTTP ${up.status}).`);
    window.dispatchEvent(new CustomEvent("vyral:video-processing",{detail:{stage:"transcribing",text:"2/4 · VYRAL está extrayendo y entendiendo la voz…"}}));
    const r=await fetch("/api/ai/automation-voice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"openai-transcribe-stored",path:pj.path})}),j=await r.json().catch(()=>({}));
    if(!r.ok){const d=j.diagnostic;const suffix=d?` · build=${d.build} · key=${d.assemblyKeyPresent?"SI":"NO"} · env=${d.vercelEnv} · sha=${String(d.gitSha||"").slice(0,8)}`:"";throw Error((j.stage?j.stage+" · ":"")+(j.error||`HTTP ${r.status}`)+suffix)}
    const t=String(j.transcript||"").trim();if(!t)throw Error("VYRAL no detectó voz en este video.");
    window.dispatchEvent(new CustomEvent("vyral:video-processing",{detail:{stage:"transcript-ready",text:"3/4 · Transcripción completada ✓"}}));
    return t;
  }catch(e:any){console.error("[VYRAL Transcription]",e);window.dispatchEvent(new CustomEvent("vyral:video-processing",{detail:{stage:"error",text:"Error de transcripción · "+(e?.message||"sin detalle")}}));return ""}
}
function pushTranscript(file:File,spoken:string){if(!spoken)return;sessionStorage.setItem("vyral-video-transcript",JSON.stringify({name:file.name,size:file.size,transcript:spoken}));window.dispatchEvent(new CustomEvent("vyral:video-transcript",{detail:{filename:file.name,transcript:spoken}}));window.dispatchEvent(new CustomEvent("vyral:video-processing",{detail:{stage:"transcript-ready",text:"3/4 · Transcripción completada ✓"}}))}
async function understand(spoken:string){if(!spoken)return"";const fd=new FormData();fd.append("mode","understand-video");fd.append("transcript",spoken);const r=await fetch("/api/ai/automation-voice",{method:"POST",body:fd}),j=await r.json().catch(()=>({}));return r.ok?String(j.context||"").trim():""}
function pushContext(file:File,context:string){if(!context)return;sessionStorage.setItem("vyral-video-context",JSON.stringify({name:file.name,size:file.size,context}));window.dispatchEvent(new CustomEvent("vyral:video-context",{detail:{filename:file.name,context}}))}
function notice(title:string,text:string,tone:"good"|"info"|"warn"="info",open=true){window.dispatchEvent(new CustomEvent("vyral:notify",{detail:{title,text,tone,open}}))}
export default function VyralAI(){const[mount,setMount]=useState<HTMLElement|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[videoReady,setVideoReady]=useState(false),[result,setResult]=useState<AIResult|null>(null),seen=useRef("");useEffect(()=>{const process=(f:File)=>{const key=`${f.name}:${f.size}`;if(seen.current===key)return;seen.current=key;setVideoReady(false);transcript(f).then(async t=>{if(t){pushTranscript(f,t);window.dispatchEvent(new CustomEvent("vyral:video-processing",{detail:{stage:"understanding",text:"Entendiendo intención del video…"}}));const context=await understand(t);if(context)pushContext(f,context);window.dispatchEvent(new CustomEvent("vyral:video-processing",{detail:{stage:"ready",text:"4/4 · Video + voz + contexto listos ✓"}}));setVideoReady(true);window.dispatchEvent(new CustomEvent("vyral:video-ready",{detail:{filename:f.name,size:f.size}}));notice("VYRAL entendió el video",context||"La voz fue transcripta y ya está disponible para VYRAL AI.","good",false)}else{setVideoReady(false);notice("Audio no disponible","VYRAL no recibió una transcripción utilizable de este video.","warn",false)}})};const onSelected=(ev:Event)=>{const f=(ev as CustomEvent).detail?.file;if(f instanceof File)process(f)};window.addEventListener("vyral:video-selected",onSelected);const sync=()=>{const area=document.querySelector<HTMLElement>(".vdTextarea"),card=area?.closest<HTMLElement>(".vdCard")||null;setMount(old=>old===card?old:card);const f=document.querySelector<HTMLInputElement>('.vdUpload input[type="file"]')?.files?.[0];if(f)process(f)};sync();const t=setInterval(sync,700);return()=>{clearInterval(t);window.removeEventListener("vyral:video-selected",onSelected)}},[]);
async function analyze(){const input=document.querySelector<HTMLInputElement>('.vdUpload input[type="file"]'),file=input?.files?.[0],caption=(document.querySelector<HTMLTextAreaElement>(".vdTextarea")?.value||"").trim();if(!file&&!caption){notice("VYRAL AI necesita contenido","Subí un video o escribí una descripción para analizar.","warn");return}setBusy(true);setResult(null);notice("VYRAL AI","Primero estoy escuchando el audio del video; después analizo imagen + voz…","info");try{let image="",spoken="";if(file){const cached=JSON.parse(sessionStorage.getItem("vyral-video-transcript")||"null");spoken=cached?.name===file.name&&cached?.size===file.size?String(cached.transcript||""):await transcript(file);if(!spoken)throw new Error("No pude extraer la voz de este video. El análisis se detuvo para no darte un resultado basado sólo en imágenes.");image=await frame(file).catch(()=>"");pushTranscript(file,spoken)}const r=await fetch("/api/ai/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({caption,image,transcript:spoken,language:localStorage.getItem("vyral-lang")||"es"})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`VYRAL AI respondió con HTTP ${r.status}.`);if(!j.result)throw new Error("VYRAL AI no devolvió un análisis.");setResult(j.result);setOpen(true);notice("Análisis terminado",`${spoken?"Voz + imagen analizadas. ":""}Viral Score: ${j.result.viralScore??"—"}/100.`,"good",false)}catch(e:any){notice("No se pudo analizar",e.message||"VYRAL AI encontró un error inesperado.","warn")}finally{setBusy(false)}}
function apply(){if(!result)return;const area=document.querySelector<HTMLTextAreaElement>(".vdTextarea");if(area){const text=`${result.caption}${result.hashtags?.length?"\n\n"+result.hashtags.map(x=>`#${String(x).replace(/^#/,"")}`).join(" "):""}`.slice(0,2200),setter=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,"value")?.set;setter?.call(area,text);area.dispatchEvent(new Event("input",{bubbles:true}));area.dispatchEvent(new Event("change",{bubbles:true}))}notice("VYRAL AI aplicado","La descripción y los hashtags fueron actualizados.","good");setOpen(false)}
if(!mount)return null;return createPortal(<><div className="vaiBar"><div><small>✦ VYRAL AI</small><strong>Potenciá este contenido antes de publicarlo</strong><span>Analiza imagen + lo que decís en el video, mejora caption, hooks, CTA y hashtags.</span></div><button type="button" onClick={()=>{if(!videoReady){const input=document.querySelector<HTMLInputElement>('.vdUpload input[type="file"]');input?.scrollIntoView({behavior:"smooth",block:"center"});window.setTimeout(()=>input?.click(),450);return}analyze()}} disabled={busy} title={!videoReady?"Disponible cuando VYRAL termine de procesar el video":undefined}>{busy?"Escuchando y analizando…":!videoReady?"Cargar video":"✦ Mejorar con IA"}</button></div>{open&&result&&<div className="vaiBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="vaiModal"><button className="vaiClose" onClick={()=>setOpen(false)}>×</button><div className="vaiTitle"><div><small>VYRAL INTELLIGENCE</small><h2>Análisis de contenido</h2></div><div className="vaiScore"><b>{result.viralScore}</b><span>/100</span></div></div><div className="vaiHero"><small>HOOK RECOMENDADO</small><strong>{result.hook}</strong><p>{result.caption}</p></div><div className="vaiCols"><div><small>LO QUE FUNCIONA</small>{result.strengths?.map((x,i)=><p key={i}>✓ {x}</p>)}</div><div><small>PARA MEJORAR</small>{result.improvements?.map((x,i)=><p key={i}>↗ {x}</p>)}</div></div><div className="vaiTips"><div><b>TikTok</b><span>{result.platformTips?.tiktok}</span></div><div><b>Instagram</b><span>{result.platformTips?.instagram}</span></div><div><b>Facebook</b><span>{result.platformTips?.facebook}</span></div></div><div className="vaiFooter"><span>CTA: {result.cta}</span><button onClick={apply}>Aplicar a la publicación ↗</button></div></div></div>}</>,mount)}