import { NextResponse } from "next/server";
import { getCustomerSession } from "../../../../lib/auth";
import { recordAiUsage } from "../../../../lib/ai-usage";
export const maxDuration=60;
function text(data:any){if(typeof data?.output_text==="string")return data.output_text;for(const i of data?.output||[])for(const c of i?.content||[])if(c?.type==="output_text"&&c?.text)return c.text;return ""}
function json(s:string){const a=s.indexOf("{"),b=s.lastIndexOf("}");if(a<0||b<a)throw new Error("invalid_response");return JSON.parse(s.slice(a,b+1))}
const unavailable=(status=503)=>NextResponse.json({error:"VYRAL Voice Studio no está disponible en este momento.",code:"VYRAL_VOICE_UNAVAILABLE"},{status});
export async function POST(req:Request){const session=await getCustomerSession();if(!session)return NextResponse.json({error:"No autorizado"},{status:401});const key=process.env.OPENAI_API_KEY;if(!key)return unavailable();
 try{const form=await req.formData();const mode=String(form.get("mode")||"transcribe");
  if(mode==="transcribe"||mode==="transcribe-video"){const file=form.get(mode==="transcribe-video"?"video":"audio");if(!(file instanceof File))return NextResponse.json({error:mode==="transcribe-video"?"Falta el video":"Falta el audio"},{status:400});const fd=new FormData();fd.append("file",file,file.name||"vyral-media.webm");fd.append("model","gpt-4o-mini-transcribe");const r=await fetch("https://api.openai.com/v1/audio/transcriptions",{method:"POST",headers:{Authorization:`Bearer ${key}`},body:fd});const d=await r.json().catch(()=>({}));if(!r.ok){console.error("[VYRAL Voice] transcription",d?.error);return NextResponse.json({error:mode==="transcribe-video"?"No pudimos transcribir el audio de este video. Podés editar el contexto manualmente.":"No pudimos transcribir el audio."},{status:502})};return NextResponse.json({ok:true,transcript:String(d.text||"").trim()})}
  const automation=JSON.parse(String(form.get("automation")||"{}"));const model="gpt-5.6-luna";const prompt=`Sos VYRAL Voice Planner. Creá una biblioteca conversacional de audios humanos ESPECÍFICOS para ESTA publicación. CONTEXTO COMPLETO DEL VIDEO=${automation.contentLabel||"Sin contexto"}; objetivo=${automation.conversationGoal||"lead"}; CTA=${automation.ctaText||""}; WhatsApp=${automation.whatsappTarget||""}; tono=${automation.aiTone||"natural"}; país=${automation.aiCountry||"neutral"}; edad/estilo=${automation.aiAudienceAge||"general"}; reglas=${automation.aiInstructions||""}; recurso=${automation.resourceName||""}. El contexto puede contener la transcripción literal del audio del video: respetá ofertas, palabras gatillo, promesas y CTA que aparezcan allí sin inventar nada. Proponé entre 8 y 12 audios cortos, naturales y distintos para cubrir una conversación real: bienvenida, pedido de precio, pedido de más información, interés leve, interés fuerte, duda/objeción, pedido de WhatsApp, pedido del recurso/promesa del video, confirmación, seguimiento y cierre cuando correspondan. Cada recomendación debe explicar claramente CUÁNDO usarla para que el agente pueda seleccionarla semánticamente. No hagas variantes redundantes. Adaptá vocabulario al país y edad sin caricaturizar. Devolvé SOLO JSON {"recommendations":[{"title":"","purpose":"","script":"","when":""}]}.`;
  const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:prompt,max_output_tokens:2400})});const d=await r.json().catch(()=>({}));if(!r.ok)return unavailable(502);await recordAiUsage(session.userId,"automation-voice-planner",model,d.usage||{});return NextResponse.json({ok:true,...json(text(d))});
 }catch(e:any){console.error("[VYRAL Voice] failure",e?.message||e);return unavailable(500)}}