import { NextResponse } from "next/server";
import { getCustomerSession } from "../../../../lib/auth";
import { recordAiUsage } from "../../../../lib/ai-usage";
export const maxDuration=60;
function text(data:any){if(typeof data?.output_text==="string")return data.output_text;for(const i of data?.output||[])for(const c of i?.content||[])if(c?.type==="output_text"&&c?.text)return c.text;return ""}
function json(s:string){const a=s.indexOf("{"),b=s.lastIndexOf("}");if(a<0||b<a)throw new Error("invalid_response");return JSON.parse(s.slice(a,b+1))}
const unavailable=(status=503)=>NextResponse.json({error:"VYRAL Voice Studio no está disponible en este momento.",code:"VYRAL_VOICE_UNAVAILABLE"},{status});
export async function POST(req:Request){const session=await getCustomerSession();if(!session)return NextResponse.json({error:"No autorizado"},{status:401});const key=process.env.OPENAI_API_KEY;if(!key){console.error("[VYRAL Voice][admin] OPENAI_API_KEY missing");return unavailable()}
 try{const form=await req.formData();const mode=String(form.get("mode")||"transcribe");
  if(mode==="transcribe"){const file=form.get("audio");if(!(file instanceof File))return NextResponse.json({error:"Falta el audio"},{status:400});const fd=new FormData();fd.append("file",file,file.name||"vyral-audio.webm");fd.append("model","gpt-4o-mini-transcribe");const r=await fetch("https://api.openai.com/v1/audio/transcriptions",{method:"POST",headers:{Authorization:`Bearer ${key}`},body:fd});const d=await r.json().catch(()=>({}));if(!r.ok){console.error("[VYRAL Voice][admin] transcription",d?.error);return unavailable(502)};return NextResponse.json({ok:true,transcript:String(d.text||"").trim()})}
  const automation=JSON.parse(String(form.get("automation")||"{}"));const model="gpt-5.6-luna";const prompt=`Sos VYRAL Voice Planner. Diseñá una biblioteca pequeña de audios humanos para una automatización comercial. Objetivo=${automation.conversationGoal||"lead"}; CTA=${automation.ctaText||""}; WhatsApp=${automation.whatsappTarget||""}; tono=${automation.aiTone||""}; reglas=${automation.aiInstructions||""}; recurso=${automation.resourceName||""}. Recomendá entre 3 y 6 audios realmente útiles, sin inventar precios ni datos. Cada audio debe tener un propósito distinto y un guion corto que el dueño pueda grabar naturalmente. Devolvé SOLO JSON {"recommendations":[{"title":"","purpose":"","script":"","when":""}]}.`;
  const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:prompt,max_output_tokens:1200})});const d=await r.json().catch(()=>({}));if(!r.ok){console.error("[VYRAL Voice][admin] recommendations",d?.error);return unavailable(502)};await recordAiUsage(session.userId,"automation-voice-planner",model,d.usage||{});return NextResponse.json({ok:true,...json(text(d))});
 }catch(e:any){console.error("[VYRAL Voice][admin] failure",e?.message||e);return unavailable(500)}}