import {NextResponse} from "next/server";
import {getCustomerSession} from "../../../../../lib/auth";
import {supabaseAdmin} from "../../../../../lib/supabase-admin";
export const runtime="nodejs";export const maxDuration=300;
const OPENAI="https://api.openai.com/v1";
function extractJson(s:string){const a=s.indexOf("{");const b=s.lastIndexOf("}");if(a<0||b<a)throw new Error("La IA no devolvió un ecosistema válido.");return JSON.parse(s.slice(a,b+1))}
const SYSTEM=`Sos el VYRAL OFFER ECOSYSTEM ARCHITECT. A partir del ebook principal ya definido, diseñá un ecosistema comercial coherente compuesto por 3 BONOS/REGALOS y 4 UPSELLS, sin redundancias ni canibalización.

PRINCIPIO CENTRAL: el ebook principal resuelve el problema/promesa central. Los BONOS aumentan valor percibido y facilitan implementación, uso, velocidad, claridad, organización o seguimiento, pero NO deben resolver el siguiente gran problema por el cual tendría sentido pagar aparte. Los UPSELLS permanecen en el mismo universo de deseo/dolor, pero atacan ramificaciones diferentes, momentos posteriores, nuevas inseguridades, prevención, mantenimiento, aceleración, profundidad o el siguiente paso lógico. Nunca vendas inmediatamente "más de lo mismo" con otro nombre.

FILTRO OBLIGATORIO DE UPSELL: preguntate internamente “¿el comprador podría decir: esto ya me lo deberían haber dado en el producto que acabo de pagar?”. Si sí, descartalo y creá otro. Cada upsell debe tener una razón clara para comprarse DESPUÉS del principal, sin depender de presión engañosa, escasez falsa o miedo fabricado. La urgencia debe surgir de relevancia, continuidad y deseo de completar el resultado.

FILTRO CRUZADO: ningún bono puede canibalizar un upsell. Ningún upsell puede duplicar otro upsell. Todos comparten universo, avatar y transformación macro, pero cada uno ocupa un trabajo distinto.

PLANTILLAS: UNO de los 3 bonos debe ser SIEMPRE un KIT DE PLANTILLAS VISUALES DESCARGABLES Y RELLENABLES MANUALMENTE. Debe ser específico al nicho, útil de verdad y contener entre 5 y 12 plantillas concretas (por ejemplo planner, tracker, checklist, worksheet, canvas, registro, calendario, ficha, matriz, guion, según el tema). Diseñalas para impresión o uso digital manual. No las conviertas en otro ebook teórico.

Los otros dos bonos deben variar inteligentemente según el producto: guía rápida, checklist, cheat sheet, plan de acción, recetario complementario, biblioteca de ejemplos, errores frecuentes, recursos, mini manual, scripts, etc. No fuerces formatos que no correspondan.

Para cada elemento generá además un BRIEF COMPLETO listo para enviarse al motor VYRAL Ebook IA como un producto independiente: título, subtítulo, nicho, avatar, problema específico, transformación, objetivo, contenido/subtemas, tono, nivel, estilo, dirección visual, paleta, tipografía, recursos visuales, portada, progresión, posicionamiento y restricciones. Para el kit de plantillas, el brief debe exigir páginas visuales con campos, espacios, tablas o casilleros realmente rellenables a mano una vez impresos/descargados.

Respondé SOLO JSON válido.`;
export async function POST(req:Request){const session=await getCustomerSession();if(!session)return NextResponse.json({error:"Iniciá sesión."},{status:401});const db=supabaseAdmin();const {data}=await db.auth.admin.getUserById(session.userId);const plan=String(data.user?.user_metadata?.plan||session.plan||"");if(plan!=="escala"&&plan!=="ai")return NextResponse.json({error:"Ecosistema de Oferta requiere Escala o VYRAL AI."},{status:403});const key=process.env.VYRAL_CREATOR_PRODUCTION;if(!key)return NextResponse.json({error:"Falta configurar la API de OpenAI."},{status:503});try{const b=await req.json();const brief=String(b.brief||"").trim();const title=String(b.title||"").trim();const promise=String(b.promise||"").trim();const transformation=String(b.transformation||"").trim();if(!brief||!title)return NextResponse.json({error:"Primero creá la estructura del ebook principal."},{status:400});const schema=`Devolvé exactamente: {"strategy":"explicación breve de la escalera de valor","bonuses":[{"id":"bonus-1","kind":"template-kit|bonus","title":"...","hook":"...","role":"...","whyComplementary":"...","whyNotUpsell":"...","recommendedPages":8,"templateNames":["..."],"brief":"BRIEF COMPLETO listo para Ebook IA"}],"upsells":[{"id":"upsell-1","title":"...","hook":"...","branch":"ramificación distinta del dolor/deseo","nextStep":"...","whyBuyNow":"urgencia natural/relevancia posterior","whyNotRedundant":"...","recommendedPages":15,"brief":"BRIEF COMPLETO listo para Ebook IA"}]}. EXACTAMENTE 3 bonuses, de los cuales EXACTAMENTE UNO kind=template-kit, y EXACTAMENTE 4 upsells. recommendedPages entre 5 y 45.`;const model=process.env.VYRAL_EBOOK_TEXT_MODEL||process.env.VYRAL_TEXT_MODEL||"gpt-5.6-sol";const r=await fetch(`${OPENAI}/responses`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:[{role:"system",content:[{type:"input_text",text:SYSTEM}]},{role:"user",content:[{type:"input_text",text:`EBOOK PRINCIPAL: ${title}\nPROMESA: ${promise}\nTRANSFORMACIÓN: ${transformation}\nBRIEF ORIGINAL:\n${brief}\n\n${schema}`}]}],max_output_tokens:18000})});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||"No se pudo crear el ecosistema.");const text=(j.output||[]).flatMap((x:any)=>x.content||[]).filter((x:any)=>x.type==="output_text").map((x:any)=>x.text).join("");const out=extractJson(text);if(out?.bonuses?.length!==3||out?.upsells?.length!==4)throw new Error("El ecosistema no devolvió 3 bonos y 4 upsells.");return NextResponse.json(out)}catch(e:any){return NextResponse.json({error:e.message||"No se pudo crear el ecosistema de oferta."},{status:500})}}
