import Link from "next/link";
import "../legal.css";
export const metadata={title:"Política de Privacidad | VYRAL",description:"Política de Privacidad de VYRAL."};
export default function PrivacyPage(){return <main className="vyralLegalPage"><div className="vyralLegalGlow"/><div className="vyralLegalWrap"><nav className="vyralLegalNav"><Link href="/" className="vyralLegalBrand">V<span>Y</span>RAL</Link><Link href="/login" className="vyralLegalExit">← Volver</Link></nav><header className="vyralLegalHero"><small>PRIVACIDAD / VYRAL</small><h1>Política de<br/><em>Privacidad.</em></h1><p>Cómo VYRAL procesa y protege la información necesaria para conectar y automatizar tus cuentas sociales.</p><div className="vyralLegalMeta"><span>Última actualización</span><strong>20 de septiembre de 2026</strong></div></header><section className="vyralLegalContent">
<article><span>01</span><div><h2>Información que procesamos</h2><p>Cuando creás una cuenta o conectás Instagram, Facebook u otras plataformas compatibles, VYRAL puede procesar identificadores de usuario y cuenta, nombre de perfil, tipo de cuenta, permisos concedidos, tokens de acceso, contenido multimedia, publicaciones, comentarios, mensajes y metadatos necesarios para ejecutar las funciones que solicitás.</p></div></article>
<article><span>02</span><div><h2>Uso de datos de Meta</h2><p>Los datos obtenidos mediante las APIs de Meta se utilizan únicamente para prestar las funciones autorizadas por el usuario: conectar cuentas profesionales, administrar y publicar contenido, recibir y gestionar comentarios, responder comentarios, gestionar mensajes y automatizaciones configuradas por el usuario, y mostrar información necesaria dentro de VYRAL.</p></div></article>
<article><span>03</span><div><h2>Autorización y credenciales</h2><p>VYRAL utiliza los mecanismos oficiales de autorización de las plataformas compatibles. No solicitamos ni almacenamos tu contraseña de Instagram o Facebook. Conservamos los tokens de acceso necesarios para ejecutar las funciones autorizadas y podés revocar el acceso desde la plataforma correspondiente.</p></div></article>
<article><span>04</span><div><h2>Automatizaciones</h2><p>Si activás automatizaciones de comentarios o mensajes, VYRAL procesa los eventos recibidos de las plataformas conectadas y el contenido necesario para aplicar las reglas que configuraste. Las respuestas y mensajes solo se ejecutan de acuerdo con las funciones habilitadas por vos.</p></div></article>
<article><span>05</span><div><h2>Proveedores y transferencias</h2><p>Podemos utilizar proveedores de infraestructura, base de datos, autenticación, almacenamiento, correo, pagos y APIs sociales para operar el servicio. Solo se comparte la información necesaria para prestar esas funciones. VYRAL no vende datos personales.</p></div></article>
<article><span>06</span><div><h2>Conservación y seguridad</h2><p>Conservamos los datos durante el tiempo necesario para prestar el servicio, mantener la seguridad y cumplir obligaciones aplicables. Aplicamos medidas técnicas y organizativas razonables para proteger credenciales, tokens y datos almacenados.</p></div></article>
<article><span>07</span><div><h2>Control y eliminación</h2><p>Podés desconectar cuentas y revocar permisos en cualquier momento. También podés solicitar la eliminación de tus datos siguiendo nuestras <Link href="/data-deletion">instrucciones de eliminación de datos</Link>. Procesaremos las solicitudes verificables y eliminaremos los datos que no debamos conservar por una obligación legal.</p></div></article>
<article><span>08</span><div><h2>Servicios de terceros</h2><p>El uso de Instagram, Facebook y otros servicios conectados también está sujeto a sus propias políticas y términos. Los cambios en sus APIs, permisos o políticas pueden modificar las funciones disponibles en VYRAL.</p></div></article>
<article><span>09</span><div><h2>Cambios</h2><p>Podemos actualizar esta política cuando cambien VYRAL, sus integraciones o los requisitos aplicables. La fecha indicada en esta página identifica la versión vigente.</p></div></article>
<article><span>10</span><div><h2>Contacto</h2><p>Para consultas de privacidad o solicitudes relacionadas con tus datos, escribí a <a href="mailto:nextgentechecommerce@gmail.com">nextgentechecommerce@gmail.com</a>.</p></div></article>
</section><footer className="vyralLegalFooter"><div className="vyralLegalPowered"><span>VYRAL</span><strong>Privacidad y datos</strong></div><div><Link href="/terms">Términos</Link><Link href="/data-deletion">Eliminar datos</Link></div></footer></div></main>}