"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import NetworkFlowEnhancer from "./NetworkFlowEnhancer";
import "./landing-growth.css";
import "./landing-ultra.css";
import "./landing-simulator-v2.css";

const rows = [
  ["Publicación multicuentas", "Incluido", "Varias herramientas / procesos"],
  ["Analytics unificado", "Incluido", "Suele estar separado"],
  ["IA aplicada al contenido", "Incluido según plan", "Suele requerir otra herramienta"],
  ["Automatizaciones comentario → DM", "Integradas", "Normalmente se contrata aparte"],
  ["Soporte + operación + creator program", "Un solo sistema", "Flujos fragmentados"],
  ["Precio de entrada", "Desde US$ 4,99 / mes", "Depende del stack que armes"]
];
const tips = {
  ai:{title:"Gasto en inteligencia artificial",text:"Ingresá lo que pagás por herramientas de IA que usás para captions, ideas, copies, respuestas o asistencia de contenido."},
  tools:{title:"Apps y software",text:"Incluí publicación, analytics, automatizaciones, social media tools y otras plataformas que VYRAL podría centralizar."},
  videos:{title:"Videos por mes",text:"VYRAL usa este dato para recomendar automáticamente el plan según su capacidad mensual: Inicio hasta 50, Crecimiento hasta 200 y Escala hasta 500 videos."},
  accounts:{title:"Cuentas por publicación",text:"Cuantas más cuentas reciben el mismo video, más veces tenés que repetir manualmente la misma carga. VYRAL centraliza esas cargas en un solo flujo."},
  hourValue:{title:"Costo por hora del equipo",text:"Puede ser tu hora o la de un community manager, editor o miembro del equipo. La usamos para poner valor al tiempo que hoy se pierde repitiendo publicaciones."}
} as const;
type TipKey=keyof typeof tips;
function InfoButton({id,open,onToggle}:{id:TipKey;open:TipKey|null;onToggle:(id:TipKey)=>void}){const active=open===id;return <span className="vyralInfoWrap"><button type="button" className={`vyralInfoButton ${active?"active":""}`} onClick={()=>onToggle(id)} aria-expanded={active}>!</button>{active&&<span className="vyralInfoPopover"><b>{tips[id].title}</b><p>{tips[id].text}</p></span>}</span>}

export default function LandingGrowthExperience(){
 const[aiCost,setAiCost]=useState(20),[toolsCost,setToolsCost]=useState(45),[videos,setVideos]=useState(50),[accounts,setAccounts]=useState(3),[hourValue,setHourValue]=useState(8);const[openTip,setOpenTip]=useState<TipKey|null>(null);
 useEffect(()=>{const targets=Array.from(document.querySelectorAll<HTMLElement>(".vyralSection,.loginExperience,.vyralTicker,.vyralImpactSection,.vyralProofSection,.vyralComparisonSection"));targets.forEach((el,i)=>{el.classList.add("vyralReveal");el.dataset.reveal=String(i%4)});const io=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle("vyralIn",entry.isIntersecting)),{threshold:.12,rootMargin:"0px 0px -6% 0px"});targets.forEach(el=>io.observe(el));return()=>io.disconnect()},[]);
 const plan=useMemo(()=>videos<=50?{id:"inicio",name:"Inicio",price:4.99,limit:50}:videos<=200?{id:"pro",name:"Crecimiento",price:9.99,limit:200}:{id:"escala",name:"Escala",price:19.99,limit:500},[videos]);
 const secondsPerManualUpload=45,manualUploads=videos*accounts,vyralUploads=videos,duplicateUploadsAvoided=Math.max(0,manualUploads-vyralUploads),manualHours=manualUploads*secondsPerManualUpload/3600,vyralHours=vyralUploads*secondsPerManualUpload/3600,savedHours=duplicateUploadsAvoided*secondsPerManualUpload/3600,laborValue=savedHours*hourValue,replaceableSoftware=aiCost+toolsCost,grossPotential=replaceableSoftware+laborValue,monthlySavings=Math.max(0,grossPotential-plan.price),yearlySavings=monthlySavings*12;
 return <><NetworkFlowEnhancer/>
 <section className="vyralImpactSection" aria-label="Impacto VYRAL"><div className="vyralImpactGlow one"/><div className="vyralImpactGlow two"/><div className="vyralImpactCopy"><div className="vyralSectionIndex">IMPACTO / OPERACIÓN</div><div className="vyralKicker">ECOMMERCE · CREADORES · AGENCIAS</div><h2>Menos cargas.<br/><em>Más tiempo para crecer.</em></h2><p>El ahorro de tiempo se calcula sobre una tarea concreta: dejar de subir la misma pieza una y otra vez en cada cuenta.</p><div className="vyralAudienceChips"><span>◌ Ecommerce</span><span>✦ Creadores</span><span>⌁ Equipos de contenido</span><span>↗ Agencias</span></div><div className="vyralAssumptionCard"><span>CÁLCULO SIMPLE Y TRANSPARENTE</span><b>45 segundos por carga manual</b><p>Usamos un promedio conservador de 30–60 segundos por publicación. <strong>No contamos edición</strong>, porque VYRAL no reemplaza ese trabajo.</p></div></div>
 <div className="vyralSavingsCard"><div className="vyralSavingsTop"><div><span>SIMULADOR DE DISTRIBUCIÓN</span><small>Ajustá tus datos y mirá cómo cambia el escenario.</small></div><i>DINÁMICO</i></div><div className="vyralSavingsInputs">
 {([["Gasto mensual en IA","ai",aiCost,setAiCost,0,300,`US$ ${aiCost}/mes`],["Gasto mensual en apps / software","tools",toolsCost,setToolsCost,0,500,`US$ ${toolsCost}/mes`],["Videos que publicás por mes","videos",videos,setVideos,1,500,`${videos} videos`],["Cuentas promedio por video","accounts",accounts,setAccounts,1,30,`${accounts} cuentas`],["Costo por hora de tu equipo","hourValue",hourValue,setHourValue,1,100,`US$ ${hourValue}/h`]] as const).map(([label,id,value,setter,min,max,out])=><div key={id} className={`vyralSavingsControl ${id==="videos"||id==="accounts"?"featured":""}`}><div className="vyralSavingsLabel"><span>{label}</span><InfoButton id={id} open={openTip} onToggle={x=>setOpenTip(openTip===x?null:x)}/><b>{out}</b></div><input type="range" min={min} max={max} value={value} onChange={e=>setter(Number(e.target.value))}/></div>)}
 </div><div className="vyralAutoPlan"><div><small>PLAN RECOMENDADO SEGÚN TU VOLUMEN</small><strong>{plan.name}</strong><span>US$ {plan.price.toFixed(2)}/mes · hasta {plan.limit} videos</span></div><div className="vyralAutoPlanBadge">{plan.id==="inicio"?"01":plan.id==="pro"?"02":"03"}</div></div><div className="vyralPublishCompare"><article><small>PUBLICANDO MANUALMENTE</small><strong>{manualUploads}</strong><span>cargas/mes · ≈ {manualHours.toFixed(1)} h</span><p>{videos} videos × {accounts} cuentas</p></article><div className="vyralVs">VS</div><article className="vyralWay"><small>PUBLICANDO CON VYRAL</small><strong>{vyralUploads}</strong><span>cargas/mes · ≈ {vyralHours.toFixed(1)} h</span><p>una carga central por video</p></article></div><div className="vyralCalcStory"><article><small>CARGAS REPETITIVAS EVITADAS</small><strong>{duplicateUploadsAvoided}</strong><span>acciones manuales que desaparecen</span></article><article><small>TIEMPO RECUPERABLE</small><strong>{savedHours.toFixed(1)} h</strong><span>por mes sólo en distribución</span></article><article><small>VALOR DEL TIEMPO RECUPERADO</small><strong>US$ {laborValue.toFixed(0)}</strong><span>{savedHours.toFixed(1)} h × US$ {hourValue}/h</span></article></div><div className="vyralSavingsBreakdown"><span><b>IA + apps que podrías centralizar</b><strong>US$ {replaceableSoftware.toFixed(0)}/mes</strong></span><span><b>Valor del tiempo de distribución recuperado</b><strong>+ US$ {laborValue.toFixed(0)}/mes</strong></span><span><b>Plan {plan.name}</b><strong>− US$ {plan.price.toFixed(2)}/mes</strong></span></div><div className="vyralSavingsResult"><small>AHORRO POTENCIAL ESTIMADO</small><strong>US$ {monthlySavings.toFixed(0)}<span> / MES</span></strong><div className="vyralYearly"><b>US$ {yearlySavings.toFixed(0)}</b><span>POTENCIAL / AÑO</span></div></div><small className="vyralEstimateNote">Estimación basada en tus datos y en 45 segundos por carga manual repetida. No incluye edición ni supone reducción de personal.</small></div></section>
 <section className="vyralProofSection"><div className="vyralProofEyebrow">MÉTRICAS REALES / CUANDO EMPIECE LA OPERACIÓN</div><div className="vyralProofGrid"><div><h3>Prueba social basada en datos, no en números inventados.</h3><p>Este espacio está preparado para mostrar creadores activos, horas recuperadas, publicaciones distribuidas y ahorro acumulado cuando exista telemetría real suficiente.</p></div><div className="vyralProofMetrics"><article><span>CREADORES</span><strong>—</strong><small>usuarios activos verificados</small></article><article><span>HORAS</span><strong>—</strong><small>tiempo recuperado acumulado</small></article><article><span>AHORRO</span><strong>—</strong><small>impacto estimado con datos reales</small></article></div></div></section>
 <section className="vyralComparisonSection"><div className="vyralComparisonHead"><div><div className="vyralSectionIndex">POR QUÉ VYRAL</div><div className="vyralKicker">UN SISTEMA EN VEZ DE UN MOSAICO DE HERRAMIENTAS</div><h2>Compará el flujo.<br/><em>No sólo el precio.</em></h2></div><p>Distribución, medición, IA y automatizaciones nacen conectadas al mismo contenido y a la misma cuenta.</p></div><div className="vyralComparisonTable"><div className="head"><span>CAPACIDAD</span><b>VYRAL</b><i>STACK TRADICIONAL</i></div>{rows.map(([a,b,c])=><div key={a}><span>{a}</span><b>✓ {b}</b><i>{c}</i></div>)}</div><div className="vyralDifferenceRail"><article><span>01</span><b>Distribuí</b><p>Un contenido. Múltiples destinos. Un solo flujo.</p></article><article><span>02</span><b>Convertí</b><p>Comentarios → intención → DM → oportunidad.</p></article><article><span>03</span><b>Entendé</b><p>Analytics de toda la red.</p></article><article><span>04</span><b>Decidí</b><p>La inteligencia de VYRAL convierte datos en próximas acciones.</p></article></div><Link className="vyralCompareCta" href="/registro">Crear mi cuenta <span>↗</span></Link></section></>;
}
