import Link from "next/link";
import "./login-plans.css";
const plans=[
 {id:"inicio",name:"Inicio",price:"4,99",annual:"49,90",accounts:"Hasta 2 cuentas",images:12,crypto:false},
 {id:"pro",name:"Crecimiento",price:"9,99",annual:"99,90",accounts:"Hasta 5 cuentas",images:25,crypto:false},
 {id:"escala",name:"Escala",price:"19,99",annual:"199,90",accounts:"Hasta 30 cuentas",images:50,crypto:true,popular:true},
 {id:"ai",name:"VYRAL AI",price:"99,99",annual:"999,90",accounts:"Hasta 50 cuentas",images:250,crypto:true,ai:true}
];
const cryptos=[["/crypto/bitcoin.svg","BTC"],["/crypto/usdt.svg","USDT"],["/crypto/ethereum.svg","ETH"],["/crypto/solana.svg","SOL"]];
export default function LoginPlans(){return <section className="lpPlans" id="planes"><div className="lpHead"><small>PLANES VYRAL · MENSUAL O ANUAL</small><h2>Elegí cómo querés empezar.</h2><p>Los mismos planes y capacidades de VYRAL. En el plan anual obtenés 2 meses gratis.</p></div><div className="lpGrid">{plans.map(p=><article key={p.id} className={p.popular?"popular":""}>{p.popular&&<span className="lpPopular">MÁS VENDIDO</span>}<small>PLAN VYRAL</small><h3>{p.name}</h3><strong>US$ {p.price}<i>/mes</i></strong><p>{p.accounts}</p><div className="lpAnnual">US$ {p.annual} / año · <b>2 MESES GRATIS</b></div><div className="lpCreator"><small>CREATOR IA</small><b>{p.images}</b><span> imágenes IA / mes</span></div><div className="lpMethods"><span><img src="/payment-card.svg" alt=""/>Tarjeta</span>{p.crypto&&cryptos.map(([src,n])=><span key={n}><img src={src} alt=""/>{n}</span>)}</div>{p.ai?<div className="lpAiHint">Creator IA + automatizaciones + toda la potencia de Escala</div>:null}<Link href={"/registro?plan="+p.id} className="lpCard">Pagar con tarjeta <b>→</b></Link>{p.crypto?<Link href={"/registro?plan="+p.id+"&payment=crypto"} className="lpCrypto">Pagar con criptomonedas <b>→</b></Link>:<div className="lpSoon">Pago cripto disponible desde Escala</div>}<em>Creá tu cuenta → verificá tu email → pagá tu plan</em></article>)}</div><div className="lpSecure">◆ PAGO SEGURO · Una carga consume 1 crédito mensual aunque la distribuyas en varias cuentas.</div></section>}