"use client";
import {useEffect,useState} from "react";
type AvailableVoice={voice_id:string;name:string;category?:string;preview_url?:string;labels?:Record<string,string>};
type VoiceProfile={id:string;name:string;source:"preset"|"cloned";status:string;provider_voice_id?:string|null;preset_voice_id?:string|null};
type VoiceSettings={enabled:boolean;voice_profile_id:string|null;max_ai_audios:number;max_audio_seconds:number;mode:string;voice_probability:number};
type A={id:string;name:string;enabled:boolean;keywords?:string[];triggerMode?:string;publicReply?:string;dmMessage?:string;resourceName?:string;resourceUrl?:string;targetMediaIds?:string[];contentLabel?:string;voiceSettings?:VoiceSettings|null};
export default function AutomationManager(){
 const[items,setItems]=useState<A[]>([]),[profiles,setProfiles]=useState<VoiceProfile[]>([]),[availableVoices,setAvailableVoices]=useState<AvailableVoice[]>([]),[paused,setPaused]=useState(false),[busy,setBusy]=useState(false),[open,setOpen]=useState<string|null>(null),[voiceName,setVoiceName]=useState("Mi voz"),[voiceId,setVoiceId]=useState(""),[voiceSource,setVoiceSource]=useState<"cloned"|"preset">("cloned"),[notice,setNotice]=useState("");
 async function load(){const r=await fetch("/api/automations",{cache:"no-store"}),j=await r.json();setItems(j.automations||[]);setProfiles(j.voiceProfiles||[]);setAvailableVoices(j.availableVoices||[]);setPaused(!!j.paused)}
 useEffect(()=>{load()},[]);
 async function post(body:any){const r=await fetch("/api/automations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j.error||"No se pudo guardar");return j}
 async function global(next:boolean){setBusy(true);await post({action:next?"pause_all":"resume_all"});await load();setBusy(false)}
 async function toggle(a:A){setBusy(true);await post({...a,enabled:!a.enabled});await load();setBusy(false)}
 async function saveProfile(){if(!voiceId.trim())return setNotice("Pegá primero el Voice ID.");setBusy(true);setNotice("");try{await post({action:"save_voice_profile",name:voiceName,source:voiceSource,voiceId:voiceId.trim()});setVoiceId("");setNotice("Voz guardada y lista para asignar.");await load()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 async function saveVoice(a:A,patch:Partial<VoiceSettings>){const cur=a.voiceSettings||{enabled:false,voice_profile_id:profiles[0]?.id||null,max_ai_audios:3,max_audio_seconds:40,mode:"smart",voice_probability:35};const next={...cur,...patch};setBusy(true);setNotice("");try{await post({action:"save_voice_settings",automationId:a.id,enabled:next.enabled,voiceProfileId:next.voice_profile_id,maxAiAudios:next.max_ai_audios,maxAudioSeconds:next.max_audio_seconds,mode:next.mode,voiceProbability:next.voice_probability});await load()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 return <main className="amPage"><header className="amTop"><button onClick={()=>location.href="/"}>← Volver al panel</button><div><small>VYRAL · CONTROL CENTER</small><h1>DMs y automatizaciones</h1><p>Todo lo que VYRAL responde y entrega, en un solo lugar.</p></div></header>
 <section className="amVoiceLab"><div><small>VOZ DEL AGENTE</small><h2>Humanizá las respuestas con audio</h2><p>Podés usar una voz VYRAL o tu voz clonada. Cada automatización admite hasta 3 respuestas dinámicas de audio por conversación; si la voz no está disponible, VYRAL continúa por texto.</p></div><div className="amVoiceForm"><select value={voiceSource} onChange={e=>setVoiceSource(e.target.value as any)}><option value="preset">Voz VYRAL</option><option value="cloned">Mi voz clonada · próximamente</option></select>{voiceSource==="preset"?<><select value={voiceId} onChange={e=>{const id=e.target.value;setVoiceId(id);const v=availableVoices.find(x=>x.voice_id===id);if(v)setVoiceName(v.name)}}><option value="">Seleccioná una voz</option>{availableVoices.map(v=><option key={v.voice_id} value={v.voice_id}>{v.name}{v.labels?.accent?` · ${v.labels.accent}`:""}</option>)}</select>{availableVoices.find(v=>v.voice_id===voiceId)?.preview_url?<button type="button" onClick={()=>new Audio(availableVoices.find(v=>v.voice_id===voiceId)!.preview_url!).play()}>▶ Escuchar</button>:<span className="amVoiceHelp">Las voces se cargan automáticamente desde VYRAL.</span>}<button disabled={busy||!voiceId} onClick={saveProfile}>Usar esta voz</button></>:<><div className="amVoiceComing"><b>Clonación de voz</b><span>La estructura ya está preparada. La activaremos más adelante sin pedir IDs al cliente.</span></div></>}</div>{notice&&<div className="amNotice">{notice}</div>}<div className="amVoicePills">{profiles.map(v=><span key={v.id}>{v.source==="cloned"?"◉":"✦"} {v.name} · {v.status}</span>)}</div></section>
 <section className="amGlobal"><div><span className={paused?"amDot off":"amDot"}/><div><b>{paused?"Automatizaciones pausadas":"Sistema activo"}</b><small>{paused?"Ningún bot responderá hasta que lo reactives.":"Los agentes activos pueden responder comentarios y DMs."}</small></div></div><button disabled={busy} onClick={()=>global(!paused)}>{paused?"▶ Reactivar todo":"Ⅱ Pausar todo"}</button></section>
 <section className="amList"><div className="amListHead"><div><small>AGENTES</small><h2>Qué hace cada automatización</h2></div><span>{items.length} configuradas</span></div>
 {items.map(a=>{const vs=a.voiceSettings||{enabled:false,voice_profile_id:profiles[0]?.id||null,max_ai_audios:3,max_audio_seconds:40,mode:"smart",voice_probability:35};return <article className={"amCard "+(!a.enabled?"disabled":"")} key={a.id}><div className="amCardTop"><div><span className={a.enabled?"amStatus":"amStatus off"}>{a.enabled?"ACTIVA":"PAUSADA"}</span><h3>{a.name}</h3><p>{a.targetMediaIds?.length?("Asignada a "+a.targetMediaIds.length+" publicación(es)"):"⚠ Sin publicación específica · puede actuar en cualquier publicación compatible"}</p></div><div className="amActions"><button onClick={()=>location.href=`/inbox?automation=${encodeURIComponent(a.id)}`}>Personas y chats</button><button onClick={()=>setOpen(open===a.id?null:a.id)}>{open===a.id?"Cerrar":"Ver qué envía"}</button><button className="primary" disabled={busy} onClick={()=>toggle(a)}>{a.enabled?"Pausar":"Activar"}</button></div></div>
 {open===a.id&&<div className="amDetail"><div><small>DISPARADOR</small><b>{a.triggerMode==="ai_intent"?"IA + intención":"Palabras clave"}</b><p>{a.keywords?.length?a.keywords.join(" · "):"Sin palabras configuradas"}</p></div><div><small>RESPUESTA PÚBLICA</small><p>{a.publicReply||"No envía respuesta pública"}</p></div><div><small>DM QUE ENVÍA</small><p>{a.dmMessage||"Sin mensaje privado configurado"}</p></div><div><small>ARCHIVO / GUÍA</small><b>{a.resourceName||"Sin archivo adjunto"}</b><p>{a.resourceUrl?"Recurso cargado y listo para enviar.":"Esta automatización no tiene un recurso cargado."}</p></div>{a.contentLabel&&<div className="wide"><small>CONTEXTO DEL BOT</small><p>{a.contentLabel}</p></div>}
 <div className="wide amVoiceSettings"><div className="amVoiceTitle"><div><small>RESPUESTAS DE AUDIO IA</small><b>{vs.enabled?"Audio inteligente activo":"Respuestas por texto"}</b></div><label className="amSwitch"><input type="checkbox" checked={vs.enabled} disabled={!profiles.length||busy} onChange={e=>saveVoice(a,{enabled:e.target.checked})}/><span/></label></div><div className="amVoiceGrid"><label>Voz<select value={vs.voice_profile_id||""} onChange={e=>saveVoice(a,{voice_profile_id:e.target.value||null})}><option value="">Elegir voz</option>{profiles.map(v=><option key={v.id} value={v.id}>{v.name} · {v.source==="cloned"?"clonada":"VYRAL"}</option>)}</select></label><label>Máximo por chat<select value={vs.max_ai_audios} onChange={e=>saveVoice(a,{max_ai_audios:Number(e.target.value)})}><option value="1">1 audio</option><option value="2">2 audios</option><option value="3">3 audios</option></select></label><label>Frecuencia<select value={vs.voice_probability} onChange={e=>saveVoice(a,{voice_probability:Number(e.target.value)})}><option value="20">Ocasional · 20%</option><option value="35">Natural · 35%</option><option value="50">Frecuente · 50%</option></select></label><label>Duración<select value={vs.max_audio_seconds} onChange={e=>saveVoice(a,{max_audio_seconds:Number(e.target.value)})}><option value="25">Hasta 25 s</option><option value="40">Hasta 40 s</option><option value="60">Hasta 60 s</option></select></label></div><p className="amVoiceHint">{profiles.length?"Los audios de apertura cargados manualmente no consumen este límite.":"Guardá arriba una voz clonada o VYRAL para poder activar esta función."}</p></div></div>}</article>})}
 {!items.length&&<div className="amEmpty">Todavía no hay automatizaciones guardadas.</div>}</section></main>
}