"use client";
import {useEffect,useState} from "react";
type A={id:string;name:string;enabled:boolean;keywords?:string[];triggerMode?:string;publicReply?:string;dmMessage?:string;resourceName?:string;resourceUrl?:string;targetMediaIds?:string[];contentLabel?:string};
export default function AutomationManager(){const[items,setItems]=useState<A[]>([]),[paused,setPaused]=useState(false),[busy,setBusy]=useState(false),[open,setOpen]=useState<string|null>(null);
async function load(){const r=await fetch("/api/automations",{cache:"no-store"}),j=await r.json();setItems(j.automations||[]);setPaused(!!j.paused)}
useEffect(()=>{load()},[]);
async function global(next:boolean){setBusy(true);await fetch("/api/automations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:next?"pause_all":"resume_all"})});await load();setBusy(false)}
async function toggle(a:A){setBusy(true);await fetch("/api/automations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...a,enabled:!a.enabled})});await load();setBusy(false)}
return <main className="amPage"><header className="amTop"><button onClick={()=>location.href="/"}>← Volver al panel</button><div><small>VYRAL · CONTROL CENTER</small><h1>DMs y automatizaciones</h1><p>Todo lo que VYRAL responde y entrega, en un solo lugar.</p></div></header>
<section className="amGlobal"><div><span className={paused?"amDot off":"amDot"}/><div><b>{paused?"Automatizaciones pausadas":"Sistema activo"}</b><small>{paused?"Ningún bot responderá hasta que lo reactives.":"Los agentes activos pueden responder comentarios y DMs."}</small></div></div><button disabled={busy} onClick={()=>global(!paused)}>{paused?"▶ Reactivar todo":"Ⅱ Pausar todo"}</button></section>
<section className="amList"><div className="amListHead"><div><small>AGENTES</small><h2>Qué hace cada automatización</h2></div><span>{items.length} configuradas</span></div>
{items.map(a=><article className={"amCard "+(!a.enabled?"disabled":"")} key={a.id}><div className="amCardTop"><div><span className={a.enabled?"amStatus":"amStatus off"}>{a.enabled?"ACTIVA":"PAUSADA"}</span><h3>{a.name}</h3><p>{a.targetMediaIds?.length?("Asignada a "+a.targetMediaIds.length+" publicación(es)"):"⚠ Sin publicación específica · puede actuar en cualquier publicación compatible"}</p></div><div className="amActions"><button onClick={()=>setOpen(open===a.id?null:a.id)}>{open===a.id?"Cerrar":"Ver qué envía"}</button><button className="primary" disabled={busy} onClick={()=>toggle(a)}>{a.enabled?"Pausar":"Activar"}</button></div></div>
{open===a.id&&<div className="amDetail"><div><small>DISPARADOR</small><b>{a.triggerMode==="ai_intent"?"IA + intención":"Palabras clave"}</b><p>{a.keywords?.length?a.keywords.join(" · "):"Sin palabras configuradas"}</p></div><div><small>RESPUESTA PÚBLICA</small><p>{a.publicReply||"No envía respuesta pública"}</p></div><div><small>DM QUE ENVÍA</small><p>{a.dmMessage||"Sin mensaje privado configurado"}</p></div><div><small>ARCHIVO / GUÍA</small><b>{a.resourceName||"Sin archivo adjunto"}</b><p>{a.resourceUrl?"Recurso cargado y listo para enviar.":"Esta automatización no tiene un recurso cargado."}</p></div>{a.contentLabel&&<div className="wide"><small>CONTEXTO DEL BOT</small><p>{a.contentLabel}</p></div>}</div>}</article>)}
{!items.length&&<div className="amEmpty">Todavía no hay automatizaciones guardadas.</div>}</section></main>}