import {NextResponse} from "next/server";
import {getCustomerSession} from "../../../../../lib/auth";
import {supabaseAdmin} from "../../../../../lib/supabase-admin";
export const runtime="nodejs";export const maxDuration=60;const BASE="https://api.heygen.com";
function key(){return process.env.HEYGEN_API_KEY||process.env.VYRAL_HEYGEN_API_KEY||""}
async function allowed(){const session=await getCustomerSession();if(!session)return {error:NextResponse.json({error:"Iniciá sesión."},{status:401})};const {data}=await supabaseAdmin().auth.admin.getUserById(session.userId);if(String(data.user?.user_metadata?.plan||session.plan||"")!=="ai")return {error:NextResponse.json({error:"Creator Reels requiere VYRAL AI."},{status:403})};return {session}}
async function defaultVoice(apiKey:string,language:string){const r=await fetch(BASE+"/v2/voices",{headers:{"x-api-key":apiKey,accept:"application/json"},cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)return "";const voices=j?.data?.voices||[];const want=language.toLowerCase().includes("español")?"es":language.toLowerCase().includes("portugu")?"pt":language.toLowerCase().includes("fran")?"fr":language.toLowerCase().includes("ital")?"it":language.toLowerCase().includes("deutsch")?"de":"en";const v=voices.find((x:any)=>String(x.language||x.locale||"").toLowerCase().startsWith(want))||voices[0];return String(v?.voice_id||"")}
export async function POST(req:Request){const gate=await allowed();if(gate.error)return gate.error;const apiKey=key();if(!apiKey)return NextResponse.json({error:"Falta HEYGEN_API_KEY."},{status:503});try{const b=await req.json();const script=String(b.script||"").trim(),avatarId=String(b.avatar||"").trim();if(!script||!avatarId)return NextResponse.json({error:"Elegí un guion y un avatar."},{status:400});const voiceId=await defaultVoice(apiKey,String(b.language||""));if(!voiceId)return NextResponse.json({error:"HeyGen no devolvió una voz disponible para este idioma."},{status:502});const productImages=Array.isArray(b.productImages)?b.productImages.filter((x:any)=>/^https?:\\/\\//i.test(String(x))).slice(0,4):[];const parts=script.split(/(?<=[.!?])\\s+/).filter(Boolean);const chunks=parts.length>1?parts:[script];const video_inputs=chunks.slice(0,Math.max(1,Math.min(4,chunks.length))).map((txt:string,i:number)=>{const image=productImages[i%Math.max(1,productImages.length)];return {character:{type:"avatar",avatar_id:avatarId,avatar_style:"normal"},voice:{type:"text",input_text:txt,voice_id:voiceId},...(image?{background:{type:"image",url:image}}:{})}});const body={video_inputs,dimension:{width:1080,height:1920},caption:Boolean(b.captions),test:false};const r=await fetch(BASE+"/v2/video/generate",{method:"POST",headers:{"x-api-key":apiKey,"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)return NextResponse.json({error:j?.message||j?.error?.message||j?.error||"HeyGen rechazó el render.",providerStatus:r.status},{status:502});const id=String(j?.data?.video_id||j?.video_id||"");if(!id)return NextResponse.json({error:"HeyGen no devolvió el identificador del video."},{status:502});return NextResponse.json({ok:true,id,status:"pending",provider:"heygen"});}catch(e:any){return NextResponse.json({error:e?.message||"No se pudo iniciar el Reel."},{status:500})}}
export async function GET(req:Request){const gate=await allowed();if(gate.error)return gate.error;const apiKey=key();if(!apiKey)return NextResponse.json({error:"Falta HEYGEN_API_KEY."},{status:503});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Falta el id del render."},{status:400});try{const r=await fetch(BASE+"/v1/video_status.get?video_id="+encodeURIComponent(id),{headers:{"x-api-key":apiKey,accept:"application/json"},cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)return NextResponse.json({error:j?.message||j?.error?.message||"No se pudo consultar el Reel."},{status:502});const d=j?.data||j;return NextResponse.json({id,status:d?.status||"processing",videoUrl:d?.video_url||null,thumbnailUrl:d?.thumbnail_url||null,error:d?.error||null});}catch(e:any){return NextResponse.json({error:e?.message||"No se pudo consultar el Reel."},{status:500})}}
