import Link from "next/link";
import "../legal.css";
export const metadata={title:"Términos del Servicio | VYRAL",description:"Términos del Servicio de VYRAL."};
export default function TermsPage(){return <main className="vyralLegalPage"><div className="vyralLegalGlow"/><div className="vyralLegalWrap"><nav className="vyralLegalNav"><Link href="/" className="vyralLegalBrand">V<span>Y</span>RAL</Link><Link href="/login" className="vyralLegalExit">← Volver</Link></nav><header className="vyralLegalHero"><small>LEGAL / VYRAL</small><h1>Términos del<br/><em>Servicio.</em></h1><p>Condiciones aplicables al uso de VYRAL y sus integraciones con plataformas sociales.</p><div className="vyralLegalMeta"><span>Última actualización</span><strong>20 de septiembre de 2026</strong></div></header><section className="vyralLegalContent">
<article><span>01</span><div><h2>Servicio</h2><p>VYRAL es una plataforma que permite a usuarios autorizados conectar y administrar sus propias cuentas sociales compatibles, publicar contenido y configurar automatizaciones mediante las APIs oficiales disponibles.</p></div></article>
<article><span>02</span><div><h2>Cuentas autorizadas</h2><p>Solo podés conectar cuentas propias o cuentas para las que tengas autorización suficiente. Sos responsable de mantener segura tu cuenta de VYRAL y de las acciones que autorices desde ella.</p></div></article>
<article><span>03</span><div><h2>Instagram y Meta</h2><p>Las funciones de Instagram y Facebook dependen de los permisos concedidos por el usuario y de las APIs de Meta. VYRAL no está afiliado ni patrocinado por Meta. El uso de esas plataformas continúa sujeto a sus términos y políticas.</p></div></article>
<article><span>04</span><div><h2>Contenido y automatizaciones</h2><p>Sos responsable del contenido, respuestas, reglas, palabras clave, mensajes y automatizaciones que configures. Debés contar con los derechos necesarios y utilizar el servicio de acuerdo con la legislación y las políticas de las plataformas conectadas.</p></div></article>
<article><span>05</span><div><h2>Uso prohibido</h2><p>No podés utilizar VYRAL para acceso no autorizado, spam abusivo, suplantación, infracciones de derechos, fraude, malware, evasión de controles de plataforma ni cualquier actividad ilegal.</p></div></article>
<article><span>06</span><div><h2>Servicios externos</h2><p>VYRAL depende de proveedores externos y APIs. Sus cambios, interrupciones, límites o decisiones de acceso pueden afectar temporal o permanentemente determinadas funciones.</p></div></article>
<article><span>07</span><div><h2>Disponibilidad</h2><p>Trabajamos para mantener el servicio disponible y seguro, pero no garantizamos funcionamiento ininterrumpido, resultados comerciales, alcance, visualizaciones, ventas o viralidad.</p></div></article>
<article><span>08</span><div><h2>Suspensión</h2><p>Podemos restringir el acceso ante incumplimientos, riesgos de seguridad, requerimientos legales, abuso del servicio, falta de pago o requerimientos de las plataformas integradas.</p></div></article>
<article><span>09</span><div><h2>Privacidad y eliminación</h2><p>El tratamiento de datos se describe en nuestra <Link href="/privacy">Política de Privacidad</Link>. Las solicitudes de eliminación se explican en <Link href="/data-deletion">Eliminación de datos</Link>.</p></div></article>
<article><span>10</span><div><h2>Contacto</h2><p>Para consultas sobre estos términos, escribí a <a href="mailto:nextgentechecommerce@gmail.com">nextgentechecommerce@gmail.com</a>.</p></div></article>
</section><footer className="vyralLegalFooter"><div className="vyralLegalPowered"><span>VYRAL</span><strong>Términos del servicio</strong></div><div><Link href="/privacy">Privacidad</Link><Link href="/data-deletion">Eliminar datos</Link></div></footer></div></main>}