import Link from "next/link";
import "../legal.css";
export const metadata={title:"Eliminación de datos | VYRAL",description:"Instrucciones para solicitar la eliminación de datos de VYRAL."};
export default function DataDeletionPage(){return <main className="vyralLegalPage"><div className="vyralLegalGlow"/><div className="vyralLegalWrap"><nav className="vyralLegalNav"><Link href="/" className="vyralLegalBrand">V<span>Y</span>RAL</Link><Link href="/login" className="vyralLegalExit">← Volver</Link></nav><header className="vyralLegalHero"><small>DATOS / VYRAL</small><h1>Eliminación<br/><em>de datos.</em></h1><p>Cómo revocar el acceso y solicitar la eliminación de la información asociada a tu cuenta.</p><div className="vyralLegalMeta"><span>Última actualización</span><strong>20 de septiembre de 2026</strong></div></header><section className="vyralLegalContent">
<article><span>01</span><div><h2>Desconectar una cuenta social</h2><p>Podés desconectar una cuenta desde la sección de cuentas conectadas de VYRAL. También podés revocar el acceso de VYRAL desde la configuración de aplicaciones y sitios web de Meta o de la plataforma correspondiente.</p></div></article>
<article><span>02</span><div><h2>Solicitar eliminación</h2><p>Para solicitar la eliminación de tus datos de VYRAL, enviá un correo desde la dirección asociada a tu cuenta a <a href="mailto:nextgentechecommerce@gmail.com">nextgentechecommerce@gmail.com</a> con el asunto “Eliminación de datos VYRAL”. Indicá el correo de tu cuenta y, si corresponde, el nombre de usuario de la cuenta social conectada.</p></div></article>
<article><span>03</span><div><h2>Verificación</h2><p>Podemos pedir información razonable para verificar que la solicitud corresponde al titular de la cuenta. Nunca te pediremos la contraseña de Instagram, Facebook u otra red social.</p></div></article>
<article><span>04</span><div><h2>Qué eliminamos</h2><p>Una vez verificada la solicitud, eliminaremos o desvincularemos los datos asociados que VYRAL ya no necesite para prestar el servicio, incluidos tokens de acceso y datos de cuentas conectadas, sujeto a cualquier obligación legal de conservación aplicable.</p></div></article>
<article><span>05</span><div><h2>Confirmación</h2><p>Cuando el proceso haya finalizado, enviaremos una confirmación al correo utilizado para realizar la solicitud. Revocar una integración puede impedir que VYRAL continúe publicando, leyendo eventos o ejecutando automatizaciones para esa cuenta.</p></div></article>
<article><span>06</span><div><h2>Contacto</h2><p>Consultas sobre privacidad y eliminación de datos: <a href="mailto:nextgentechecommerce@gmail.com">nextgentechecommerce@gmail.com</a>.</p></div></article>
</section><footer className="vyralLegalFooter"><div className="vyralLegalPowered"><span>VYRAL</span><strong>Control de tus datos</strong></div><div><Link href="/privacy">Privacidad</Link><Link href="/terms">Términos</Link></div></footer></div></main>}