import {NextResponse} from "next/server";
import {getCustomerSession} from "../../../../../lib/auth";
import {supabaseAdmin} from "../../../../../lib/supabase-admin";
const BUCKET="scheduled-media";
const clean=(v:any,n=1600)=>String(v||"").trim().slice(0,n);
export async function GET(){const s=await getCustomerSession();if(!s)return NextResponse.json({error:"No autorizado"},{status:401});const {data,error}=await supabaseAdmin().from("vyral_business_resources").select("*").eq("user_id",s.userId).order("created_at",{ascending:false});if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({resources:data||[]})}
export async function POST(req:Request){const s=await getCustomerSession();if(!s)return NextResponse.json({error:"No autorizado"},{status:401});const b=await req.json().catch(()=>({})),kind=b.kind==="url"?"url":"file",db=supabaseAdmin();if(kind==="url"){let url="";try{const u=new URL(clean(b.url,1800));if(!["http:","https:"].includes(u.protocol))throw 0;url=u.toString()}catch{return NextResponse.json({error:"Ingresá una URL válida."},{status:400})}const {data,error}=await db.from("vyral_business_resources").insert({user_id:s.userId,name:clean(b.name,180)||url,kind:"url",external_url:url,purpose:clean(b.purpose),send_when:clean(b.send_when,900)}).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true,resource:data})}
 const name=clean(b.name,180).replace(/[^a-zA-Z0-9._-]/g,"_")||"recurso",type=clean(b.type,120)||"application/octet-stream",size=Number(b.size||0);if(!size||size>50*1024*1024)return NextResponse.json({error:"El archivo debe pesar menos de 50 MB."},{status:400});const path=`business-resource/${s.userId}/${crypto.randomUUID()}-${name}`,q=await db.storage.from(BUCKET).createSignedUploadUrl(path,{upsert:false});if(q.error||!q.data)return NextResponse.json({error:"No se pudo preparar el archivo."},{status:500});const {data,error}=await db.from("vyral_business_resources").insert({user_id:s.userId,name:clean(b.name,180)||name,kind:"file",storage_path:path,mime_type:type,purpose:clean(b.purpose),send_when:clean(b.send_when,900)}).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true,resource:data,signedUrl:q.data.signedUrl,path})}
export async function DELETE(req:Request){const s=await getCustomerSession();if(!s)return NextResponse.json({error:"No autorizado"},{status:401});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Falta id"},{status:400});const db=supabaseAdmin(),old=await db.from("vyral_business_resources").select("storage_path").eq("id",id).eq("user_id",s.userId).maybeSingle();const del=await db.from("vyral_business_resources").delete().eq("id",id).eq("user_id",s.userId);if(del.error)return NextResponse.json({error:del.error.message},{status:500});if(old.data?.storage_path)await db.storage.from(BUCKET).remove([old.data.storage_path]);return NextResponse.json({ok:true})}
