import {NextResponse} from "next/server";
import {getCustomerSession} from "../../../../lib/auth";
import {supabaseAdmin} from "../../../../lib/supabase-admin";
export const runtime="nodejs"; export const maxDuration=300;
const OPENAI="https://api.openai.com/v1";
function sleep(ms:number){return new Promise(resolve=>setTimeout(resolve,ms))}
function retryDelayMs(r:Response,attempt:number){
 const retry=Number(r.headers.get("retry-after")||0);
 if(Number.isFinite(retry)&&retry>0)return Math.min(90000,Math.ceil(retry*1000)+750);
 return Math.min(90000,12000*Math.pow(2,attempt)+750);
}
function cleanJson(s:string){const a=s.indexOf("[");const b=s.lastIndexOf("]");if(a<0||b<a)throw new Error("La IA no devolvió una estructura válida.");return JSON.parse(s.slice(a,b+1))}
async function readProviderJson(r:Response,label:string){const raw=await r.text();try{return JSON.parse(raw)}catch{throw new Error(`${label} respondió con un formato inválido (HTTP ${r.status}). Reintentá la generación.`)}}
function safeError(j:any){return {type:j?.error?.type||null,code:j?.error?.code||null,message:j?.error?.message||null,param:j?.error?.param||null}}
async function diag(db:any,row:any){try{await db.from("creator_ai_diagnostics").insert(row)}catch{}}
export async function POST(req:Request){
 const session=await getCustomerSession();if(!session)return NextResponse.json({error:"Iniciá sesión."},{status:401});
 const db=supabaseAdmin(); let stage="boot";
 try{
  const {data}=await db.auth.admin.getUserById(session.userId);const plan=String(data.user?.user_metadata?.plan||session.plan||"");
  if(plan!=="escala"&&plan!=="ai")return NextResponse.json({error:"Creator IA está disponible en los planes Escala y VYRAL AI."},{status:403});
  const keySource=process.env.VYRAL_CREATOR_PRODUCTION?"VYRAL_CREATOR_PRODUCTION":"missing";
  const key=process.env.VYRAL_CREATOR_PRODUCTION;
  if(!key){await diag(db,{user_id:session.userId,stage:"config",ok:false,error_code:"missing_key",error_message:"VYRAL_CREATOR_PRODUCTION is not configured"});return NextResponse.json({error:"Falta configurar la API de OpenAI.",diagnosticStage:"config"},{status:503})}
  const body=await req.json();const humanMode=body.humanMode===true;const logoPath=typeof body.logoPath==="string"&&body.logoPath.startsWith(`${session.userId}/creator-ai/references/`)?body.logoPath:"";const personRefPaths=Array.isArray(body.personRefPaths)?body.personRefPaths.filter((x:any)=>typeof x==="string"&&x.startsWith(`${session.userId}/creator-ai/references/`)).slice(0,5):[];const count=Math.min(7,Math.max(1,Number(body.count)||6));const single=!!body.slide;
  const variationSeed=String(body.variationSeed||crypto.randomUUID());
  const visualStyles:Record<string,string>={
   "hand-drawn-editorial":"HAND-DRAWN EDITORIAL SKETCH — Dirección visual obligatoria: fondo blanco o papel blanco cálido con textura física sutil; ilustración artesanal claramente dibujada a mano con marcador negro, lápiz y crayón; trazos imperfectos, presión irregular y pequeñas imperfecciones humanas; personajes simples tipo monigote cuando aporten a la historia; objetos, teléfonos, flechas, ondas de audio, globos, subrayados y anotaciones dibujados manualmente. Tipografía principal con apariencia manuscrita/rotulador, grande y expresiva; palabras clave resaltadas con marcador cyan/turquesa y, de forma secundaria, amarillo. Mucho espacio blanco y una sola idea visual dominante por placa. Composición editorial limpia pero deliberadamente humana, como una página de sketchbook creada por un ilustrador real. Evitar fotografía, render 3D, CGI, interfaces futuristas, neón, glassmorphism, estética SaaS genérica, plantillas corporativas y acabado vectorial perfecto. No copiar la composición de la miniatura: usar solamente su lenguaje artístico y crear una escena distinta para cada historia. Mantener consistentes papel, materiales, grosor de trazo y paleta durante todas las placas.",
   "minimal-editorial":"MINIMAL EDITORIAL PREMIUM — Dirección visual obligatoria: composición editorial sofisticada y espaciosa, inspirada en dirección de arte de revista contemporánea y campañas premium. Base crema, marfil, beige cálido o blanco roto; tipografía sans serif negra de alto contraste con titulares grandes, contundentes y perfectamente jerarquizados; textos secundarios pequeños, aireados y precisos. Integrar fotografía lifestyle/producto realista de alta calidad con luz natural suave, sombras arquitectónicas de ventana y materiales sobrios como papel, madera clara, metal negro y cerámica. Usar pocos objetos cuidadosamente colocados, abundante espacio negativo, líneas finas, microetiquetas editoriales e iconografía monocromática mínima. Paleta restringida y elegante, sin saturación innecesaria. Cada placa debe sentirse diseñada por un director de arte, no como una plantilla de redes. Variar composición, encuadre y recurso narrativo entre historias sin perder identidad visual. Evitar neón, cyberpunk, dibujos infantiles, 3D caricaturesco, gradientes tecnológicos, interfaces SaaS, exceso de stickers, collages caóticos y fondos cargados. No copiar la composición de la miniatura: conservar únicamente iluminación, materiales, tipografía, sobriedad, fotografía editorial y nivel premium.",
   "retro-collage":"RETRO EDITORIAL COLLAGE / TORN PAPER — Dirección visual obligatoria: collage físico editorial de alto impacto construido con capas de papel rasgado, recortes impresos, fotografías monocromáticas de alto contraste, texturas de fotocopia, grano, halftone, tinta, cinta adhesiva, subrayados y trazos manuales. Paleta limitada y agresiva: negro, crema/blanco envejecido y un único color acento intenso, preferentemente rojo; el color puede variar si la identidad de marca lo exige, manteniendo siempre la restricción cromática. Titulares enormes de inspiración póster/zine, combinados con pequeñas notas manuscritas, etiquetas, fragmentos tipográficos y elementos editoriales. La composición debe sentirse táctil, imperfecta, urbana y deliberadamente recortada a mano, con profundidad real entre capas. Usar metáforas visuales, recortes inesperados y contraste de escala; cada nueva historia debe inventar una composición distinta. Evitar repetir ojo, periódico, código de barras o cualquier objeto de la miniatura salvo que el concepto lo justifique. Evitar estética digital limpia, SaaS, 3D pulido, glassmorphism y plantillas simétricas. No copiar la referencia: conservar únicamente el lenguaje de collage físico, textura, energía editorial y contraste.",
   "comic-pop":"MODERN COMIC / POP ILLUSTRATION — Dirección visual obligatoria: ilustración editorial tipo cómic contemporáneo, energética y extremadamente legible en móvil. Personajes expresivos dibujados con contornos negros gruesos, formas limpias y sombreado ilustrado; globos de diálogo, carteles, flechas, líneas cinéticas, pequeños doodles e iconos solo cuando ayudan a contar la idea. Titulares grandes, atrevidos y de lectura instantánea integrados como parte de la escena. Paleta de alto contraste dominada por negro, blanco y cyan/azul VYRAL, con uno o dos acentos cálidos como amarillo; mantener colores sólidos y controlados. Composición dinámica con profundidad, diagonales y variación de escala, pero sin saturar cada rincón. Cada pieza debe inventar su propio gag, metáfora, personaje, encuadre y mecanismo visual: NO repetir siempre persona frente a notebook, dedo señalando, bombilla, checklist ni globo gigante. El cómic es el lenguaje artístico, no una plantilla narrativa. Puede usar viñetas, split-screen, secuencias, close-ups, objetos personificados o escenas absurdas según el concepto. Evitar anime, estética infantil preescolar, 3D, fotografía realista, cyberpunk y plantillas de thumbnail genéricas. No copiar la referencia: preservar solamente energía, línea gráfica, contraste, expresividad y claridad visual.",
   "cinematic-motivation":"CINEMATIC HIGH-CONTRAST EDITORIAL — Dirección visual obligatoria: fotografía cinematográfica premium, oscura y dramática, con luz natural direccional de amanecer/atardecer, sombras profundas, reflejos cálidos y contraste intenso. Integrar titulares editoriales gigantes en blanco con un único color acento eléctrico —amarillo ácido por defecto—, subrayados o anotaciones manuscritas muy puntuales y composición con sensación de campaña deportiva/negocio de alto nivel. Objetos, espacios, producto o escenas reales deben sentirse tangibles y fotografiados con lente profesional, profundidad de campo y gradación cinematográfica. Mantener negro/carbón como base y restringir el acento a pocos puntos de atención. Cada historia debe inventar escenario, protagonista visual, encuadre y metáfora nuevos: NO repetir escritorio, laptop, shaker, libros, checklist ni frases motivacionales salvo que la idea lo exija. Este estilo puede vivir en calle nocturna, fábrica, gimnasio, estudio, auto, arquitectura, producto macro, manos en acción o escenarios abstractos realistas. Evitar renders 3D evidentes, cyberpunk de neón, stock corporativo, composición SaaS, exceso de overlays y estética de póster motivacional genérico. No copiar la miniatura: preservar únicamente fotografía cinematográfica, contraste, jerarquía tipográfica, luz dramática y energía premium.",
   "urban-editorial":"URBAN ASPIRATIONAL EDITORIAL CAMPAIGN — Dirección visual obligatoria: campaña editorial contemporánea fotografiada en arquitectura urbana real, hormigón, escaleras, ciudad, espacios monumentales y luz de amanecer o atardecer. Composición limpia y aspiracional con una figura humana, producto u objeto integrado naturalmente cuando el concepto lo requiera; sensación de progreso, recorrido y movimiento físico sin convertir cada pieza en motivación deportiva. Titulares sans serif condensados o grotescos, enormes, negros o blancos, con bloques de alto impacto; un único acento amarillo aplicado como brochazo, highlight o señal visual. Combinar fotografía premium con pequeñas notas manuscritas, flechas o fragmentos de papel solo de forma puntual. Mucho aire, geometría arquitectónica, perspectiva y escala. Cada historia debe crear una situación y encuadre nuevos: NO repetir escaleras, persona de espaldas, mochila, skyline, disciplina ni camino ascendente salvo que el concepto realmente lo pida. Puede trasladarse a estaciones, pasillos, azoteas, talleres, locales, canchas, depósitos, fachadas, interiores brutalistas o espacios cotidianos. Evitar stock corporativo, collage dominante, estética cyberpunk, render 3D, composición de escritorio y póster motivacional genérico. No copiar la referencia: conservar dirección fotográfica urbana, escala, tipografía, acento amarillo y sofisticación editorial.",
   "object-metaphor":"CONCEPTUAL OBJECT METAPHOR — Dirección visual obligatoria: una única metáfora visual construida alrededor de un objeto cotidiano o simbólico fotografiado con tratamiento premium y composición de naturaleza muerta contemporánea. Fondo sobrio, luz escultórica, contraste preciso y muchísimo espacio negativo; el objeto debe comunicar la idea incluso antes de leer el titular. Tipografía editorial limpia y secundaria al concepto visual. Puede recurrir a transformaciones imposibles pero visualmente creíbles, escalas inesperadas, materiales alterados, objetos fusionados, sombras con significado o relaciones físicas sorprendentes. La selección del objeto debe nacer del mensaje de cada historia y cambiar radicalmente entre generaciones. NO repetir reloj de arena, tiempo, laptop, escritorio, libros, amarillo/negro ni discurso motivacional por defecto. La paleta debe adaptarse al tema y a la marca, no quedar fijada a la referencia. Evitar composición de póster motivacional, escenas urbanas aspiracionales, personas subiendo, collage, cómic, interfaz SaaS y fotografía stock. No copiar la referencia: conservar únicamente el principio de metáfora de objeto, dirección de arte premium, simplicidad y lectura conceptual inmediata.",
   "animated-3d":"VIBRANT 3D ANIMATED STORYTELLING — Dirección visual obligatoria: universo 3D estilizado, expresivo y de calidad cinematográfica, con personajes u objetos de formas suaves, volumen claro, materiales ricos y expresiones muy legibles en pantalla pequeña. Iluminación cálida y espectacular, profundidad de campo, color intenso y composición con energía de película animada contemporánea. Priorizar storytelling visual inmediato: contraste entre estados, acciones congeladas, exageración controlada, escala, perspectiva y props que cuenten la historia sin depender del texto. Titulares grandes pueden integrarse como objetos físicos o capas gráficas, pero nunca deben tapar la escena. La paleta debe variar según marca y concepto; NO fijar amarillo, negro ni escritorio. Cada generación debe cambiar escenario, personaje, encuadre, emoción y mecanismo narrativo. NO repetir antes/después, chico con laptop, dormitorio, checklist, puño levantado ni ciudad luminosa salvo que el concepto lo requiera. Puede representar producto, comida, servicios, tecnología, retail, educación, deporte, objetos personificados o mundos miniatura. Evitar apariencia de plantilla motivacional, fotografía real, collage, cómic 2D, estética infantil barata, personajes genéricos clonados y render plástico sin dirección de arte. No copiar la miniatura: conservar únicamente lenguaje 3D animado, expresividad, riqueza visual y capacidad viral.",
   "scrapbook-vision":"TACTILE SCRAPBOOK / VISION BOARD EDITORIAL — Dirección visual obligatoria: composición física de scrapbook y tablero editorial construida con papeles envejecidos, fotografías impresas, polaroids, recortes, cinta adhesiva, chinches, sellos, tickets, notas manuscritas, garabatos y capas táctiles claramente diferenciadas. Debe sentirse armado a mano sobre una mesa, pared o cuaderno real, con sombras pequeñas entre materiales, bordes rasgados y textura analógica. La narrativa se construye mediante asociaciones visuales entre fragmentos: aspiraciones, producto, proceso, lugares, personas, datos o recuerdos según el tema. Titular central fuerte pero integrado como una pieza más del tablero, no como póster digital flotante. Paleta adaptable: papel natural y negro pueden servir de base, pero colores, fotografías y acentos deben responder a la marca y al concepto. Cada generación debe cambiar radicalmente los recortes, materiales, organización, jerarquía y metáfora. NO repetir viajes, autos, gimnasio, laptop, checklist, disciplina, cinta amarilla ni los elementos concretos de la referencia salvo que correspondan al mensaje. Diferenciarlo del estilo 03: aquí domina el diario personal/vision board, la acumulación de recuerdos y conexiones; no el zine agresivo de alto contraste. Evitar interfaces digitales, 3D, cómic, fotografía única a página completa y collage genérico de plantilla. No copiar la miniatura: preservar solamente tactilidad, capas físicas, espontaneidad organizada y riqueza narrativa.",
   "luxury-lifestyle":"LUXURY LIFESTYLE EDITORIAL — Dirección visual obligatoria: fotografía lifestyle aspiracional de nivel campaña de lujo, con arquitectura sofisticada, luz natural de amanecer o golden hour, materiales nobles, composición editorial espaciosa y gradación cálida refinada. Combinar escena fotográfica inmersiva con tipografía serif de moda/revista y sans serif muy limpia; jerarquía elegante, aire y pequeños detalles editoriales. El protagonista puede ser una persona, producto, espacio, experiencia o ritual según el mensaje. Paleta sobria y premium: marfil, negro, piedra, madera, dorado apagado y tonos naturales, adaptables a la marca. IMPORTANTE: el estilo NO significa riqueza, mansiones, laptop, disciplina ni productividad; esos son solo elementos de la referencia. Cada generación debe inventar otro universo aspiracional coherente con el producto: gastronomía, belleza, retail, wellness, viaje, servicio profesional, moda, tecnología o experiencias. Evitar póster motivacional, checklist, libros apilados, escritorio recurrente, collage, cómic, 3D y estética influencer genérica. No copiar la miniatura: preservar únicamente fotografía premium, sofisticación editorial, luz, espacio y sensación aspiracional.",
   "game-world":"GAME WORLD / PROGRESSION ADVENTURE — Dirección visual obligatoria: convertir el concepto en un mundo de videojuego visualmente espectacular, con niveles, mapas, portales, recompensas, obstáculos, inventario, caminos o mecánicas de progreso elegidas según el mensaje. Mezclar 3D estilizado con recursos gráficos de HUD/pixel solo cuando aporten. Color vibrante, profundidad, escala épica y lectura instantánea. IMPORTANTE: no repetir montaña, camino ascendente, trofeo, chico de espaldas, hábitos ni disciplina de la referencia. Cada negocio debe producir su propia mecánica visual: restaurante como mapa de sabores, software como misión, producto como power-up, educación como árbol de habilidades, etc. El concepto manda; no una plantilla gamer. Evitar aspecto de videojuego genérico, interfaces ilegibles y saturación sin foco.",
   "neo-pop-surreal":"NEO-POP SURREAL STOP-SCROLL — Dirección visual obligatoria: imagen editorial maximalista y surrealista con una anomalía visual imposible que se entienda en menos de un segundo. Combinar elementos clásicos, cotidianos o de producto de maneras inesperadas: cortes anatómicos metafóricos, escalas absurdas, objetos atravesando espacios, materiales incompatibles, perspectivas imposibles, duplicaciones o transformaciones visuales. Tipografía brutalista de alto contraste, bloques cromáticos intensos y composición asimétrica controlada. Cada publicación debe construir UNA rareza central completamente nueva; nunca reutilizar busto clásico, cerebro abierto, checklist, collage de papeles, disciplina ni la paleta de la referencia por defecto. El objetivo es provocar: «¿qué estoy viendo?» y después hacer que el mensaje cierre la metáfora. Evitar surrealismo aleatorio sin relación con el producto; la rareza debe comunicar una idea concreta.",
   "cinematic-threshold":"CINEMATIC THRESHOLD / CONTRAST OF WORLDS — Dirección visual obligatoria: fotografía cinematográfica hiperrealista construida alrededor de un umbral físico o transición espacial contundente que separa dos estados narrativos. Puede ser puerta, abertura, corte arquitectónico, túnel, ventana, grieta, pasaje o frontera visual, pero debe elegirse según el mensaje y NO repetirse mecánicamente. Un lado expresa problema/tensión y el otro solución/deseo mediante iluminación, ambiente, utilería y composición; evitar depender de carteles pequeños. PRIORIDAD DE CARRUSEL: formato vertical 4:5 y lectura móvil instantánea. Reservar una zona limpia y deliberada para UN titular principal muy grande, corto y perfectamente legible; copy secundario breve, alto contraste, sin texto microscópico ni decenas de etiquetas dentro de la escena. El texto jamás debe competir con el fondo. La referencia de sacrificio/libertad es solo lenguaje visual: NO repetir dormitorio, cadenas, amanecer, ciudad, hombre caminando, disciplina, hábitos, libros, laptop, amarillo, negro ni narrativa motivacional salvo que el negocio lo requiera. Adaptar el contraste a cualquier producto o servicio con mundos y escenarios nuevos. Debe sentirse como fotografía publicitaria real de alto presupuesto, no ilustración, 3D, videojuego ni póster motivacional genérico.",
   "editorial-duality":"EDITORIAL DUALITY / PHOTOGRAPHIC STILL-LIFE COMPARISON — Dirección visual obligatoria: fotografía cenital o de estudio de objetos REALES organizada como una comparación visual contundente entre dos estados, elecciones, procesos o resultados. Debe sentirse como una producción fotográfica editorial tangible: materiales, sombras, superficies, objetos y pequeñas imperfecciones físicas; NO ilustración, NO render 3D. La división puede ser geométrica, cromática, material o espacial y no tiene que ser siempre mitad izquierda/mitad derecha. PRIORIDAD ABSOLUTA: formato 4:5, titular principal enorme y perfectamente legible en móvil, máximo 1-2 mensajes secundarios breves. Evitar llenar la escena de etiquetas diminutas. Los objetos deben explicar el concepto antes de leer. IMPORTANTE: la miniatura de hábitos buenos/malos es solo una referencia de gramática visual. NO repetir teléfono, joystick, comida chatarra, libros, mancuerna, escritorio, disciplina, rojo/verde ni narrativa de productividad por defecto. Elegir objetos específicos del negocio y una comparación inesperada en cada generación. Puede funcionar con productos, gastronomía, belleza, servicios, tecnología, educación, retail o cualquier nicho. Buscar composición de campaña fotográfica y no plantilla de redes sociales.",
   "mind-cutaway":"MIND CUTAWAY / INNER WORLD PORTRAIT — Dirección visual obligatoria: retrato fotográfico hiperrealista convertido en una sección física imposible que revela un microescenario interior relacionado con el concepto. La apertura puede ocurrir en cabeza, torso, objeto sostenido o silueta, pero debe sentirse construida físicamente y fotografiada en estudio, con materiales, escala y luz plausibles. El interior funciona como una mini escenografía narrativa, no como cerebro anatómico literal. Formato 4:5. Un único titular dominante, grande y legible en móvil; máximo un apoyo breve. IMPORTANTE: NO repetir joven con ojos cerrados, cabeza abierta horizontalmente, escalera, habitación, redes sociales, joystick, libros, gimnasio, disciplina ni contraste productividad/distracción. Cada generación debe inventar una anatomía visual y micro-mundo completamente distintos según el negocio: un producto puede revelar su proceso, un servicio su mecanismo invisible, una marca el mundo que habilita. Evitar gore, anatomía explícita, 3D caricaturesco, póster motivacional y exceso de cartelitos. La referencia define únicamente la idea de retrato/objeto real + corte imposible + mundo interior cinematográfico.",
   "focus-arena":"FOCUS ARENA / OVERHEAD SOCIAL PRESSURE — Dirección visual obligatoria: fotografía cenital de gran escala donde un sujeto, producto o acción central queda aislado dentro de una frontera física o lumínica claramente visible, mientras fuerzas externas invaden, rodean, observan, presionan o compiten desde la periferia. La composición debe leerse como un diagrama humano fotografiado en el mundo real: centro muy claro, periferia caótica, contraste tonal fuerte y geometría memorable. El círculo de la referencia NO es obligatorio: variar a cuadrados, corredores, vacíos, líneas, mesas, luz, arquitectura o agrupaciones humanas según el concepto. Formato vertical 4:5; titular enorme y legible desde móvil, máximo 1-2 apoyos breves. IMPORTANTE: NO repetir estudiante en escritorio, multitud monocroma, círculo luminoso, disciplina, distracciones, etiquetas amarillas/negras ni narrativa productividad vs redes. Aplicar la gramática centro protegido/periferia hostil al negocio real: producto entre imitaciones, chef entre pedidos, marca entre ruido publicitario, creador entre comentarios, etc. Fotografía publicitaria real, perspectiva cenital extrema y puesta en escena física; NO 3D, NO ilustración, NO collage, NO póster motivacional genérico.",
   "gritty-sketch-collage":"GRITTY HAND-DRAWN SKETCH COLLAGE — Dirección visual obligatoria: composición artesanal de dibujo a mano con tinta, grafito, carboncillo, rayones, flechas, tachones, papel envejecido, recortes y pequeñas irrupciones fotográficas o de color. Debe sentirse como una página obsesivamente trabajada de un cuaderno creativo o pared de estudio, no como una ilustración digital limpia. Combinar trazos imperfectos, notas manuscritas, marcos rotos, manchas y capas físicas con UNA idea visual central clara. Formato 4:5 y lectura móvil: titular grande dibujado a mano, perfectamente legible, con máximo 1-2 apoyos importantes; los garabatos secundarios son textura, nunca información indispensable. La referencia de disciplina es SOLO gramática visual: NO repetir cabeza masculina, mente partida, redes sociales, comida chatarra, libros, amanecer, listas de hábitos, negro/amarillo/rojo ni mensaje motivacional. Para cada negocio inventar símbolos, dibujos, recortes y metáforas propios del producto. Evitar estética 3D, CGI, render brillante, fotografía cinematográfica dominante y plantilla corporativa. Priorizar humanidad, imperfección, energía gráfica y sensación de pieza única hecha físicamente a mano.",
   "minimal-note-editor":"MINIMAL NOTE EDITOR / VIRAL TEXT SCREEN — Dirección visual obligatoria: una única ventana de editor de notas o documento digital ocupa casi todo el encuadre sobre fondo negro o muy oscuro, fotografiada o renderizada con perspectiva sutil, bordes redondeados y textura analógica/grano fino. Interfaz minimalista creíble con barra superior y controles discretos, pero SIN copiar marcas, nombres de apps ni UI propietaria exacta. El protagonista absoluto es UNA frase corta, potente y emocional escrita en tipografía sans-serif negra, enorme, limpia y perfectamente legible; debe sentirse como una idea privada que alguien acaba de escribir y todavía tiene el cursor activo. Añadir solo 1-3 intervenciones dibujadas a mano MUY sutiles —círculo imperfecto, subrayado, flecha, pequeño símbolo o nota manuscrita— que destaquen una palabra clave sin convertirlo en collage. Muchísimo espacio negativo, paleta casi monocroma, composición austera y sensación humana. Formato 4:5. Ideal para hooks, afirmaciones, verdades incómodas, frases de ebook, consejos, preguntas o mensajes de marca. IMPORTANTE: la referencia de disciplina es SOLO lenguaje visual. NO repetir disciplina, resultados mañana, corona, Confía en el proceso, título de ventana, textos ni doodles exactos. Generar copy específico del negocio y variar qué palabra se interviene y qué gesto manual aparece. Evitar fotografías de personas/productos, 3D llamativo, fondos complejos, múltiples bloques de texto, collage y estética publicitaria tradicional. El stop-scroll debe venir de la brutal simplicidad, escala tipográfica y sensación de nota auténtica.",
   "human-documentary-story":"HUMAN DOCUMENTARY STORY / ULTRA-REAL PERSON — Dirección visual obligatoria: fotografía vertical 9:16 que parezca una foto REAL tomada con cámara o smartphone premium a una persona real en un momento cotidiano, no una escena generada por IA. El ser humano es el protagonista inequívoco: rostro visible cuando tenga sentido, anatomía natural, poros, textura de piel, vello, arrugas finas, ojeras sutiles, cabello irregular, manos correctas, ropa con pliegues y pequeñas imperfecciones. Evitar piel plástica, simetría perfecta, belleza de modelo artificial, pose rígida y look de render. Usar luz natural o práctica creíble, exposición fotográfica real, profundidad de campo moderada y composición espontánea tipo documental/lifestyle. El entorno debe ser LIMPIO y simple: pocos objetos relevantes, aire negativo y una sola acción humana clara. Formato Instagram Story; texto mínimo: UN titular limpio y opcionalmente una línea secundaria, en zona libre y perfectamente legible. La referencia es SOLO el nivel de humanidad y realismo: NO copiar hombre de espaldas, dormitorio, trading, bulldog, mate, libros, checklist, amanecer, disciplina ni sus frases. Según el negocio variar radicalmente persona, edad adulta, género, vestuario, lugar, hora, actividad, encuadre y emoción. Puede ser cliente usando producto, profesional trabajando, persona en calle, hogar, comercio, estudio, cocina, viaje o servicio real. PROHIBIDO: CGI, 3D, surrealismo, collage, exceso de props, paredes llenas de copy y estética de póster motivacional. Debe poder confundirse con una fotografía editorial auténtica publicada por una marca humana.",
   "clean-explainer-editorial":"CLEAN EXPLAINER EDITORIAL / SOCIAL EDUCATION — Dirección visual obligatoria: diseño editorial limpio y contemporáneo para explicar una decisión, comparación o concepto en menos de un segundo. Fondo claro cálido o neutro con textura de papel MUY sutil, enorme titular sans-serif negro de alto peso y jerarquía agresiva, una palabra o fragmento clave resaltado con bloque cromático intenso, subtexto breve y mucho aire negativo. Integrar 1 a 3 fotografías de producto u objetos hiperrealistas recortados limpiamente, con sombras suaves y composición tipo campaña editorial. Añadir solo algunos gestos humanos dibujados a mano —flecha, subrayado, círculo, nota breve— para dirigir la lectura. Formato 4:5. El titular debe ser perfectamente legible en móvil y ocupar gran parte de la placa. La referencia de tecnología usada/nueva es SOLO gramática visual: NO repetir iPhone, MacBook, PlayStation, tecnología, usado vs sellado, azul/verde, textos ni marcas de la referencia salvo que el negocio lo requiera. Adaptar la metáfora, objetos, colores de acento y copy al negocio real. Puede explicar diferencias, errores, procesos, mitos, beneficios, antes/después conceptual o decisiones de compra. Evitar collage caótico, papel rasgado, estética sketch dominante, 3D futurista, fondos oscuros y exceso de elementos. Resultado: limpio, comercial, educativo, humano y stop-scroll.",
   "cinematic-human-hook":"CINEMATIC HUMAN HOOK / EBOOK COVER — Dirección visual obligatoria: portada vertical de alto impacto construida alrededor de UNA fotografía humana hiperrealista y cinematográfica que represente un problema cotidiano reconocible. El rostro, postura y acción deben comunicar la tensión antes de leer. Superponer un titular gigantesco, condensado, blanco, de 2-4 líneas, con UNA pregunta, palabra o remate dentro de un bloque de color intenso. Debajo, máximo 2-4 microbeneficios con iconos lineales simples y texto corto. Fondo real oscuro o de contraste alto, iluminación práctica creíble, profundidad fotográfica, piel y anatomía naturales; composición limpia y contundente como portada de ebook, anuncio educativo o carrusel premium. La referencia de entrenar/comer es SOLO gramática visual: NO repetir gimnasio, cocina, atleta cansado, verduras, disciplina, alimentación, rojo, frases ni iconos salvo que el negocio lo requiera. Para cada tema inventar una situación humana distinta: emprendedor ante una decisión, profesional con un problema, cliente usando un producto, creador bloqueado, trabajador resolviendo algo, etc. El hook debe nacer del dolor o contradicción del tema. Formato 4:5; legibilidad móvil absoluta. Evitar split-screen, dos diseños en uno, collage, CGI, 3D, estética IA plástica y exceso de texto. Debe parecer una campaña fotográfica editorial real con dirección de arte profesional.",
   "native-lockscreen-reminder":"NATIVE LOCKSCREEN REMINDER / VIRAL UI — Dirección visual obligatoria: recrear la sensación de una pantalla de bloqueo móvil real y cotidiana, vertical, con fondo fotográfico extremadamente simple y creíble, hora grande, fecha y UNA notificación protagonista que contiene el hook principal. Debe parecer una captura que alguien podría haber recibido de verdad, no un póster diseñado. La notificación puede adoptar semántica de recordatorio, calendario, alarma, mensaje del sistema o nota según el negocio, manteniendo una interfaz genérica inspirada en sistemas móviles pero SIN copiar logotipos, marcas ni UI propietaria exacta. El copy de la notificación debe ser corto, humano, inesperado y legible instantáneamente; puede funcionar como consejo, pregunta, verdad incómoda, alerta, beneficio o llamada de atención. Añadir como máximo UN detalle humano sutil fuera de la UI —una frase manuscrita, pequeño subrayado o símbolo— solo si mejora el concepto. Formato 9:16 o 4:5 según destino. Fondo con luz natural, grano sutil y profundidad real; muchísimo espacio visual. IMPORTANTE: la referencia es SOLO la idea de contenido nativo. NO repetir 07:00, lunes 22, dormitorio, disciplina, libertad, recordatorio ni frases del ejemplo. Variar hora, contexto, tipo de alerta, wallpaper y copy en función del negocio. Evitar collage, 3D, póster publicitario, tipografía gigante externa, exceso de notificaciones y estética artificial. El stop-scroll debe venir de que el usuario crea por un instante que está viendo SU propia pantalla.",
   "native-search-intent":"NATIVE SEARCH INTENT / VIRAL QUERY — Dirección visual obligatoria: escena fotográfica realista centrada en un buscador web abierto en laptop o desktop, donde la consulta escrita funciona como hook y las sugerencias automáticas desarrollan el concepto del negocio. Debe sentirse como una búsqueda privada capturada por accidente, no como anuncio. Interfaz de buscador genérica y familiar SIN depender de logos ni copiar una marca exacta; consulta grande y legible, 5-8 sugerencias cortas, plausibles y específicas que despierten curiosidad. Entorno físico muy secundario, limpio y creíble, con luz natural y máximo 2-3 objetos contextuales. Formato 4:5. IMPORTANTE: NO repetir cómo ser una mejor versión de mí, disciplina, libros, termo, dormitorio/escritorio ni frases de la referencia. Para cada negocio inventar una intención de búsqueda real: problema, deseo, comparación, duda incómoda o decisión de compra. Evitar póster, collage, 3D, UI fantasiosa y exceso de decoración. El stop-scroll nace de reconocer una búsqueda que el público podría haber escrito.",
   "physical-daily-plan":"PHYSICAL DAILY PLAN / FOUND NOTE — Dirección visual obligatoria: fotografía hiperrealista de UNA hoja física real encontrada en un entorno cotidiano, pegada, apoyada, doblada o sujeta de forma natural. La hoja contiene un título corto y 3-5 líneas manuscritas o checklist que expresan el concepto del negocio como si una persona real lo hubiera escrito para sí misma. Papel con textura, arrugas, cinta, sombras y pequeñas imperfecciones auténticas; luz natural cinematográfica pero no publicitaria. El entorno debe aportar contexto sin competir: pared, heladera, taller, escritorio, mostrador, espejo, puerta, cocina, depósito, etc., elegido según el negocio. Formato 4:5; escritura perfectamente legible en móvil. IMPORTANTE: NO repetir PLAN DE HOY, disciplina, hábitos, libros negros, pared de dormitorio, planta, laptop ni frases de la referencia. Variar soporte, caligrafía, ubicación, lista y objetos contextuales. Evitar interfaces digitales, pantalla de teléfono, collage, 3D, composición de póster y demasiados props. Debe parecer una nota real que alguien encontró y fotografió, y el hook nace de leer algo íntimo, útil o inesperado."
  };
  const visualStyleId=String(body.visualStyle||"");const visualStylePrompt=visualStyles[visualStyleId]||"";
  const strategy=single?JSON.stringify([body.slide]):`Creá ${count} placas distintas. Estructura recomendada: hook que detiene el scroll, problema/deseo, consecuencia o tensión, solución, beneficio/prueba, oferta y CTA. Adaptala al número de placas. VARIACIÓN OBLIGATORIA ENTRE GENERACIONES: esta ejecución tiene semilla creativa ${variationSeed}. Elegí una dirección visual y contextos nuevos; no recurras por defecto al mismo fondo editorial beige/blanco, escritorio, papel cuadriculado o collage usado habitualmente.`;
  const referenceSystem=`REFERENCIA VISUAL VYRAL (usar como lenguaje de diseño, NO copiar piezas ni identidades): carruseles editoriales de alto impacto; cada placa sale terminada con texto dentro de la imagen. Jerarquía tipográfica extrema: titular corto grande, 1-2 palabras clave destacadas con bloques de color/subrayado/marcador, texto secundario breve y legible. Mezclar según el tema: editorial blanco con grilla sutil y acentos fuertes; dark premium con neón/gradientes; hoja/cuaderno físico fotografiado con escritura manual, resaltadores, flechas y doodles; collage con fotos/producto/capturas en tarjetas, marcos, stickers, badges y datos. Mucho contraste, composición clara, aire, profundidad y foco único. No hacer una ilustración genérica a pantalla completa. La narrativa visual debe variar entre placas pero mantener paleta/tipografía/sistema. DIVERSIDAD FUERTE ENTRE PUBLICACIONES: cada carrusel debe elegir un universo visual/contextual distinto según el negocio y la idea. Rotar de forma deliberada entre fotografía lifestyle/location, estudio de producto, arquitectura/interiores, calle/exterior, macro/detail, fondos cromáticos sólidos, gradientes/3D, dark premium, collage, editorial, interfaces/diagramas cuando correspondan. No usar siempre papel beige/blanco, grilla, escritorio, cuaderno, pared crema ni el mismo tipo de collage. El fondo y escenario deben ser consecuencia del concepto, no una plantilla fija. STOP-SCROLL OBLIGATORIO: antes de proponer cada concepto, buscá una anomalía, contraste, pregunta visual, metáfora, escala, encuadre o mecanismo narrativo que haga que la primera placa sea difícil de ignorar aun sin leer el copy. Evitá la primera solución obvia. Si una idea podría confundirse con una publicación genérica de Canva o con una pieza ya vista en el feed, descartala internamente y buscá otra. Priorizá conceptos propios, específicos al producto y visualmente memorables por encima de tendencias copiadas. El hook debe impactar inmediatamente. La última placa debe ser un CTA grande y accionable. No inventar métricas, testimonios, logos, perfiles, capturas ni resultados: si faltan pruebas reales, usar beneficio/explicación sin fingir evidencia.`;
  const humanDirection=humanMode?`MODO HUMANO / PERSONAL BRAND: el carrusel debe sentirse producido por un director creativo y fotógrafo humano. Usá a la persona de las referencias cuando aporte a la narrativa, alternando retrato/lifestyle/acción/trabajo/producto/capturas/diagramas para no repetir composiciones. Fotografía hiperrealista, piel y textura naturales, iluminación y óptica plausibles, manos y anatomía realistas, escenarios creíbles, imperfecciones fotográficas sutiles. La persona debe conservar identidad visual consistente entre placas: forma del rostro, ojos, nariz, boca, mandíbula, cabello, tono de piel y proporciones. No embellecer, rejuvenecer ni rediseñar rasgos. No copiar literalmente piezas, marcas, usernames o composiciones de otros creadores. Cada placa debe tener una composición diferente pero una dirección de arte coherente.`:"";
  const prompt=`Sos el director creativo de VYRAL. Diseñás carruseles de Instagram persuasivos en español rioplatense, claros y modernos. ${referenceSystem} ${humanDirection} No inventes testimonios, cifras ni garantías. Cada placa debe tener poco texto y avanzar una historia. Negocio/producto: ${String(body.business||"")}. Oferta: ${String(body.offer||"")}. Público: ${String(body.audience||"")}. Objetivo: ${String(body.goal||"ventas")}. CTA final: ${String(body.cta||"Escribí INFO")}. IMPORTANTE: el CTA se escribe UNA SOLA VEZ. Si la frase ya contiene un verbo de acción como "comentá", "escribí", "mandame", "comprá" o equivalente, no lo antepongas ni lo repitas. Ejemplo: si CTA final es "Comentá BRYAN", renderizar exactamente "Comentá BRYAN", nunca "Comentá Comentá BRYAN". Estética solicitada: ${String(body.tone||"animado premium")}. ${visualStylePrompt?`ESTILO VISUAL SELECCIONADO POR EL USUARIO — respetar por encima de la dirección visual genérica: ${visualStylePrompt}`:""} ${strategy} Respondé SOLO JSON array con objetos {"role":"hook|problema|tension|solucion|beneficio|oferta|cta","title":"máx 9 palabras","copy":"máx 22 palabras","visualPrompt":"dirección de arte detallada para una placa TERMINADA, indicando layout, fondo, tipografía, jerarquía, bloques, fotos/ilustraciones, flechas/stickers y ubicación del texto; composición vertical 4:5, misma identidad/paleta en todo el carrusel"}.`;
  const textModel=process.env.VYRAL_TEXT_MODEL||"gpt-5.6-sol"; stage="text_model";
  const tr=await fetch(OPENAI+"/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:textModel,messages:[{role:"user",content:prompt}]})});
  const tj=await readProviderJson(tr,"La estrategia de IA"); const trId=tr.headers.get("x-request-id");
  await diag(db,{user_id:session.userId,stage,ok:tr.ok,http_status:tr.status,model:textModel,request_id:trId,error_type:safeError(tj).type,error_code:safeError(tj).code,error_message:safeError(tj).message,details:{key_source:keySource,endpoint:"chat/completions",param:safeError(tj).param}});
  if(!tr.ok)return NextResponse.json({error:tj.error?.message||"Falló la estrategia de IA.",diagnosticStage:stage,requestId:trId},{status:tr.status});
  let slides=cleanJson(tj.choices?.[0]?.message?.content||""); slides=single?slides.slice(0,1):slides.slice(0,count);
  const model=process.env.VYRAL_IMAGE_MODEL||"gpt-image-2";
  const generated=[];
  for(let i=0;i<slides.length;i++){
   const s=slides[i];
   const imageStage=`image_${i+1}`;const sceneRule=`Creative run ${variationSeed}, slide ${i+1}/${slides.length}. Scene type: ${String(s.sceneType||"concept-specific")}. Background/environment: ${String(s.background||"choose a distinctive environment driven by this slide")}. Do not default to beige paper, off-white editorial grids, desks or notebook textures unless explicitly required by the concept.`;const personRule=humanMode&&personRefPaths.length?`Identity references are attached. Preserve the same person faithfully across generated scenes: facial geometry, eyes, nose, mouth, jaw, hair, skin tone and distinctive visible traits. Do not beautify, age-shift, change ethnicity, reshape the face or invent facial details. Use natural photographic variation only in pose, expression, wardrobe, lighting, lens and environment. Do not place the person in every slide unless narratively useful.`:"No person identity reference is supplied.";const logoRule=logoPath?"A brand logo reference is attached. Preserve its recognizable symbol, proportions, colors and lettering as faithfully as possible. Integrate it naturally as a small brand signature; do not redesign it, invent a replacement, or make it dominate the composition.":"No brand logo was supplied; do not invent one.";const ip=`Create a FINISHED premium Instagram carousel slide, vertical 4:5. ${referenceSystem} Slide role: ${s.role}. Exact headline to render legibly: "${s.title}". Exact supporting copy to render legibly: "${s.copy}". ${s.visualPrompt}. ${sceneRule} Business context: ${String(body.business||"")}. Requested style: ${String(body.tone||"editorial premium")}. ${visualStylePrompt?`MANDATORY SELECTED VISUAL STYLE: ${visualStylePrompt}`:""} ${humanDirection} ${personRule} The text is part of the final design: render it clearly, correctly spelled in Spanish, with strong hierarchy and highlighted keywords. Do not add invented claims, fake UI, fake logos or watermarks. Maintain visual continuity with the carousel while making this slide compositionally distinct.`;
   const refPaths=[...(logoPath?[logoPath]:[]),...(humanMode?personRefPaths:[])];const editRefs=await Promise.all(refPaths.map(async(path:string)=>{const d=await db.storage.from("scheduled-media").download(path);if(d.error||!d.data)throw new Error("No se pudo leer una imagen de referencia.");return {path,blob:d.data};}));const imageEndpoint=editRefs.length?"/images/edits":"/images/generations";
   let imageBody:BodyInit;
   if(editRefs.length){
    const form=new FormData();
    form.append("model",model);
    form.append("prompt",ip+" "+logoRule+" "+personRule);
    form.append("size","1024x1280");
    form.append("quality","medium");
    form.append("output_format","webp");
    editRefs.forEach((ref:any,refIndex:number)=>{
     const mime=ref.blob.type||"image/jpeg";const ext=mime==="image/jpeg"?"jpg":mime.split("/")[1]||"img";
     form.append("image[]",ref.blob,refIndex===0&&logoPath?"brand-logo."+ext:"person-reference-"+refIndex+"."+ext);
    });
    imageBody=form;
   }else{
    imageBody=JSON.stringify({model,prompt:ip+" "+logoRule,size:"1024x1280",quality:"medium",output_format:"webp"});
   }
   const headers:Record<string,string>={Authorization:"Bearer "+key};
   if(!editRefs.length)headers["Content-Type"]="application/json";
   let ir:Response;let ij:any;let irId:string|null=null;
   for(let attempt=0;;attempt++){
    ir=await fetch(OPENAI+imageEndpoint,{method:"POST",headers,body:imageBody});
    ij=await readProviderJson(ir,`La generación de la imagen ${i+1}`);irId=ir.headers.get("x-request-id");
    if(ir.status!==429&&ir.status!==503)break;
    if(attempt>=4)break;
    await sleep(retryDelayMs(ir,attempt));
   }
   await diag(db,{user_id:session.userId,stage:imageStage,ok:ir.ok,http_status:ir.status,model,request_id:irId,error_type:safeError(ij).type,error_code:safeError(ij).code,error_message:safeError(ij).message,details:{key_source:keySource,endpoint:editRefs.length?"images/edits":"images/generations",slide:i+1,logo_used:!!logoPath,human_mode:humanMode,person_refs:personRefPaths.length,param:safeError(ij).param}});
   if(!ir.ok)throw new Error(ij.error?.message||`Falló la generación de la imagen ${i+1}.`);
   const b64=ij.data?.[0]?.b64_json;if(!b64)throw new Error(`OpenAI no devolvió la imagen ${i+1}.`);
   const imageBytes=Uint8Array.from(atob(b64),ch=>ch.charCodeAt(0));
   const storagePath=`${session.userId}/creator-ai/${crypto.randomUUID()}-${i+1}.webp`;
   const uploaded=await db.storage.from("scheduled-media").upload(storagePath,imageBytes,{contentType:"image/webp",upsert:false});
   if(uploaded.error)throw new Error(`No se pudo guardar la placa ${i+1}: ${uploaded.error.message}`);
   const signed=await db.storage.from("scheduled-media").createSignedUrl(storagePath,86400);
   if(signed.error||!signed.data?.signedUrl)throw new Error(`No se pudo preparar la placa ${i+1}.`);
   generated.push({role:s.role,title:s.title,copy:s.copy,image:signed.data.signedUrl,storagePath});
  }
  return NextResponse.json({slides:generated,model});
 }catch(e:any){await diag(db,{user_id:session.userId,stage,ok:false,error_type:"local_exception",error_message:e.message||"unknown"});return NextResponse.json({error:e.message||"No se pudo generar el carrusel.",diagnosticStage:stage},{status:500})}
}