import {NextResponse} from "next/server";
import {getCustomerSession} from "../../../../../lib/auth";
import {supabaseAdmin} from "../../../../../lib/supabase-admin";
export const runtime="nodejs";export const maxDuration=300;const OPENAI="https://api.openai.com/v1";
async function generateHtml(key:string,system:string,input:any){const model=process.env.VYRAL_EBOOK_TEXT_MODEL||process.env.VYRAL_TEXT_MODEL||"gpt-5.6-sol";const r=await fetch(`${OPENAI}/responses`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:[{role:"system",content:[{type:"input_text",text:system}]},{role:"user",content:[{type:"input_text",text:JSON.stringify(input)}]}],max_output_tokens:30000})});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||"Error de IA");const text=(j.output||[]).flatMap((x:any)=>x.content||[]).filter((x:any)=>x.type==="output_text").map((x:any)=>x.text).join("");if(!text)throw new Error("La IA no devolvió HTML.");return text.replace(/^```html\s*/i,"").replace(/```\s*$/i,"").trim()}
const SYSTEM=`Sos VYRAL Landing Engine, especialista en páginas de venta premium EXCLUSIVAMENTE para ImpulTienda. Entregá SOLO un documento HTML completo desde <!DOCTYPE html> hasta </html>, sin markdown ni explicación.

REGLAS IMPULTIENDA: CTA con href="/checkout" o data-checkout. Preservá literalmente {{price}}, {{original_price}}, {{savings}} y {{currency}}. HTML/CSS/JS autocontenido y responsive, listo para pegar en ImpulTienda. No uses frameworks JS externos.

OFERTA: brief y plan son la fuente de avatar, dolores, transformación, promesa, contenido, tono y Style Bible. assets.main es el mockup principal. assets.bonuses contiene hasta 5 bonos opcionales: ignorá vacíos. assets.upsells son post-compra y NO aparecen en la landing principal. No inventes valores monetarios faltantes.

CONTRATO VISUAL: creá una landing específica para el producto con base de conversión sólida, jerarquía editorial premium, imágenes grandes y narrativa comercial clara. El HERO usa heroDesktop como fondo desktop y heroMobile como fondo móvil cuando existan, con overlays elegantes para legibilidad. El mockup principal mantiene presencia protagonista. Nunca deformes imágenes.

RESPONSIVE — REGLA CRÍTICA: CELULAR NO ES UN REDISEÑO. Desktop define la composición maestra. En móvil debe verse LA MISMA LANDING: mismo orden, mismos bloques, mismas relaciones visuales, misma jerarquía y lenguaje compositivo, solamente adaptados proporcionalmente al ancho. NO conviertas por defecto columnas en una pila vertical interminable. Cuando sea viable preservá 2 columnas, grids, filas de beneficios, tarjetas lado a lado y relaciones texto/imagen usando clamp(), minmax(), grid/flex, gaps y tipografía fluidos. Nunca ocultes contenido importante. heroMobile es la adaptación de la misma escena, no una dirección artística nueva.

ESTRUCTURA BASE OBLIGATORIA: 1 hero potente con promesa, producto, precio dinámico y CTA; 2 problema/dolores; 3 mecanismo/nueva forma de entender el problema; 4 contenido/beneficios; 5 bonos existentes con imágenes; 6 value stack; 7 SECCIÓN DE CHATS ESTILO WHATSAPP; 8 FAQ; 9 CTA final. Podés agregar secciones útiles pero no eliminar estas cuando haya datos.

CHATS WHATSAPP — OBLIGATORIOS SIEMPRE: generá 3 conversaciones breves, naturales y específicas del avatar/producto, visualmente reconocibles como WhatsApp mediante burbujas entrantes/salientes, horas discretas, nombres ficticios y estética de mensajería. Deben sonar humanas y representar situaciones plausibles relacionadas con el producto. No afirmes que son clientes verificados, compras reales, resultados comprobados ni evidencia real; no inventes cifras extraordinarias. Integralos como una sección visual premium y mantené las 3 tarjetas lado a lado cuando el ancho lo permita, escalándolas de forma inteligente en celular.

FAQ: 6–9 objeciones específicas. En móvil debe conservar la relación visual del desktop con controles táctiles y texto legible.

COPY: escribí para el avatar real y vendé mediante problema, mecanismo, transformación y contenido. No inventes estadísticas, estudios, garantías, escasez o urgencia. Devolvé exclusivamente HTML válido.`;
export async function POST(req:Request){const session=await getCustomerSession();if(!session)return NextResponse.json({error:"Iniciá sesión."},{status:401});const db=supabaseAdmin();const {data}=await db.auth.admin.getUserById(session.userId);const userPlan=String(data.user?.user_metadata?.plan||session.plan||"");if(userPlan!=="escala"&&userPlan!=="ai")return NextResponse.json({error:"Landing ImpulTienda requiere Escala o VYRAL AI."},{status:403});const key=process.env.VYRAL_CREATOR_PRODUCTION;if(!key)return NextResponse.json({error:"Falta configurar la API de OpenAI."},{status:503});try{const b=await req.json();if(!b.brief||!b.plan)return NextResponse.json({error:"Primero generá el producto principal y su estructura."},{status:400});const assets=b.assets||{};if(!String(assets.main||"").trim())return NextResponse.json({error:"Pegá la URL del mockup del producto principal."},{status:400});const input={brief:b.brief,plan:b.plan,assets:{main:assets.main,bonuses:Array.isArray(assets.bonuses)?assets.bonuses.filter((x:any)=>String(x?.url||"").trim()):[],upsells:Array.isArray(assets.upsells)?assets.upsells.filter((x:any)=>String(x?.url||"").trim()):[]},heroDesktop:String(b.heroDesktop||"").trim(),heroMobile:String(b.heroMobile||"").trim()};const html=await generateHtml(key,SYSTEM,input);return NextResponse.json({html})}catch(e:any){return NextResponse.json({error:e.message||"Error interno"},{status:500})}}
