import {NextResponse} from "next/server";
import {getCustomerSession} from "../../../../../lib/auth";
import {supabaseAdmin} from "../../../../../lib/supabase-admin";
export const runtime="nodejs";export const maxDuration=300;
const OPENAI="https://api.openai.com/v1";
async function generateHtml(key:string,system:string,input:any){const model=process.env.VYRAL_EBOOK_TEXT_MODEL||process.env.VYRAL_TEXT_MODEL||"gpt-5.6-sol";const r=await fetch(`${OPENAI}/responses`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:[{role:"system",content:[{type:"input_text",text:system}]},{role:"user",content:[{type:"input_text",text:JSON.stringify(input)}]}],max_output_tokens:30000})});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||"Error de IA");const text=(j.output||[]).flatMap((x:any)=>x.content||[]).filter((x:any)=>x.type==="output_text").map((x:any)=>x.text).join("");if(!text)throw new Error("La IA no devolvió HTML.");return text.replace(/^```html\s*/i,"").replace(/```\s*$/i,"").trim()}
const SYSTEM=`Sos VYRAL Landing Engine, especialista en páginas de venta premium EXCLUSIVAMENTE para ImpulTienda. Entregá SOLO un documento HTML completo desde <!DOCTYPE html> hasta </html>, sin markdown ni explicación.

REGLAS IMPULTIENDA: CTA de compra con href="/checkout" o data-checkout. Preservá literalmente {{price}}, {{original_price}}, {{savings}} y {{currency}}. HTML/CSS/JS autocontenido y responsive, listo para pegar en ImpulTienda. No uses frameworks JS externos.

OFERTA: brief y plan son la fuente de avatar, dolores, transformación, promesa, contenido, tono y Style Bible. assets.main es el mockup principal. assets.bonuses contiene hasta 5 bonos opcionales: ignorá slots vacíos. assets.upsells contiene hasta 3 upsells opcionales pero son post-compra y NO deben aparecer en la landing principal. Cada asset puede incluir name,url,value,description. No inventes valores faltantes.

DISEÑO: creá una landing específica para el producto, no una plantilla genérica. Jerarquía editorial premium, imágenes grandes, narrativa comercial clara, CTA y value stack cuando los datos lo permitan. Desktop y celular deben diseñarse intencionalmente; no apiles mecánicamente toda la composición móvil. FAQ especialmente legible y táctil en celular. Si heroDesktop existe usalo en desktop; si heroMobile existe usalo en el media query móvil. Si falta alguno, resolvé el hero con el mockup principal sin inventar URLs. Nunca deformes imágenes.

ESTRUCTURA ADAPTABLE: hero; problema; mecanismo; contenido/beneficios; bonos existentes; value stack; prueba social solo cuando exista evidencia real suministrada; FAQ; CTA final. No inventes testimonios, identidades de clientes, resultados, estadísticas, garantías, escasez ni urgencia. Si no hay testimonios reales, podés usar situaciones o conversaciones hipotéticas únicamente si quedan presentadas como ejemplos, no como clientes reales.

COPY: escribí para el avatar real del brief y vendé mediante claridad del problema, mecanismo, transformación y contenido. FAQ debe responder objeciones reales del producto y del acceso digital. Devolvé exclusivamente HTML válido.`;
export async function POST(req:Request){const session=await getCustomerSession();if(!session)return NextResponse.json({error:"Iniciá sesión."},{status:401});const db=supabaseAdmin();const {data}=await db.auth.admin.getUserById(session.userId);const userPlan=String(data.user?.user_metadata?.plan||session.plan||"");if(userPlan!=="escala"&&userPlan!=="ai")return NextResponse.json({error:"Landing ImpulTienda requiere Escala o VYRAL AI."},{status:403});const key=process.env.VYRAL_CREATOR_PRODUCTION;if(!key)return NextResponse.json({error:"Falta configurar la API de OpenAI."},{status:503});try{const b=await req.json();if(!b.brief||!b.plan)return NextResponse.json({error:"Primero generá el producto principal y su estructura."},{status:400});const assets=b.assets||{};if(!String(assets.main||"").trim())return NextResponse.json({error:"Pegá la URL del mockup del producto principal."},{status:400});const input={brief:b.brief,plan:b.plan,assets:{main:assets.main,bonuses:Array.isArray(assets.bonuses)?assets.bonuses.filter((x:any)=>String(x?.url||"").trim()):[],upsells:Array.isArray(assets.upsells)?assets.upsells.filter((x:any)=>String(x?.url||"").trim()):[]},heroDesktop:String(b.heroDesktop||"").trim(),heroMobile:String(b.heroMobile||"").trim()};const html=await generateHtml(key,SYSTEM,input);return NextResponse.json({html})}catch(e:any){return NextResponse.json({error:e.message||"Error interno"},{status:500})}}
