"use client";
import {useEffect,useState} from "react";
import Link from "next/link";\nimport CreatorReelsStudio from "./CreatorReelsStudio";
type Slide={title:string;copy:string;role:string;image?:string;storagePath?:string};
export default function CreatorAIStudio({enabled,reelsEnabled}:{enabled:boolean;reelsEnabled:boolean}){
 const [mode,setMode]=useState<"images"|"reels">("images");\n const [business,setBusiness]=useState(""); const [offer,setOffer]=useState(""); const [audience,setAudience]=useState(""); const [tone,setTone]=useState("animado premium"); const [cta,setCta]=useState("Escribí INFO"); const [goal,setGoal]=useState("ventas"); const [count,setCount]=useState(6); const [slides,setSlides]=useState<Slide[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [elapsed,setElapsed]=useState(0); const [logo,setLogo]=useState("");
 useEffect(()=>{if(!loading){setElapsed(0);return}const id=setInterval(()=>setElapsed(v=>v+1),1000);return()=>clearInterval(id)},[loading]);
 const eta=count===3?"20–50 s":count===5?"30–70 s":count===6?"35–85 s":"40–100 s";
 function pickLogo(file?:File){if(!file){setLogo("");return}if(!file.type.startsWith("image/"))return setError("El logo debe ser una imagen.");if(file.size>4*1024*1024)return setError("El logo puede pesar hasta 4 MB.");const reader=new FileReader();reader.onload=()=>{setLogo(String(reader.result||""));setError("")};reader.readAsDataURL(file)}
 async function generate(){setLoading(true);setElapsed(0);setError("");try{const r=await fetch("/api/creator-ai/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({business,offer,audience,tone,cta,goal,count,logo})});const j=await r.json();if(!r.ok)throw new Error(j.error||"No se pudo generar");setSlides(j.slides||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 function useForPublishing(){
  try{
   const ready=slides.filter(s=>s.image&&s.storagePath);
   if(ready.length<2){setError("El carrusel todavía no está listo para publicar.");return}
   const payload={version:2,createdAt:Date.now(),slides:ready.map((s,i)=>({index:i,title:s.title,copy:s.copy,role:s.role,image:s.image,storagePath:s.storagePath})),caption:[slides.map(s=>s.title).filter(Boolean).join(" · "),cta].filter(Boolean).join("\n\n"),business,offer,audience,goal,cta};
   sessionStorage.setItem("vyral:creator-ai-publication",JSON.stringify(payload));
   window.location.href="/?section=publish&source=creator-ai";
  }catch(e:any){setError(e?.name==="QuotaExceededError"?"No hay espacio temporal suficiente en el navegador. Regenerá el carrusel y volvé a intentar.":"No se pudo preparar el carrusel para Publicar.")}
 }
 async function downloadSlide(s:Slide,i:number){
  if(!s.image)return;
  try{const r=await fetch(s.image);if(!r.ok)throw new Error();const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`vyral-placa-${i+1}.webp`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch{window.open(s.image,"_blank")}
 }
 async function regen(i:number){setLoading(true);setError("");try{const r=await fetch("/api/creator-ai/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({business,offer,audience,tone,cta,goal,count:1,slide:slides[i],slideIndex:i,total:slides.length,logo})});const j=await r.json();if(!r.ok)throw new Error(j.error||"No se pudo regenerar");setSlides(s=>s.map((x,n)=>n===i?j.slides[0]:x))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 return <main className="cai"><header><Link href="/">← Panel</Link><b>VYRAL <i>CREATOR IA</i></b><span>ESCALA · AI</span></header>
 <section className="caiHero"><small>CREATOR VIRAL · GENERATIVE STUDIO</small><h1>De una idea a un carrusel que <em>vende.</em></h1><p>VYRAL crea la estrategia, el storytelling, las placas visuales y el CTA con IA.</p></section>
 {!enabled?<section className="caiLocked"><b>✦ EXCLUSIVO ESCALA</b><h2>Creator IA está incluido en Escala.</h2><p>La generación está bloqueada también en servidor.</p><Link href="/mi-plan#upgrade">Pasar a Escala →</Link></section>:
 <><section className="caiGrid"><div className="caiForm"><h2>Brand Brain</h2><label>Negocio / producto<textarea value={business} onChange={e=>setBusiness(e.target.value)} placeholder="Qué vendés, beneficios, diferenciador..."/></label><label>Oferta<input value={offer} onChange={e=>setOffer(e.target.value)} placeholder="Precio, promo o propuesta"/></label><label>Público<input value={audience} onChange={e=>setAudience(e.target.value)} placeholder="A quién queremos convencer"/></label><div className="caiTwo"><label>Objetivo<select value={goal} onChange={e=>setGoal(e.target.value)}><option value="ventas">Vender</option><option value="mensajes">Conseguir mensajes</option><option value="seguidores">Ganar seguidores</option><option value="trafico">Llevar tráfico</option><option value="educar">Educar</option></select></label><label>Placas<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[3,5,6,7].map(n=><option key={n}>{n}</option>)}</select></label></div><label>Estilo visual<input value={tone} onChange={e=>setTone(e.target.value)} placeholder="Animado premium, cómic moderno..."/></label><label>CTA<input value={cta} onChange={e=>setCta(e.target.value)} /></label><label>Logo de marca <small style={{opacity:.6}}>· opcional</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>pickLogo(e.target.files?.[0])}/>{logo&&<span style={{display:"flex",alignItems:"center",gap:10,marginTop:8}}><img src={logo} alt="Logo cargado" style={{width:54,height:54,objectFit:"contain",borderRadius:10,background:"#fff",padding:5}}/><button type="button" onClick={()=>setLogo("")} style={{padding:"7px 10px"}}>Quitar logo</button></span>}</label><button disabled={loading||!business.trim()} onClick={generate}>{loading?`Creando carrusel · ${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,"0")}`:"✦ Generar carrusel"}</button><p style={{fontSize:12,opacity:.62,marginTop:8}}>{loading?`Generando las imágenes en paralelo. Tiempo estimado: ${eta}.`:`Tiempo estimado para ${count} placas: ${eta}.`}</p>{error&&<p className="caiError">{error}</p>}</div>
 <aside><small>ESTRUCTURA INTELIGENTE</small><h3>Hook → tensión → solución → prueba → oferta → CTA</h3><p>No repite una plantilla: adapta la narrativa al negocio y mantiene coherencia visual entre placas.</p></aside></section>
 {slides.length>0&&<section className="caiResults"><div><small>CARRUSEL GENERADO</small><h2>{slides.length} placas listas</h2></div><div className="caiSlides">{slides.map((s,i)=><article key={i}><div className="caiImg">{s.image?<img src={s.image} alt={s.title}/>:<span>Generando visual…</span>}</div><small>{String(i+1).padStart(2,"0")} · {s.role}</small><input value={s.title} onChange={e=>setSlides(a=>a.map((x,n)=>n===i?{...x,title:e.target.value}:x))}/><textarea value={s.copy} onChange={e=>setSlides(a=>a.map((x,n)=>n===i?{...x,copy:e.target.value}:x))}/><div style={{display:"flex",gap:8}}><button onClick={()=>regen(i)} disabled={loading}>↻ Regenerar placa</button><button type="button" onClick={()=>downloadSlide(s,i)} disabled={!s.image}>↓ Descargar</button></div></article>)}</div><div style={{marginTop:24,display:"flex",gap:12,alignItems:"center",flexWrap:"wrap"}}><button type="button" onClick={useForPublishing} style={{padding:"14px 20px",borderRadius:12,background:"#bffdf8",color:"#06100f",fontWeight:800,border:0,cursor:"pointer"}}>Usar imágenes para publicación →</button><span style={{fontSize:12,opacity:.6}}>Prepará la publicación, descripción, cuentas y automatización desde Publicar.</span></div></section>}</>}
 </main>
}
