"use client";
import {useMemo,useState} from "react";
type PagePlan={number:number;type:string;section:string;title:string;subtitle?:string;body:string;objective:string;visual:string;visualFunction:string;composition:string;textVisualRatio:string;imagePrompt:string;image?:string;storagePath?:string;status?:"pending"|"generating"|"done"|"error";error?:string};
export default function EbookStudio(){
 const [brief,setBrief]=useState("");const [requestedPages,setRequestedPages]=useState(15);const [plan,setPlan]=useState<any>(null);const [pages,setPages]=useState<PagePlan[]>([]);const [planning,setPlanning]=useState(false);const [running,setRunning]=useState(false);const [exporting,setExporting]=useState(false);const [error,setError]=useState("");const [current,setCurrent]=useState(0);const [pdfUrl,setPdfUrl]=useState("");
 const done=useMemo(()=>pages.filter(p=>p.status==="done").length,[pages]);const allDone=pages.length>0&&done===pages.length;
 async function createPlan(){setPlanning(true);setError("");setPdfUrl("");setPlan(null);setPages([]);try{const r=await fetch("/api/creator-ai/ebook/plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({brief,requestedPages})});const raw=await r.text();let j:any;try{j=JSON.parse(raw)}catch{throw new Error("El servidor no devolvió un plan válido.")}if(!r.ok)throw new Error(j.error||"No se pudo planificar el ebook.");setPlan(j);setPages((j.pages||[]).map((p:PagePlan)=>({...p,status:"pending"})));}catch(e:any){setError(e.message)}finally{setPlanning(false)}}
 function pagePrompt(p:PagePlan){const s=plan?.styleBible||{};return `EBOOK: ${plan?.title||""}. STYLE BIBLE BLOQUEADA: concepto ${s.concept||"editorial premium"}; paleta ${s.primary||""} ${s.secondary||""} ${s.accent||""}; fondo ${s.background||""}; texto ${s.text||""}; tipografía display ${s.displayFont||"editorial"}; cuerpo ${s.bodyFont||"legible"}; fotografía ${s.photography||""}; diagramas ${s.diagrams||""}; composición ${s.composition||""}. Mantener el mismo ADN visual y variar el layout según el contenido. PÁGINA ${p.number}. Tipo: ${p.type}. Sección: ${p.section}. TÍTULO EXACTO: ${p.title}. SUBTÍTULO EXACTO: ${p.subtitle||""}. CUERPO EXACTO: ${p.body||""}. Objetivo: ${p.objective}. Visual: ${p.visual}. Función visual: ${p.visualFunction}. Composición: ${p.composition}. Relación texto/visual: ${p.textVisualRatio}. ${p.imagePrompt}`}
 async function generatePage(index:number){const p=pages[index];if(!p)return null;setCurrent(index+1);setPages(x=>x.map((q,i)=>i===index?{...q,status:"generating",error:""}:q));try{const r=await fetch("/api/creator-ai/ebook/image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({page:p.number,total:pages.length,prompt:pagePrompt(p)})});const raw=await r.text();let j:any;try{j=JSON.parse(raw)}catch{throw new Error(`Respuesta inválida al generar página ${p.number}.`)}if(!r.ok)throw new Error(j.error||`No se pudo generar página ${p.number}.`);setPages(x=>x.map((q,i)=>i===index?{...q,image:j.image,storagePath:j.storagePath,status:"done"}:q));return j;}catch(e:any){setPages(x=>x.map((q,i)=>i===index?{...q,status:"error",error:e.message}:q));return null}}
 async function generateAll(){if(!pages.length||running)return;setRunning(true);setError("");setPdfUrl("");try{for(let i=0;i<pages.length;i++){if(pages[i]?.status==="done")continue;await generatePage(i)}}finally{setRunning(false);setCurrent(0)}}
 async function regen(i:number){if(running)return;setRunning(true);setPdfUrl("");try{await generatePage(i)}finally{setRunning(false);setCurrent(0)}}
 async function exportPdf(){const ready=pages.filter(p=>p.status==="done"&&p.storagePath);if(ready.length!==pages.length){setError("Primero tienen que estar listas todas las páginas.");return}setExporting(true);setError("");try{const r=await fetch("/api/creator-ai/ebook/pdf",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:plan?.title||"ebook",storagePaths:ready.map(p=>p.storagePath)})});const j=await r.json();if(!r.ok)throw new Error(j.error||"No se pudo crear el PDF.");setPdfUrl(j.url);window.open(j.url,"_blank")}catch(e:any){setError(e.message)}finally{setExporting(false)}}
 async function downloadImage(p:PagePlan){if(!p.image)return;try{const r=await fetch(p.image);const b=await r.blob();const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=`${String(p.number).padStart(3,"0")}_${p.type||"pagina"}.webp`;a.click();URL.revokeObjectURL(u)}catch{window.open(p.image,"_blank")}}
 return <section style={{maxWidth:1400,margin:"0 auto",padding:"24px 18px 80px"}}>
  <div style={{border:"1px solid #252535",borderRadius:24,padding:24,background:"linear-gradient(135deg,#11111b,#0b0b12)"}}><small style={{color:"#9b87ff",fontWeight:800}}>VYRAL · EBOOK ENGINE · CALIDAD MEDIA</small><h2 style={{fontSize:"clamp(28px,4vw,52px)",margin:"8px 0"}}>Pegá una sola vez. VYRAL arma el ebook completo.</h2><p style={{color:"#aaa",maxWidth:850}}>Un único brief. Blueprint, dirección de arte y una generación independiente por página. Calidad de imagen fija en Medium para equilibrar resultado, velocidad y costo. Al finalizar, VYRAL une las páginas sin remaquetarlas y entrega el PDF.</p>
   <textarea value={brief} onChange={e=>setBrief(e.target.value)} placeholder={"Pegá acá toda la información junta:\nTítulo, nicho, avatar, problema, transformación, subtemas, tono, marca, estética, colores, referencias y observaciones."} style={{width:"100%",minHeight:240,marginTop:18,borderRadius:16,padding:18,background:"#09090f",color:"white",border:"1px solid #303044",fontSize:15,lineHeight:1.55}}/>
   <div style={{display:"flex",gap:12,alignItems:"end",flexWrap:"wrap",marginTop:14}}><label style={{display:"grid",gap:6}}><span style={{fontSize:12,color:"#aaa"}}>PÁGINAS</span><select value={requestedPages} onChange={e=>setRequestedPages(Number(e.target.value))} style={{background:"#09090f",color:"white",border:"1px solid #303044",borderRadius:12,padding:"12px 14px"}}>{Array.from({length:41},(_,i)=>i+5).map(n=><option key={n}>{n}</option>)}</select></label><button onClick={createPlan} disabled={planning||brief.trim().length<20} style={{border:0,borderRadius:14,padding:"13px 22px",fontWeight:900}}>{planning?"Creando Blueprint…":"✦ Crear estructura"}</button>{plan&&<button onClick={generateAll} disabled={running} style={{border:0,borderRadius:14,padding:"13px 22px",fontWeight:900,background:"#7c5cff",color:"white"}}>{running?`Generando ${current||done+1}/${pages.length}…`:`Generar ${pages.length} páginas`}</button>}{allDone&&<button onClick={exportPdf} disabled={exporting||running} style={{border:0,borderRadius:14,padding:"13px 22px",fontWeight:900,background:"#fff",color:"#09090f"}}>{exporting?"Armando PDF…":"↓ Descargar ebook PDF"}</button>}{pdfUrl&&<a href={pdfUrl} target="_blank" rel="noreferrer" style={{padding:"12px 16px",color:"#b9ffbf",fontWeight:800}}>PDF listo ✓</a>}</div>{error&&<p style={{color:"#ff7474",fontWeight:700}}>{error}</p>}
  </div>
  {plan&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12,margin:"18px 0"}}><div style={{padding:16,border:"1px solid #252535",borderRadius:16}}><small>PROMESA</small><b style={{display:"block",marginTop:6}}>{plan.promise}</b></div><div style={{padding:16,border:"1px solid #252535",borderRadius:16}}><small>TRANSFORMACIÓN</small><b style={{display:"block",marginTop:6}}>{plan.transformation}</b></div><div style={{padding:16,border:"1px solid #252535",borderRadius:16}}><small>PROGRESO</small><b style={{display:"block",marginTop:6}}>{done}/{pages.length} páginas listas</b></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(240px,1fr))",gap:14}}>{pages.map((p,i)=><article key={p.number} style={{border:"1px solid #252535",borderRadius:18,overflow:"hidden",background:"#101018"}}>{p.image?<img src={p.image} alt={p.title} style={{width:"100%",aspectRatio:"4/5",objectFit:"contain",background:"#07070b"}}/>:<div style={{aspectRatio:"4/5",display:"grid",placeItems:"center",padding:20,textAlign:"center",background:"#09090f"}}><div><b style={{fontSize:36,opacity:.3}}>{String(p.number).padStart(2,"0")}</b><h3>{p.title}</h3><small style={{color:p.status==="error"?"#ff7474":"#999"}}>{p.status==="generating"?"GENERANDO…":p.status==="error"?p.error:"EN COLA"}</small></div></div>}<div style={{padding:14}}><small style={{color:"#8d7aff"}}>PÁGINA {p.number} · {p.type}</small><b style={{display:"block",margin:"5px 0 10px"}}>{p.title}</b><div style={{display:"flex",gap:8}}><button disabled={running} onClick={()=>regen(i)} style={{padding:"8px 10px",borderRadius:10,border:"1px solid #333",background:"#181824",color:"white"}}>{p.image?"Regenerar":"Generar"}</button>{p.image&&<button onClick={()=>downloadImage(p)} style={{padding:"8px 10px",borderRadius:10,border:"1px solid #333",background:"#181824",color:"white"}}>Descargar</button>}</div></div></article>)}</div></>}
 </section>
}
