import {NextResponse} from "next/server";
import {getCustomerSession} from "../../../../../lib/auth";
import {supabaseAdmin} from "../../../../../lib/supabase-admin";
export const runtime="nodejs";export const maxDuration=300;
const OPENAI="https://api.openai.com/v1";
const EBOOK_RULES=`VYRAL EBOOK MASTER BRAIN — INTERNAL PRODUCTION CONTRACT. These rules are permanent system behavior. NEVER require the end user to type, repeat, know or remember them. The user's only responsibility is describing their product/ebook.

ROLE: act simultaneously as world-class subject-matter author, premium editorial director, researcher, ebook designer, art director and image-first production director. Produce a paid-product level ebook, not generic infoproduct copy.

SOURCE PRIORITY: user-supplied product data is primary. Sales-page screenshots/references, when supplied, are mandatory secondary evidence: extract promises, transformation, pains, benefits, methods, frameworks, objections, buyer expectations and visual identity. Incorporate coherent additions; flag material contradictions in the Blueprint instead of choosing arbitrarily. Never invent facts that materially change the product, fake studies, statistics, sources, experts, testimonials or real-world results.

PEDAGOGY: build a promise→understanding→learning→action→chapter→example→exercise/tool→visual map so no promise is uncovered. Every important concept should answer why it works, how to do it, what to do now, what can fail/how to fix it, and how the reader knows it was done correctly. Depth comes from mechanisms, procedures, diagnosis, examples, comparisons, decisions, exceptions, implementation and verification—not repetition. Adapt language, examples, complexity, budget/tools and assumptions to the avatar. Chapters must form one progressive system and create concrete advancement. Use actionable exercises/checklists/scripts/frameworks only when genuinely useful.

EDITORIAL/VISUAL: every content page needs a meaningful visual component unless deliberate negative space is editorially justified. Visuals must teach: explain, demonstrate, compare, contextualize, simplify, exemplify, show process/consequence, aid memory or decisions. Prefer teaching over decoration. Dynamically choose photography, conceptual illustration, infographic, diagram, flowchart, timeline, chart, visual table, mockup, framework, mind map, process, before/after, correct/incorrect, interface representation, checklist, matrix, decision tree, data composition, contextual scene or visual metaphor according to the lesson. Vary layouts and text/visual density intentionally; do not repeat a rigid title/text/image template.

STYLE BIBLE: derive a specific identity from niche, avatar, transformation, brand and references. Lock 2–4 principal colors with exact HEX, text/background colors, display/body typography categories and weights, hierarchy, margins/grid/alignment, photographic/illustrative treatment, diagram language, iconography, geometry, borders, shadows, lighting and title treatment. Coherence does NOT mean identical layouts. Cover establishes the universe. Include a real TOC. Choose a representative interior pilot page to validate the visual DNA.

IMAGE-FIRST CONTRACT: ONE ebook page = ONE independent master image = ONE PDF page. Each real image-generation request must request EXACTLY ONE complete final page. Never request multiple pages in one image; never grid, collage, mosaic, contact sheet, book spread, thumbnails or crop pages from a multi-page composition. The per-page image prompt describes ONLY the current page. Every page is flat, frontal, rectangular, vertical, finished and readable. Main generation should directly produce the complete editorial page with final text + hierarchy + relevant visual + composition. Do not pre-generate a mass asset library. If a concrete page's generated text fails, that page may exceptionally use a precision composition correction; this is not permission for mass asset production.

CONTENT/QUALITY: exact visible text for every page must be planned. No placeholders. No aggressive resale CTA: this is the purchased product. Maintain natural expert voice, no empty motivation, no obvious AI patterns. For sensitive health/money/legal/security topics, add responsible precision and limitations. If content cannot fit legibly, restructure across pages rather than shrinking text into illegibility. Respect the requested page count while prioritizing complete coverage within it.

PRODUCTION PHASES: research/analysis → Blueprint Editorial → complete visual map → deep master copy → representative pilot → page-by-page final production → verification/correction → consolidation → final audit. The Blueprint includes promise, avatar, starting point, transformation, architecture, chapters, practical resources, promise coverage and visual direction. The visual map covers EVERY page, not just the first pages, with objective, content, visual, what it shows, visual function, composition and text/visual ratio.

FINAL DELIVERY RULES: all master pages must exist and be verified before final PDF. Assemble exactly one full master image per PDF page, ordered, with no re-layout, reconstructed text, moved elements, new margins, crop or composition changes. The PDF is only the final container; master page images are the visual originals. Audit completeness, duplicates, order, rotation/cropping, proportion, semantic correspondence, text fidelity, visual coherence and PDF/image identity.

Generate between 5 and 45 pages according to requestedPages. If requestedPages is provided, return EXACTLY that many planned pages. Respond ONLY valid JSON, no markdown.`;
function extractJson(s:string){const a=s.indexOf("{");const b=s.lastIndexOf("}");if(a<0||b<a)throw new Error("La IA no devolvió un plan válido.");return JSON.parse(s.slice(a,b+1))}
export async function POST(req:Request){
 const session=await getCustomerSession();if(!session)return NextResponse.json({error:"Iniciá sesión."},{status:401});
 const db=supabaseAdmin();const {data}=await db.auth.admin.getUserById(session.userId);const plan=String(data.user?.user_metadata?.plan||session.plan||"");if(plan!=="escala"&&plan!=="ai")return NextResponse.json({error:"Ebooks IA está disponible en Escala y VYRAL AI."},{status:403});
 const key=process.env.VYRAL_CREATOR_PRODUCTION;if(!key)return NextResponse.json({error:"Falta configurar la API de OpenAI."},{status:503});
 try{
  const body=await req.json();const brief=String(body.brief||"").trim();const requestedPages=Math.min(45,Math.max(5,Number(body.requestedPages)||15));if(brief.length<20)return NextResponse.json({error:"Pegá la información del ebook en un solo texto."},{status:400});
  const schema=`Devolvé exactamente este objeto: {"title":"...","promise":"...","avatar":"...","transformation":"...","styleBible":{"concept":"...","primary":"#...","secondary":"#...","accent":"#...","background":"#...","text":"#...","displayFont":"...","bodyFont":"...","photography":"...","diagrams":"...","composition":"..."},"pilotPage":3,"pages":[{"number":1,"type":"cover|toc|content|exercise|closing","section":"...","title":"texto exacto visible","subtitle":"texto exacto visible o vacío","body":"texto exacto visible; usar saltos de línea cuando ayuden","objective":"...","visual":"...","visualFunction":"...","composition":"...","textVisualRatio":"...","imagePrompt":"dirección de arte autocontenida EXCLUSIVAMENTE para esta página final"}]}. pages debe contener EXACTAMENTE ${requestedPages} objetos numerados 1..${requestedPages}. Página 1 portada, página 2 índice y pilotPage una página interior representativa. No pongas instrucciones operativas internas dentro del contenido visible del ebook.`;
  const textModel=process.env.VYRAL_EBOOK_TEXT_MODEL||process.env.VYRAL_TEXT_MODEL||"gpt-5.6-sol";
  const r=await fetch(`${OPENAI}/responses`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:textModel,input:[{role:"system",content:[{type:"input_text",text:EBOOK_RULES}]},{role:"user",content:[{type:"input_text",text:`INFORMACIÓN DEL PRODUCTO/ebook PROPORCIONADA POR EL USUARIO:\n${brief}\n\nCANTIDAD DE PÁGINAS ELEGIDA EN VYRAL: ${requestedPages}\n\n${schema}`}]}],max_output_tokens:30000})});
  const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||"No se pudo planificar el ebook.");const text=(j.output||[]).flatMap((x:any)=>x.content||[]).filter((x:any)=>x.type==="output_text").map((x:any)=>x.text).join("");const out=extractJson(text);if(!Array.isArray(out.pages)||out.pages.length!==requestedPages)throw new Error("El plan no devolvió la cantidad exacta de páginas.");return NextResponse.json(out);
 }catch(e:any){return NextResponse.json({error:e.message||"No se pudo planificar el ebook."},{status:500})}
}
