import {NextResponse} from "next/server";
import {getCustomerSession} from "../../../../../lib/auth";
import {supabaseAdmin} from "../../../../../lib/supabase-admin";
export const runtime="nodejs";export const maxDuration=300;
const OPENAI="https://api.openai.com/v1";
const EBOOK_RULES=`Actuá como autor experto, director editorial, investigador, diseñador editorial y director de arte. Tu misión es planificar un ebook premium image-first terminado. El input del usuario es la fuente principal. Debés convertir un único brief libre en un Blueprint Editorial, Style Bible y mapa completo de páginas. Reglas innegociables: una página del ebook = una imagen maestra independiente; una llamada real al generador = exactamente una página; nunca grid, collage, mosaico, spread ni varias páginas en una imagen. Cada página debe ser vertical, plana, frontal y editorial. Todas las páginas de contenido deben tener un componente visual significativo que enseñe, no decore. Mantené coherencia de paleta, tipografías, jerarquías, iluminación, estilo fotográfico/ilustrativo, iconografía, geometría, bordes, sombras, márgenes, numeración y branding, pero variá deliberadamente los layouts y el ritmo editorial. Elegí dinámicamente fotografía, ilustración, infografía, diagrama, flowchart, timeline, tabla visual, framework, mapa mental, proceso, antes/después, correcto/incorrecto, checklist, matriz, árbol de decisión, escena o metáfora según qué enseñe mejor. La portada establece el universo visual. Incluí índice. Profundidad sin relleno: explicar por qué, cómo, qué hacer ahora, qué puede salir mal y cómo verificar si está bien. Cada capítulo debe avanzar la transformación y cerrar con lo esencial + una acción útil cuando corresponda. No inventes estudios, estadísticas, testimonios, fuentes o resultados reales. Si el contenido no entra legible, dividilo en más páginas. El texto visible de cada página debe quedar definido exactamente. La página piloto representativa debe fijar el ADN visual reutilizable. El PDF final se ensamblará después, con una imagen completa por página y sin remaquetación. Generá entre 5 y 45 páginas según requestedPages; si requestedPages está definido, respetalo salvo imposibilidad editorial extrema. Respondé SOLO JSON válido, sin markdown.`;
function extractJson(s:string){const a=s.indexOf("{");const b=s.lastIndexOf("}");if(a<0||b<a)throw new Error("La IA no devolvió un plan válido.");return JSON.parse(s.slice(a,b+1))}
export async function POST(req:Request){
 const session=await getCustomerSession();if(!session)return NextResponse.json({error:"Iniciá sesión."},{status:401});
 const db=supabaseAdmin();const {data}=await db.auth.admin.getUserById(session.userId);const plan=String(data.user?.user_metadata?.plan||session.plan||"");if(plan!=="escala"&&plan!=="ai")return NextResponse.json({error:"Ebooks IA está disponible en Escala y VYRAL AI."},{status:403});
 const key=process.env.VYRAL_CREATOR_PRODUCTION;if(!key)return NextResponse.json({error:"Falta configurar la API de OpenAI."},{status:503});
 try{
  const body=await req.json();const brief=String(body.brief||"").trim();const requestedPages=Math.min(45,Math.max(5,Number(body.requestedPages)||15));if(brief.length<20)return NextResponse.json({error:"Pegá la información del ebook en un solo texto."},{status:400});
  const schema=`Devolvé exactamente este objeto: {"title":"...","promise":"...","avatar":"...","transformation":"...","styleBible":{"concept":"...","primary":"#...","secondary":"#...","accent":"#...","background":"#...","text":"#...","displayFont":"...","bodyFont":"...","photography":"...","diagrams":"...","composition":"..."},"pilotPage":3,"pages":[{"number":1,"type":"cover|toc|content|exercise|closing","section":"...","title":"texto exacto visible","subtitle":"texto exacto visible o vacío","body":"texto exacto visible; usar saltos de línea cuando ayuden","objective":"...","visual":"...","visualFunction":"...","composition":"...","textVisualRatio":"...","imagePrompt":"prompt autocontenido para generar SOLAMENTE ESTA página editorial final, sin mencionar otras páginas, grid, collage ni ebook completo"}]}. pages debe contener EXACTAMENTE ${requestedPages} objetos, numerados 1..${requestedPages}. La página 1 es portada, la 2 índice y pilotPage debe apuntar a una página interior representativa.`;
  const r=await fetch(`${OPENAI}/responses`,{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-sol",input:[{role:"system",content:[{type:"input_text",text:EBOOK_RULES}]},{role:"user",content:[{type:"input_text",text:`INPUT ÚNICO DEL USUARIO:\n${brief}\n\nCANTIDAD SOLICITADA: ${requestedPages}\n\n${schema}`}]}],max_output_tokens:30000})});
  const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||"No se pudo planificar el ebook.");const text=(j.output||[]).flatMap((x:any)=>x.content||[]).filter((x:any)=>x.type==="output_text").map((x:any)=>x.text).join("");const out=extractJson(text);if(!Array.isArray(out.pages)||out.pages.length!==requestedPages)throw new Error("El plan no devolvió la cantidad exacta de páginas.");return NextResponse.json(out);
 }catch(e:any){return NextResponse.json({error:e.message||"No se pudo planificar el ebook."},{status:500})}
}
