"use client";
import VyralSidebar from "../ui/VyralSidebar";
import "../ui/dashboard.css";
import "../ui/dashboard-addons.css";
import { FormEvent, MouseEvent, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";

type Handoff={id:string;contact_id:string;contact_username?:string|null;reason?:string|null;lead_score:number;last_message?:string|null;status:string;stage?:string;priority?:string;assigned_to?:string|null;notes?:string|null;unread?:boolean;updated_at?:string;needs_human?:boolean;ai_paused?:boolean};
type Message={id:string;body:string;direction:"in"|"out";sender_type:"contact"|"ai"|"human"|"system";created_at?:string;attachment_type?:string|null;attachment_url?:string|null};
type Stats={total:number;hot:number;unread:number;human:number};type Analytics={conversations:number;interested:number;hot:number;whatsapp:number;goals:number;human:number;conversion:number;series?:number[]};
const stages:Record<string,string>={new:"Nuevo",contacted:"Contactado",qualified:"Calificado",won:"Ganado",lost:"Perdido"};
const fallbackSeries=[8,18,13,31,24,46,38,61,51,76,68,91];

export default function Inbox(){
 const searchParams=useSearchParams();
 const automation=searchParams.get("automation")||"";
 const[handoffs,setHandoffs]=useState<Handoff[]>([]),[selected,setSelected]=useState<Handoff|null>(null),[messages,setMessages]=useState<Message[]>([]),[message,setMessage]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState("open"),[sending,setSending]=useState(false),[stats,setStats]=useState<Stats>({total:0,hot:0,unread:0,human:0}),[notes,setNotes]=useState(""),[analytics,setAnalytics]=useState<Analytics>({conversations:0,interested:0,hot:0,whatsapp:0,goals:0,human:0,conversion:0,series:[]}),[days,setDays]=useState(30),[hover,setHover]=useState<{x:number;y:number;value:number;index:number}|null>(null);
 async function loadAnalytics(period=days){const r=await fetch("/api/inbox?analytics=1&days="+period+(automation?"&automation="+encodeURIComponent(automation):""),{cache:"no-store"});if(r.ok)setAnalytics(await r.json())}
 async function load(){const r=await fetch("/api/inbox"+(automation?"?automation="+encodeURIComponent(automation):""),{cache:"no-store"});if(!r.ok)return;const d=await r.json();setHandoffs(d.handoffs||[]);setStats(d.stats||{total:0,hot:0,unread:0,human:0})}
 async function thread(h:Handoff){setSelected(h);setNotes(h.notes||"");const r=await fetch("/api/inbox?contact="+encodeURIComponent(h.contact_id)+(automation?"&automation="+encodeURIComponent(automation):""),{cache:"no-store"});if(r.ok){const d=await r.json();setMessages(d.messages||[])}}
 useEffect(()=>{void load();void loadAnalytics();const t=window.setInterval(()=>void load(),8000);return()=>window.clearInterval(t)},[automation]);
 const visible=useMemo(()=>handoffs.filter(h=>{const q=search.toLowerCase();const matches=!q||String(h.contact_username||h.contact_id).toLowerCase().includes(q)||String(h.last_message||"").toLowerCase().includes(q);const f=filter==="all"?true:filter==="hot"?h.status==="open"&&h.lead_score>=75:filter==="unread"?h.status==="open"&&h.unread:filter==="human"?h.status==="open"&&!!h.needs_human:filter==="resolved"?h.status==="resolved":h.status==="open";return matches&&f}),[handoffs,search,filter]);
 async function send(e:FormEvent){e.preventDefault();if(!selected||!message.trim()||sending)return;setSending(true);try{const r=await fetch("/api/inbox",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({handoffId:selected.id,message:message.trim()})});if(r.ok){setMessage("");await thread(selected);await load()}}finally{setSending(false)}}
 async function event(eventType:string){if(!selected)return;const r=await fetch("/api/inbox",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"event",id:selected.id,eventType})});if(r.ok){const d=await r.json();if(d.handoff)setSelected(d.handoff);await load();await loadAnalytics()}}
 async function update(patch:Record<string,unknown>){if(!selected)return;const r=await fetch("/api/inbox",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"update",id:selected.id,...patch})});if(r.ok){const d=await r.json();if(d.handoff)setSelected(d.handoff);await load()}}
 const series=analytics.series?.length?analytics.series:fallbackSeries;const maxSeries=Math.max(1,...series);const pts=series.map((v,i)=>({x:series.length===1?550:i*(1100/(series.length-1)),y:164-(v/maxSeries)*132,value:v,index:i}));const smoothPath=pts.length?pts.slice(1).reduce((d,p,i)=>{const a=pts[i],mx=(a.x+p.x)/2;return d+" C "+mx+" "+a.y+", "+mx+" "+p.y+", "+p.x+" "+p.y},"M "+pts[0].x+" "+pts[0].y):"";function chartMove(e:MouseEvent<HTMLDivElement>){if(!pts.length)return;const rect=e.currentTarget.getBoundingClientRect(),rx=Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),idx=Math.min(pts.length-1,Math.round(rx*(pts.length-1))),p=pts[idx];setHover({...p})}
 return <div className="viShell">
  <VyralSidebar active="inbox"/>
    <main className="vi">
   <header className="viHero"><div><small>VYRAL INBOX · ESCALA</small><h1>{automation?"Personas y chats de esta automatización":"Convertí conversaciones en ventas."}</h1><p>IA, leads y atención humana en una sola bandeja.</p></div></header>
   <section className="viAnalyticsCard"><div className="viAnalyticsHead"><div><small>CRM ANALYTICS</small><h2>Embudo comercial</h2></div><select value={days} onChange={e=>{const n=Number(e.target.value);setDays(n);void loadAnalytics(n)}}><option value={7}>7 días</option><option value={30}>30 días</option><option value={90}>90 días</option></select></div><div className="viChart"><div className="viChartTop"><div><span>PROGRESO DEL OBJETIVO</span><strong>{analytics.goals}</strong><small>objetivos completados</small></div><div className="viChartLegend"><i/> Evolución real del período</div></div><div className="viChartPlot" onMouseMove={chartMove} onMouseLeave={()=>setHover(null)}><div className="viChartGrid"/><svg viewBox="0 0 1100 180" preserveAspectRatio="none" role="img" aria-label="Progreso de objetivos"><defs><linearGradient id="viArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#59f3ec" stopOpacity=".38"/><stop offset="70%" stopColor="#59f3ec" stopOpacity=".07"/><stop offset="100%" stopColor="#59f3ec" stopOpacity="0"/></linearGradient></defs>{pts.length>0&&<><path className="viArea" d={smoothPath+" L "+pts[pts.length-1].x+" 180 L 0 180 Z"} fill="url(#viArea)"/><path className="viLine" d={smoothPath}/>{pts.map(p=><circle key={p.index} className="viDot" cx={p.x} cy={p.y} r="3.4"/>)}</>}</svg>{hover&&<><div className="viHoverLine" style={{left:(hover.x/11)+"%"}}/><div className="viHoverDot" style={{left:(hover.x/11)+"%",top:(hover.y/1.8)+"%"}}/><div className="viTooltip" style={{left:"min(calc("+(hover.x/11)+"% + 10px), calc(100% - 138px))",top:Math.max(4,hover.y/1.8-8)+"%"}}><small>PROGRESO</small><b>{hover.value}</b><span>objetivos · punto {hover.index+1}</span></div></>}</div></div><div className="viFunnel"><div><span>CONVERSACIONES</span><b>{analytics.conversations}</b></div><i>→</i><div><span>INTERESADOS</span><b>{analytics.interested}</b></div><i>→</i><div><span>ALTA INTENCIÓN</span><b>{analytics.hot}</b></div><i>→</i><div><span>WHATSAPP</span><b>{analytics.whatsapp}</b></div><i>→</i><div><span>OBJETIVO CUMPLIDO</span><b>{analytics.goals}</b></div><strong>{analytics.conversion}%<small> CUMPLIMIENTO</small></strong></div></section><div className="viStats"><button onClick={()=>setFilter("open")}><span>PENDIENTES</span><b>{stats.total}</b><small>Necesitan atención</small></button><button onClick={()=>setFilter("hot")}><span>ALTA INTENCIÓN</span><b>{stats.hot}</b><small>Score ≥ 75</small></button><button onClick={()=>setFilter("unread")}><span>SIN LEER</span><b>{stats.unread}</b><small>Nuevos mensajes</small></button><button onClick={()=>setFilter("human")}><span>PIDIERON HUMANO</span><b>{stats.human}</b><small>Esperan tu respuesta</small></button></div>
   <div className="viToolbar"><div className="viSearch">⌕ <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar persona o mensaje…"/></div><div className="viFilters">{[["open","Activas"],["hot","✦ Alta intención"],["human","👤 Humano"],["unread","Sin leer"],["resolved","Cerradas"],["all","Todas"]].map(x=><button key={x[0]} className={filter===x[0]?"on":""} onClick={()=>setFilter(x[0])}>{x[1]}</button>)}</div></div>
   <div className="viGrid">
    <aside className="viThreads">{visible.length?visible.map(h=><button className={(selected?.id===h.id?"on ":"")+(h.unread?"unread":"")} onClick={()=>void thread(h)} key={h.id}><div className="viAvatar">{(h.contact_username||"?").slice(0,1).toUpperCase()}</div><div className="viThreadText"><div><b>@{h.contact_username||h.contact_id}</b><time>{h.unread?"● NUEVO":stages[h.stage||"new"]}</time></div><p>{h.last_message||h.reason||"Requiere atención"}</p><span className={h.lead_score>=75?"hot":""}>Lead {h.lead_score}/100</span></div></button>):<div className="empty"><b>Todo al día.</b><span>No hay conversaciones en este filtro.</span></div>}</aside>
    <section className="viConversation">{selected?<><div className="viThreadHead"><div className="viPerson"><div className="viAvatar">{(selected.contact_username||"?").slice(0,1).toUpperCase()}</div><div><b>@{selected.contact_username||selected.contact_id}</b><span>Instagram · {selected.reason||"Conversación activa"}</span>{selected.needs_human&&<em className="viHumanBadge">◆ ATENCIÓN HUMANA SOLICITADA</em>}</div></div><div className="viScore"><small>INTENCIÓN</small><strong>{selected.lead_score}/100</strong></div></div><div className="viMessages">{messages.map(m=><div key={m.id} className={"msg "+m.direction}><small>{m.sender_type==="human"?"VOS":m.direction==="out"?"VYRAL IA":"CONTACTO"}</small>{m.attachment_url&&m.attachment_type==="image"&&<a className="viMedia" href={m.attachment_url} target="_blank" rel="noreferrer"><img src={m.attachment_url} alt="Imagen enviada por Instagram"/></a>}{m.attachment_url&&m.attachment_type!=="image"&&<a className="viFile" href={m.attachment_url} target="_blank" rel="noreferrer">Ver archivo adjunto ↗</a>}<p>{m.body}</p>{m.created_at&&<time>{new Date(m.created_at).toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})}</time>}</div>)}</div><form onSubmit={send}><div className="viComposer"><button type="button" className="viAudioSoon" title="Audio desde CRM — próximamente" aria-label="Audio próximamente">◉</button><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Respondé desde VYRAL…"/><button disabled={sending}>{sending?"ENVIANDO…":"ENVIAR →"}</button></div></form></>:<div className="choose"><div>◉</div><b>Tu centro de conversaciones</b><span>Elegí un lead para ver el historial completo y responder sin salir de VYRAL.</span></div>}</section>
    <aside className="viCRM">{selected?<><small>CRM DEL LEAD</small><h3>@{selected.contact_username||selected.contact_id}</h3><label>Etapa<select value={selected.stage||"new"} onChange={e=>void update({stage:e.target.value})}>{Object.entries(stages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Prioridad<select value={selected.priority||"normal"} onChange={e=>void update({priority:e.target.value})}><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><div className="viLeadMeter"><span><b>Lead score</b><i>{selected.lead_score}%</i></span><div><i style={{width:selected.lead_score+"%"}}/></div></div><label>Notas<textarea value={notes} onChange={e=>setNotes(e.target.value)} onBlur={()=>void update({notes})} placeholder="Datos, objeciones, seguimiento…"/></label>{selected.ai_paused&&<button className="viClose" onClick={()=>void update({aiPaused:false,needsHuman:false})}>REANUDAR VYRAL IA</button>}<button className="viClose" onClick={()=>void update({status:selected.status==="resolved"?"open":"resolved"})}>{selected.status==="resolved"?"REABRIR CONVERSACIÓN":"MARCAR COMO RESUELTA ✓"}</button><div className="viActions"><small>ACCIONES DEL EMBUDO</small><div><button onClick={()=>void event("interested")}>♡ INTERESADO</button><button onClick={()=>void event("whatsapp")}>↗ WHATSAPP</button><button onClick={()=>void event("payment_intent")}>$ PAGO</button><button onClick={()=>void event("goal_completed")}>✓ OBJETIVO</button></div></div><div className="viAIReason"><small>POR QUÉ LA DERIVÓ VYRAL AI</small><p>{selected.reason||"Intención comercial detectada."}</p></div></>:<div className="viCrmEmpty">Seleccioná un lead para ver su ficha CRM.</div>}</aside>
   </div>
  </main>
 </div>
}