import crypto from "crypto";
import {NextResponse} from "next/server";
import {env} from "../../../../../lib/env";
import {supabaseAdmin} from "../../../../../lib/supabase-admin";
export const maxDuration=60;
const GRAPH="https://graph.instagram.com",VER=process.env.META_GRAPH_API_VERSION||"v24.0";
function norm(s:any){return String(s||"").trim().toLowerCase()}
function deterministicMatch(a:any,text:string){const t=norm(text),ks=(a.keywords||[]).map(norm).filter(Boolean),ex=(a.excludeKeywords||[]).map(norm).filter(Boolean);if(ex.some((x:string)=>t.includes(x)))return false;if(a.triggerMode==="exact")return ks.some((x:string)=>t===x);if(a.triggerMode==="contains")return ks.some((x:string)=>t.includes(x));return ks.some((x:string)=>t.includes(x))}
async function aiDecision(a:any,text:string){if(a.triggerMode!=="ai_intent")return{match:deterministicMatch(a,text),dm:String(a.dmMessage||"")};const key=process.env.OPENAI_API_KEY;if(!key)return{match:deterministicMatch(a,text),dm:String(a.dmMessage||"")};const prompt=`Decidí si este comentario activa este agente de Instagram y redactá UNA respuesta privada breve si corresponde. Comentario: ${text}. Palabras/intenciones: ${JSON.stringify(a.keywords||[])}. Contexto: ${String(a.contentLabel||"")}. Objetivo: ${String(a.conversationGoal||"lead")}. Tono: ${String(a.aiTone||"natural")}. País: ${String(a.aiCountry||"")}. Reglas: ${String(a.aiInstructions||"")}. Base DM: ${String(a.dmMessage||"")}. No inventes precios ni datos. Respondé SOLO JSON {"match":true,"dm":"..."}. Si no corresponde, match=false.`;const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",input:prompt,max_output_tokens:350})}),j=await r.json().catch(()=>({}));if(!r.ok)return{match:deterministicMatch(a,text),dm:String(a.dmMessage||"")};let out=String(j.output_text||"");if(!out)for(const x of j.output||[])for(const z of x.content||[])if(z.type==="output_text")out+=z.text||"";try{const x=JSON.parse(out.slice(out.indexOf("{"),out.lastIndexOf("}")+1));return{match:Boolean(x.match),dm:String(x.dm||a.dmMessage||"")}}catch{return{match:deterministicMatch(a,text),dm:String(a.dmMessage||"")}}
}
async function ig(url:string,token:string,body?:any){const r=await fetch(url,{method:"POST",headers:{Authorization:`Bearer ${token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,cache:"no-store"}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw Error(j.error?.message||`Instagram HTTP ${r.status}`);return j}
async function conversationReply(a:any,text:string){const key=process.env.OPENAI_API_KEY;if(!key)return String(a.dmMessage||"Gracias por escribir. ¿En qué te puedo ayudar?");const prompt=`Sos el agente de Instagram de este negocio. Continuá la conversación por DM de forma breve, natural y útil. Mensaje del usuario: ${text}. Contexto del contenido/oferta: ${String(a.contentLabel||"")}. Objetivo: ${String(a.conversationGoal||"lead")}. Tono: ${String(a.aiTone||"natural")}. País: ${String(a.aiCountry||"")}. Reglas: ${String(a.aiInstructions||"")}. No inventes precios, condiciones ni datos que no estén en el contexto. Hacé como máximo una pregunta por respuesta. No digas que sos una IA. Respondé SOLO el texto que se debe enviar.`;const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",input:prompt,max_output_tokens:250})}),j=await r.json().catch(()=>({}));if(!r.ok)return String(a.dmMessage||"Gracias por escribir. ¿En qué te puedo ayudar?");let out=String(j.output_text||"");if(!out)for(const x of j.output||[])for(const z of x.content||[])if(z.type==="output_text")out+=z.text||"";return out.trim().slice(0,1800)||String(a.dmMessage||"Gracias por escribir. ¿En qué te puedo ayudar?")}
async function processMessage(db:any,account:any,m:any){const senderId=String(m?.sender?.id||""),recipientId=String(m?.recipient?.id||""),mid=String(m?.message?.mid||""),text=String(m?.message?.text||"").trim();if(!senderId||!mid||!text||m?.message?.is_echo)return;const selfIds=new Set([String(account.instagram_user_id||""),recipientId]);if(selfIds.has(senderId))return;const u=await db.auth.admin.getUserById(account.user_id),rules=(u.data?.user?.user_metadata?.vyral_automations||[]).filter((a:any)=>a.enabled&&a.platforms?.includes("instagram")&&a.continueConversation!==false&&a.dmEnabled!==false);if(!rules.length)return;
 // Prefer the automation that most recently started a DM with this Instagram user.
 const prev=await db.from("instagram_automation_runs").select("automation_id,commenter_id,created_at").eq("account_id",account.id).eq("commenter_id",senderId).eq("status","sent").order("created_at",{ascending:false}).limit(1).maybeSingle();let a=rules.find((x:any)=>x.id===prev.data?.automation_id)||rules[0];const reply=await conversationReply(a,text);if(!reply)return;const syntheticId=`dm:${mid}`;const ins=await db.from("instagram_automation_runs").insert({user_id:account.user_id,account_id:account.id,automation_id:a.id,comment_id:syntheticId,commenter_id:senderId,comment_text:text,status:"matched",detail:{source:"instagram_dm",continueConversation:true}}).select("id").maybeSingle();if(ins.error){if(String(ins.error.code)==="23505")return;throw ins.error}try{const j=await ig(`${GRAPH}/${VER}/${encodeURIComponent(account.instagram_user_id)}/messages`,account.access_token,{recipient:{id:senderId},message:{text:reply}});await db.from("instagram_automation_runs").update({status:"sent",private_message_id:String(j.message_id||"")||null,updated_at:new Date().toISOString(),detail:{source:"instagram_dm",continueConversation:true}}).eq("id",ins.data?.id)}catch(e:any){await db.from("instagram_automation_runs").update({status:"error",error:String(e?.message||e).slice(0,1000),updated_at:new Date().toISOString()}).eq("id",ins.data?.id)}}
async function processComment(db:any,account:any,value:any){const commentId=String(value?.id||""),text=String(value?.text||""),fromId=String(value?.from?.id||""),username=String(value?.from?.username||""),mediaId=String(value?.media?.id||"");if(!commentId||!text||fromId===String(account.instagram_user_id))return;
 const u=await db.auth.admin.getUserById(account.user_id),rules=(u.data?.user?.user_metadata?.vyral_automations||[]).filter((a:any)=>a.enabled&&a.platforms?.includes("instagram"));for(const a of rules){const decision=await aiDecision(a,text);if(!decision.match)continue;
 const ins=await db.from("instagram_automation_runs").insert({user_id:account.user_id,account_id:account.id,automation_id:a.id,comment_id:commentId,media_id:mediaId||null,commenter_id:fromId||null,commenter_username:username||null,comment_text:text,status:"matched",detail:{triggerMode:a.triggerMode}}).select("id").maybeSingle();if(ins.error){if(String(ins.error.code)==="23505")return;throw ins.error}const runId=ins.data?.id;
 try{let publicId="",messageId="";if(a.publicReplyEnabled&&String(a.publicReply||"").trim()){const j=await ig(`${GRAPH}/${VER}/${encodeURIComponent(commentId)}/replies?message=${encodeURIComponent(String(a.publicReply).trim())}`,account.access_token);publicId=String(j.id||"")}
 let dm=String(decision.dm||a.dmMessage||"").trim();if(a.dmLink)dm=`${dm}\n\n${a.dmLink}`.trim();if(a.resourceUrl&&String(a.resourceUrl).startsWith("automation-resource/")){const s=await db.storage.from("scheduled-media").createSignedUrl(String(a.resourceUrl),604800);if(s.data?.signedUrl)dm=`${dm}\n\n${a.resourceName||"Guía"}: ${s.data.signedUrl}`.trim()}else if(a.resourceUrl)dm=`${dm}\n\n${a.resourceUrl}`.trim();
 if(a.dmEnabled&&dm){const j=await ig(`${GRAPH}/${VER}/${encodeURIComponent(account.instagram_user_id)}/messages`,account.access_token,{recipient:{comment_id:commentId},message:{text:dm}});messageId=String(j.message_id||"")}
 await db.from("instagram_automation_runs").update({status:"sent",public_reply_id:publicId||null,private_message_id:messageId||null,updated_at:new Date().toISOString(),detail:{triggerMode:a.triggerMode,resource:Boolean(a.resourceUrl)}}).eq("id",runId)}catch(e:any){await db.from("instagram_automation_runs").update({status:"error",error:String(e?.message||e).slice(0,1000),updated_at:new Date().toISOString()}).eq("id",runId)}return}}
export async function GET(req:Request){const u=new URL(req.url),mode=u.searchParams.get("hub.mode"),token=u.searchParams.get("hub.verify_token"),challenge=u.searchParams.get("hub.challenge");if(mode==="subscribe"&&token===env("META_WEBHOOK_VERIFY_TOKEN")&&challenge)return new NextResponse(challenge,{status:200,headers:{"Content-Type":"text/plain"}});return new NextResponse("Forbidden",{status:403})}
export async function POST(req:Request){const raw=await req.text(),sig=req.headers.get("x-hub-signature-256")||"",expected="sha256="+crypto.createHmac("sha256",env("META_INSTAGRAM_APP_SECRET")).update(raw).digest("hex");if(sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return new NextResponse("Invalid signature",{status:401});let payload:any;try{payload=JSON.parse(raw)}catch{return new NextResponse("Bad request",{status:400})}const db=supabaseAdmin();await db.from("meta_webhook_events").insert({platform:"instagram",event_type:String(payload.object||"instagram"),payload});for(const entry of payload.entry||[]){const accountId=String(entry.id||"");if(!accountId)continue;let q=await db.from("meta_instagram_accounts").select("id,user_id,instagram_user_id,access_token").eq("instagram_user_id",accountId).maybeSingle();let account=q.data;
 // Instagram webhook IDs can be in a different ID namespace than the ID returned by Instagram Login.
 // If the entry ID does not match our stored account, identify the owner by checking the event media
 // with each connected Instagram token. A token can read that media only for the account it belongs to.
 if(!account){const mediaId=String((entry.changes||[]).find((x:any)=>x.field==="comments")?.value?.media?.id||"");if(mediaId){const all=await db.from("meta_instagram_accounts").select("id,user_id,instagram_user_id,access_token");for(const candidate of all.data||[]){try{const u=new URL(`${GRAPH}/${VER}/${encodeURIComponent(mediaId)}`);u.searchParams.set("fields","id");u.searchParams.set("access_token",candidate.access_token);const r=await fetch(u,{cache:"no-store"}),j=await r.json().catch(()=>({}));if(r.ok&&!j.error&&String(j.id)===mediaId){account=candidate;break}}catch{}}}}
 if(!account&&Array.isArray(entry.messaging)&&entry.messaging.length){const recipientIds=entry.messaging.map((m:any)=>String(m?.recipient?.id||"")).filter(Boolean);const senderIds=entry.messaging.map((m:any)=>String(m?.sender?.id||"")).filter(Boolean);const ids=[...new Set([...recipientIds,...senderIds])];if(ids.length){const all=await db.from("meta_instagram_accounts").select("id,user_id,instagram_user_id,access_token");account=(all.data||[]).find((x:any)=>ids.includes(String(x.instagram_user_id)))||null}if(!account){const all=await db.from("meta_instagram_accounts").select("id,user_id,instagram_user_id,access_token");const accounts=all.data||[];if(accounts.length===1)account=accounts[0]}}
 if(!account)continue;for(const ch of entry.changes||[])if(ch.field==="comments")await processComment(db,account,ch.value);for(const m of entry.messaging||[])await processMessage(db,account,m)}return NextResponse.json({ok:true})}
