import crypto from "crypto";
import { NextResponse } from "next/server";
import { getCustomerSession } from "../../../lib/auth";
import { supabaseAdmin } from "../../../lib/supabase-admin";

const BUCKET = "scheduled-media";
const ALLOWED = new Set(["video/mp4", "video/quicktime", "video/webm"]);
const MAX_FILE_SIZE = 4 * 1024 * 1024 * 1024;
type Target = { platform: "tiktok" | "instagram" | "facebook"; accountId: string; name?: string };
function safeExt(fileName: string) { return (fileName.split(".").pop() || "mp4").replace(/[^a-z0-9]/gi, "").toLowerCase() || "mp4"; }
function validateTargets(value: unknown): value is Target[] { return Array.isArray(value)&&value.length>0&&value.every((target)=>target&&typeof target==="object"&&["tiktok","instagram","facebook"].includes(String((target as Target).platform))&&typeof (target as Target).accountId==="string"&&Boolean((target as Target).accountId)); }
async function ownsTargets(userId:string,targets:Target[]){const client=supabaseAdmin();const tables:Record<Target["platform"],string>={tiktok:"tiktok_accounts",instagram:"meta_instagram_accounts",facebook:"meta_facebook_pages"};for(const platform of ["tiktok","instagram","facebook"] as const){const ids=[...new Set(targets.filter(t=>t.platform===platform).map(t=>t.accountId))];if(!ids.length)continue;const q=await client.from(tables[platform]).select("id").eq("user_id",userId).in("id",ids);if(q.error)throw new Error(q.error.message);if(new Set((q.data||[]).map((r:any)=>String(r.id))).size!==ids.length)return false}return true;}

export async function POST(req:Request){const session=await getCustomerSession();if(!session)return NextResponse.json({error:"No autorizado"},{status:401});try{const body=await req.json();const action=String(body.action||"create");const client=supabaseAdmin();if(action==="prepare-upload"){const fileName=String(body.fileName||"video.mp4"),mimeType=String(body.mimeType||"video/mp4"),fileSize=Number(body.fileSize||0);if(!ALLOWED.has(mimeType))return NextResponse.json({error:"Usá MP4, MOV/QuickTime o WebM."},{status:400});if(!Number.isFinite(fileSize)||fileSize<=0||fileSize>MAX_FILE_SIZE)return NextResponse.json({error:"El video tiene un tamaño inválido o supera 4 GB."},{status:400});const id=crypto.randomUUID(),storagePath=`${session.userId}/${id}/video.${safeExt(fileName)}`;const signed=await client.storage.from(BUCKET).createSignedUploadUrl(storagePath);if(signed.error||!signed.data)throw new Error(`No se pudo preparar el almacenamiento: ${signed.error?.message||"error desconocido"}`);return NextResponse.json({ok:true,id,bucket:BUCKET,path:storagePath,token:signed.data.token,signedUrl:signed.data.signedUrl});}
const id=String(body.id||""),storagePath=String(body.storagePath||""),scheduledAt=String(body.scheduledAt||""),timezone=String(body.timezone||"UTC"),caption=String(body.caption||"").trim(),privacyLevel=String(body.privacyLevel||""),mimeType=String(body.mimeType||"video/mp4"),fileName=String(body.fileName||"video.mp4"),fileSize=Number(body.fileSize||0),targets=body.targets as unknown,platforms=body.platforms as unknown;if(!id||!storagePath||!scheduledAt||!caption)return NextResponse.json({error:"Faltan datos para crear la programación."},{status:400});if(!storagePath.startsWith(`${session.userId}/${id}/`))return NextResponse.json({error:"Ruta de almacenamiento inválida."},{status:403});if(!ALLOWED.has(mimeType)||!Number.isFinite(fileSize)||fileSize<=0||fileSize>MAX_FILE_SIZE)return NextResponse.json({error:"Datos de video inválidos."},{status:400});const when=new Date(scheduledAt);if(!Number.isFinite(when.getTime())||when.getTime()<=Date.now()+30000)return NextResponse.json({error:"Elegí una fecha al menos 30 segundos en el futuro."},{status:400});if(!validateTargets(targets))return NextResponse.json({error:"Seleccioná al menos una cuenta válida."},{status:400});if(!Array.isArray(platforms)||!platforms.length)return NextResponse.json({error:"Seleccioná al menos una plataforma."},{status:400});if(!(await ownsTargets(session.userId,targets)))return NextResponse.json({error:"Una de las cuentas seleccionadas no pertenece a tu usuario."},{status:403});const exists=await client.storage.from(BUCKET).list(`${session.userId}/${id}`,{search:`video.${safeExt(fileName)}`});if(exists.error||!(exists.data||[]).some(item=>item.name===`video.${safeExt(fileName)}`))return NextResponse.json({error:"El video todavía no terminó de guardarse. Intentá nuevamente."},{status:409});const insert=await client.from("scheduled_publications").insert({id,user_id:session.userId,scheduled_at:when.toISOString(),timezone,caption,privacy_level:privacyLevel||null,platforms,targets,storage_bucket:BUCKET,storage_path:storagePath,mime_type:mimeType,file_name:fileName,file_size:fileSize,status:"scheduled"}).select("id,scheduled_at,status").single();if(insert.error){await client.storage.from(BUCKET).remove([storagePath]);throw new Error(`No se pudo crear la programación: ${insert.error.message}`)}const jobs=(targets as Target[]).map(t=>({publication_id:id,user_id:session.userId,platform:t.platform,account_id:t.accountId,account_name:t.name||null,status:"queued",next_attempt_at:when.toISOString()}));const jq=await client.from("publish_target_jobs").upsert(jobs,{onConflict:"publication_id,platform,account_id"});if(jq.error){await client.from("scheduled_publications").delete().eq("id",id);await client.storage.from(BUCKET).remove([storagePath]);throw new Error(`No se pudo preparar la cola: ${jq.error.message}`)}return NextResponse.json({ok:true,publication:insert.data});}catch(e:any){return NextResponse.json({error:e?.message||"No se pudo programar la publicación."},{status:500})}}

export async function GET(){const session=await getCustomerSession();if(!session)return NextResponse.json({error:"No autorizado"},{status:401});const client=supabaseAdmin();const q=await client.from("scheduled_publications").select("id,scheduled_at,timezone,caption,privacy_level,platforms,targets,status,last_error,platform_results,created_at,storage_bucket,storage_path,file_name,mime_type").eq("user_id",session.userId).order("scheduled_at",{ascending:false}).limit(200);if(q.error)return NextResponse.json({error:q.error.message},{status:500});const publications=await Promise.all((q.data||[]).map(async(row)=>{let preview_url:string|null=null;if(row.storage_path&&String(row.mime_type||"").startsWith("image/")){const signed=await client.storage.from(row.storage_bucket||BUCKET).createSignedUrl(row.storage_path,3600);if(!signed.error)preview_url=signed.data?.signedUrl||null}return {...row,preview_url};}));return NextResponse.json({publications},{headers:{"Cache-Control":"private, no-store"}});}
