import { NextRequest, NextResponse } from "next/server";
import { getCustomerSession } from "../../../lib/auth";
import { supabaseAdmin } from "../../../lib/supabase-admin";
export const dynamic="force-dynamic";
type VoiceAsset={id:string;name:string;transcript:string;purpose:string;when:string;url?:string};
type AutomationRule={id:string;name:string;enabled:boolean;platforms:("instagram"|"facebook"|"tiktok")[];contentLabel?:string;triggerMode:"exact"|"contains"|"ai_intent";keywords:string[];excludeKeywords?:string[];publicReplyEnabled:boolean;publicReply:string;dmEnabled:boolean;dmMessage:string;dmLink?:string;resourceName?:string;resourceUrl?:string;resourcePurpose?:string;resourceWhen?:string;resourceMode?:"business"|"specific";businessResourceIds?:string[];conversationMode?:"human"|"instant";targetMediaIds?:string[];aiEnabled:boolean;aiTone?:string;aiCountry?:string;aiAudienceAge?:string;aiInstructions?:string;aiConfidence?:number;humanHandoff?:boolean;collectLead?:boolean;leadTag?:string;cooldownMinutes?:number;maxRepliesPerUser?:number;smartGuard?:boolean;conversionGoal?:"link_click"|"dm_started"|"lead"|"none";conversationGoal?:"sell"|"whatsapp"|"book"|"lead"|"support"|"resource";autonomy?:"guided"|"balanced"|"high";personalizeName?:boolean;continueConversation?:boolean;qualifyLead?:boolean;whatsappTarget?:string;ctaText?:string;voiceEnabled?:boolean;voiceAssetName?:string;voiceAssetUrl?:string;voiceWhen?:"never"|"hot"|"manual";voiceAssets?:VoiceAsset[];createdAt:string;updatedAt:string};
async function loadUser(){const session=await getCustomerSession();if(!session)return null;const client=supabaseAdmin();const{data}=await client.auth.admin.getUserById(session.userId);if(!data.user)return null;return{session,client,user:data.user}}
function sanitizeRule(input:any,existing?:AutomationRule):AutomationRule{const now=new Date().toISOString(),allowed=new Set(["instagram","facebook"]);const platforms=(Array.isArray(input.platforms)?input.platforms.filter((x:string)=>allowed.has(x)).slice(0,2):["instagram","facebook"]) as AutomationRule["platforms"];const triggerMode=(["exact","contains","ai_intent"].includes(input.triggerMode)?input.triggerMode:"contains") as AutomationRule["triggerMode"],goal=(["link_click","dm_started","lead","none"].includes(input.conversionGoal)?input.conversionGoal:"dm_started") as AutomationRule["conversionGoal"],conversationGoal=(["sell","whatsapp","book","lead","support","resource"].includes(input.conversationGoal)?input.conversationGoal:"lead") as AutomationRule["conversationGoal"],autonomy=(["guided","balanced","high"].includes(input.autonomy)?input.autonomy:"balanced") as AutomationRule["autonomy"],voiceWhen=(["never","hot","manual"].includes(input.voiceWhen)?input.voiceWhen:"never") as AutomationRule["voiceWhen"];
 const voiceAssets=(Array.isArray(input.voiceAssets)?input.voiceAssets:[]).slice(0,12).map((v:any)=>({id:String(v.id||crypto.randomUUID()).slice(0,80),name:String(v.name||"Audio VYRAL").slice(0,180),transcript:String(v.transcript||"").slice(0,3000),purpose:String(v.purpose||"").slice(0,500),when:String(v.when||"").slice(0,500),url:String(v.url||"").slice(0,1200)}));
 return{id:String(input.id||existing?.id||crypto.randomUUID()),name:String(input.name||existing?.name||"Nueva automatización").slice(0,80),enabled:Boolean(input.enabled??existing?.enabled??true),platforms,contentLabel:String(input.contentLabel||"").slice(0,1000),triggerMode,keywords:(Array.isArray(input.keywords)?input.keywords:[]).map((x:unknown)=>String(x).trim().toLowerCase()).filter(Boolean).slice(0,30),excludeKeywords:(Array.isArray(input.excludeKeywords)?input.excludeKeywords:[]).map((x:unknown)=>String(x).trim().toLowerCase()).filter(Boolean).slice(0,30),publicReplyEnabled:Boolean(input.publicReplyEnabled),publicReply:String(input.publicReply||"").slice(0,500),dmEnabled:Boolean(input.dmEnabled??true),dmMessage:String(input.dmMessage||"").slice(0,2000),dmLink:String(input.dmLink||"").slice(0,1000),resourceName:String(input.resourceName||"").slice(0,180),resourceUrl:String(input.resourceUrl||"").slice(0,1200),resourcePurpose:String(input.resourcePurpose||"").slice(0,1200),resourceWhen:String(input.resourceWhen||"").slice(0,700),resourceMode:input.resourceMode==="specific"?"specific":"business",businessResourceIds:(Array.isArray(input.businessResourceIds)?input.businessResourceIds:[]).map((x:unknown)=>String(x)).filter(Boolean).slice(0,100),conversationMode:input.conversationMode==="instant"?"instant":"human",targetMediaIds:(Array.isArray(input.targetMediaIds)?input.targetMediaIds:[]).map((x:unknown)=>String(x)).filter(Boolean).slice(0,20),aiEnabled:Boolean(input.aiEnabled),aiTone:String(input.aiTone||"Natural y cercano").slice(0,100),aiCountry:String(input.aiCountry||"Argentina").slice(0,80),aiAudienceAge:String(input.aiAudienceAge||"Joven adulto").slice(0,80),aiInstructions:String(input.aiInstructions||"").slice(0,3000),aiConfidence:Math.max(.5,Math.min(.99,Number(input.aiConfidence||.78))),humanHandoff:Boolean(input.humanHandoff??true),collectLead:Boolean(input.collectLead),leadTag:String(input.leadTag||"").slice(0,80),cooldownMinutes:Math.max(0,Math.min(10080,Number(input.cooldownMinutes||60))),maxRepliesPerUser:Math.max(1,Math.min(50,Number(input.maxRepliesPerUser||8))),smartGuard:Boolean(input.smartGuard??true),conversionGoal:goal,conversationGoal,autonomy,personalizeName:Boolean(input.personalizeName??true),continueConversation:Boolean(input.continueConversation??true),qualifyLead:Boolean(input.qualifyLead??true),whatsappTarget:String(input.whatsappTarget||"").slice(0,80),ctaText:String(input.ctaText||"").slice(0,300),voiceEnabled:Boolean(input.voiceEnabled),voiceAssetName:String(input.voiceAssetName||"").slice(0,180),voiceAssetUrl:String(input.voiceAssetUrl||"").slice(0,1200),voiceWhen,voiceAssets,createdAt:existing?.createdAt||now,updatedAt:now}}
export async function GET(){const ctx=await loadUser();if(!ctx)return NextResponse.json({error:"No autorizado"},{status:401});const meta=ctx.user.user_metadata||{},raw:Array<any>=Array.isArray(meta.vyral_automations)?meta.vyral_automations:[];const runs=await ctx.client.from("instagram_automation_runs").select("automation_id,media_id,created_at").eq("user_id",ctx.session.userId).not("media_id","is",null).order("created_at",{ascending:false}).limit(200);const latest=new Map<string,string>();for(const r of runs.data||[])if(r.automation_id&&r.media_id&&!latest.has(String(r.automation_id)))latest.set(String(r.automation_id),String(r.media_id));const voiceQ=await ctx.client.from("vyral_automation_voice_settings").select("automation_id,enabled,voice_profile_id,max_ai_audios,max_audio_seconds,mode,voice_probability").eq("user_id",ctx.session.userId);
const voiceMap=new Map((voiceQ.data||[]).map((v:any)=>[String(v.automation_id),v]));
const automations=raw.map(a=>({...a,targetMediaIds:Array.isArray(a.targetMediaIds)&&a.targetMediaIds.length?a.targetMediaIds:(latest.get(String(a.id))?[latest.get(String(a.id))]:[]),voiceSettings:voiceMap.get(String(a.id))||null}));
const profiles=await ctx.client.from("vyral_voice_profiles").select("id,name,source,provider,status,language_mode,provider_voice_id,preset_voice_id").eq("user_id",ctx.session.userId).order("created_at",{ascending:true});
let availableVoices:any[]=[];const elevenKey=process.env.ELEVENLABS_API_KEY;
if(elevenKey){try{const vr=await fetch("https://api.elevenlabs.io/v2/voices?page_size=100",{headers:{"xi-api-key":elevenKey},cache:"no-store"});if(vr.ok){const vj=await vr.json();availableVoices=(Array.isArray(vj.voices)?vj.voices:[]).map((v:any)=>({voice_id:String(v.voice_id||""),name:String(v.name||"Voz"),category:String(v.category||""),preview_url:String(v.preview_url||""),labels:v.labels||{}})).filter((v:any)=>v.voice_id)}}catch{}}
return NextResponse.json({automations,paused:Boolean(meta.vyral_automations_paused),voiceProfiles:profiles.data||[],availableVoices})}
export async function POST(req:NextRequest){const ctx=await loadUser();if(!ctx)return NextResponse.json({error:"No autorizado"},{status:401});const body=await req.json().catch(()=>({})),meta=ctx.user.user_metadata||{};
if(body.action==="voice_preview"){
 const voiceId=String(body.voiceId||"").trim(),language=String(body.language||"es").toLowerCase();
 if(!voiceId)return NextResponse.json({error:"Elegí una voz."},{status:400});
 const key=process.env.ELEVENLABS_API_KEY;if(!key)return NextResponse.json({error:"La voz todavía no está disponible."},{status:503});
 const samples:any={es:"Hola, soy tu asistente de VYRAL. Esta es una prueba de cómo voy a sonar hablando en español.",en:"Hi, I am your VYRAL assistant. This is a preview of how I will sound speaking English.",pt:"Olá, sou seu assistente da VYRAL. Esta é uma amostra de como vou falar em português.",fr:"Bonjour, je suis votre assistant VYRAL. Voici un aperçu de ma voix en français.",de:"Hallo, ich bin dein VYRAL-Assistent. So werde ich auf Deutsch klingen.",it:"Ciao, sono il tuo assistente VYRAL. Questa è un'anteprima di come parlerò in italiano."};
 const tr=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(voiceId)}`,{method:"POST",headers:{"xi-api-key":key,"Content-Type":"application/json","Accept":"audio/mpeg"},body:JSON.stringify({text:samples[language]||samples.es,model_id:"eleven_multilingual_v2"})});
 if(!tr.ok)return NextResponse.json({error:"No se pudo generar la prueba en ese idioma."},{status:502});
 return new NextResponse(await tr.arrayBuffer(),{status:200,headers:{"Content-Type":"audio/mpeg","Cache-Control":"no-store"}});
}
if(body.action==="save_voice_settings"){
 const automationId=String(body.automationId||"");if(!automationId)return NextResponse.json({error:"Falta automationId"},{status:400});
 const enabled=Boolean(body.enabled),voiceProfileId=body.voiceProfileId?String(body.voiceProfileId):null;
 if(enabled&&!voiceProfileId)return NextResponse.json({error:"Elegí una voz para activar respuestas de audio."},{status:400});
 if(voiceProfileId){const owned=await ctx.client.from("vyral_voice_profiles").select("id").eq("id",voiceProfileId).eq("user_id",ctx.session.userId).maybeSingle();if(!owned.data)return NextResponse.json({error:"La voz seleccionada no pertenece a esta cuenta."},{status:400})}
 const payload={user_id:ctx.session.userId,automation_id:automationId,enabled,voice_profile_id:voiceProfileId,max_ai_audios:Math.max(0,Math.min(3,Number(body.maxAiAudios??3))),max_audio_seconds:Math.max(10,Math.min(60,Number(body.maxAudioSeconds??40))),mode:body.mode==="text_only"?"text_only":"smart",voice_probability:Math.max(0,Math.min(100,Number(body.voiceProbability??35))),updated_at:new Date().toISOString()};
 const saved=await ctx.client.from("vyral_automation_voice_settings").upsert(payload,{onConflict:"user_id,automation_id"}).select().single();if(saved.error)return NextResponse.json({error:saved.error.message},{status:500});return NextResponse.json({ok:true,voiceSettings:saved.data});
}
if(body.action==="save_voice_profile"){
 const id=body.id?String(body.id):undefined,source=body.source==="cloned"?"cloned":"preset",name=String(body.name|| (source==="cloned"?"Mi voz clonada":"Voz VYRAL")).slice(0,100),voiceId=String(body.voiceId||"").trim();
 if(!voiceId)return NextResponse.json({error:"Elegí una voz."},{status:400});
 const payload:any={user_id:ctx.session.userId,name,source,provider:"elevenlabs",provider_voice_id:source==="cloned"?voiceId:null,preset_voice_id:source==="preset"?voiceId:null,status:"ready",language_mode:"auto",consent_confirmed_at:source==="cloned"?new Date().toISOString():null,updated_at:new Date().toISOString()};
 if(id)payload.id=id;const saved=await ctx.client.from("vyral_voice_profiles").upsert(payload).select("id,name,source,provider,status,language_mode,provider_voice_id,preset_voice_id").single();if(saved.error)return NextResponse.json({error:saved.error.message},{status:500});return NextResponse.json({ok:true,voiceProfile:saved.data});
}if(body.action==="pause_all"||body.action==="resume_all"){const paused=body.action==="pause_all";await ctx.client.auth.admin.updateUserById(ctx.session.userId,{user_metadata:{...meta,vyral_automations_paused:paused}});return NextResponse.json({ok:true,paused,automations:Array.isArray(meta.vyral_automations)?meta.vyral_automations:[]})}const current:AutomationRule[]=Array.isArray(meta.vyral_automations)?meta.vyral_automations:[],existing=body.id?current.find(x=>x.id===String(body.id)):undefined,rule=sanitizeRule(body,existing);if(!rule.platforms.length)return NextResponse.json({error:"Elegí Instagram o Facebook."},{status:400});if(!rule.keywords.length&&rule.triggerMode!=="ai_intent")return NextResponse.json({error:"Agregá al menos una palabra clave."},{status:400});if(!rule.dmEnabled&&!rule.publicReplyEnabled)return NextResponse.json({error:"Activá al menos una acción: respuesta pública o mensaje privado."},{status:400});const next=existing?current.map(x=>x.id===rule.id?rule:x):[rule,...current].slice(0,50);await ctx.client.auth.admin.updateUserById(ctx.session.userId,{user_metadata:{...meta,vyral_automations:next}});return NextResponse.json({ok:true,automation:rule,automations:next})}
export async function DELETE(req:NextRequest){const ctx=await loadUser();if(!ctx)return NextResponse.json({error:"No autorizado"},{status:401});const id=req.nextUrl.searchParams.get("id");if(!id)return NextResponse.json({error:"Falta id"},{status:400});const meta=ctx.user.user_metadata||{},current:AutomationRule[]=Array.isArray(meta.vyral_automations)?meta.vyral_automations:[],next=current.filter(x=>x.id!==id);await ctx.client.auth.admin.updateUserById(ctx.session.userId,{user_metadata:{...meta,vyral_automations:next}});return NextResponse.json({ok:true,automations:next})}