"use client";

const plans={inicio:{name:"Inicio",price:1.99,checkout:"https://vyralmulticuentas.lemonsqueezy.com/checkout/buy/084513ad-2a9c-453a-ae56-1ee76c73bb40"},pro:{name:"Crecimiento",price:6.99,checkout:"https://vyralmulticuentas.lemonsqueezy.com/checkout/buy/1637355e-15b2-49ca-8bd1-1d5137d8e30b"},escala:{name:"Escala",price:19.99,checkout:"https://vyralmulticuentas.lemonsqueezy.com/checkout/buy/fbf20548-29e5-40af-8627-b52224bb3ed8"},ai:{name:"VYRAL AI",price:49,checkout:""}} as const;
type Id=keyof typeof plans;

export default function UpgradeCalculator({current,periodEnd,pending=false}:{current:Id;periodEnd:string|null;pending?:boolean}){
 const order:Id[]=["inicio","pro","escala","ai"]; const targets=order.slice(order.indexOf(current)+1); if(!targets.length)return null;
 const remainingDays=periodEnd?Math.max(0,Math.ceil((new Date(periodEnd).getTime()-Date.now())/86400000)):30;
 return <section className="upgradeCalc" id="upgrade"><div className="upgradeCalcHead"><div><small>UPGRADE INTELIGENTE</small><h2>Subí de nivel sin perder el valor que ya pagaste.</h2><p>Elegí entre iniciar un mes nuevo o solicitar que el saldo restante de tu plan actual se convierta en días equivalentes del plan superior.</p></div><span>VALOR PROPORCIONAL</span></div>{pending&&<div className="upgradePending">Tu solicitud de conversión está en revisión. Te avisaremos en tu panel apenas sea aprobada o rechazada.</div>}<div className="upgradeOptions">{targets.map(id=>{const target=plans[id];const equivalent=Math.max(1,Math.floor((remainingDays*plans[current].price)/target.price));return <article key={id}><small>CAMBIAR A</small><h3>{target.name}</h3><strong>US$ {target.price.toFixed(2)} <i>/ mes</i></strong><div className="upgradeMath"><span>Saldo actual estimado</span><b>{remainingDays} días en {plans[current].name}</b><span>Equivalencia estimada</span><b>{equivalent} días en {target.name}</b></div>{target.checkout?<a href={target.checkout}>Pagar mes completo →</a>:<a href="/planes">Ver disponibilidad →</a>}<form action="/api/account/request-upgrade" method="post"><input type="hidden" name="target" value={id}/><button type="submit" disabled={pending}>{pending?"Solicitud en revisión":`Solicitar cambio de saldo · ${equivalent} días`}</button></form></article>})}</div><div className="upgradeNote">La equivalencia se calcula según el valor restante del plan actual. Si aprobamos la solicitud, VYRAL cancela la renovación del proveedor cuando la suscripción esté sincronizada y te asigna manualmente los días equivalentes del nuevo plan.</div></section>
}
