"use client";

const plans={inicio:{name:"Inicio",price:1.99,checkout:"https://vyralmulticuentas.lemonsqueezy.com/checkout/buy/084513ad-2a9c-453a-ae56-1ee76c73bb40"},pro:{name:"Crecimiento",price:6.99,checkout:"https://vyralmulticuentas.lemonsqueezy.com/checkout/buy/1637355e-15b2-49ca-8bd1-1d5137d8e30b"},escala:{name:"Escala",price:19.99,checkout:"https://vyralmulticuentas.lemonsqueezy.com/checkout/buy/fbf20548-29e5-40af-8627-b52224bb3ed8"}} as const;
type Id=keyof typeof plans;

export default function UpgradeCalculator({current,periodEnd}:{current:Id;periodEnd:string|null}){
 const order:Id[]=["inicio","pro","escala"]; const targets=order.slice(order.indexOf(current)+1); if(!targets.length)return null;
 const remainingDays=periodEnd?Math.max(0,Math.ceil((new Date(periodEnd).getTime()-Date.now())/86400000)):null;
 return <section className="upgradeCalc" id="upgrade"><div className="upgradeCalcHead"><div><small>UPGRADE INTELIGENTE</small><h2>Subí de nivel sin perder el valor que ya pagaste.</h2><p>Podés empezar un ciclo nuevo completo o convertir el saldo restante de tu plan actual en días equivalentes del plan superior.</p></div><span>VALOR PROPORCIONAL</span></div><div className="upgradeOptions">{targets.map(id=>{const target=plans[id];const equivalent=remainingDays===null?null:Math.max(1,Math.floor((remainingDays*plans[current].price)/target.price));return <article key={id}><small>CAMBIAR A</small><h3>{target.name}</h3><strong>US$ {target.price.toFixed(2)} <i>/ mes</i></strong><div className="upgradeMath"><span>Saldo actual</span><b>{remainingDays===null?"Pendiente de sincronización":`${remainingDays} días en ${plans[current].name}`}</b><span>Equivalencia estimada</span><b>{equivalent===null?"Se calcula al sincronizar tu ciclo":`${equivalent} días en ${target.name}`}</b></div><a href={target.checkout}>Pagar mes completo →</a><button disabled title="Se habilita al sincronizar la suscripción con el proveedor de pagos">Convertir saldo actual {equivalent?`· ${equivalent} días`:""}</button></article>})}</div><div className="upgradeNote">La conversión proporcional queda preparada, pero no se ejecutará hasta sincronizar VYRAL con el proveedor de pagos para evitar cobros o renovaciones inconsistentes.</div></section>
}
