"use client";

import { useEffect, useRef, useState } from "react";
import "./locale-controller.css";

type Lang="es"|"en";
type Country={code:string;flag:string;name:string;lang:Lang;tz:string;zone:string};
const countries:Country[]=[
{code:"AR",flag:"🇦🇷",name:"Argentina",lang:"es",tz:"America/Argentina/Buenos_Aires",zone:"GMT-3"},{code:"BR",flag:"🇧🇷",name:"Brasil",lang:"es",tz:"America/Sao_Paulo",zone:"GMT-3"},{code:"CL",flag:"🇨🇱",name:"Chile",lang:"es",tz:"America/Santiago",zone:"GMT-3"},{code:"UY",flag:"🇺🇾",name:"Uruguay",lang:"es",tz:"America/Montevideo",zone:"GMT-3"},{code:"PY",flag:"🇵🇾",name:"Paraguay",lang:"es",tz:"America/Asuncion",zone:"GMT-3"},{code:"BO",flag:"🇧🇴",name:"Bolivia",lang:"es",tz:"America/La_Paz",zone:"GMT-4"},{code:"PE",flag:"🇵🇪",name:"Perú",lang:"es",tz:"America/Lima",zone:"GMT-5"},{code:"CO",flag:"🇨🇴",name:"Colombia",lang:"es",tz:"America/Bogota",zone:"GMT-5"},{code:"EC",flag:"🇪🇨",name:"Ecuador",lang:"es",tz:"America/Guayaquil",zone:"GMT-5"},{code:"VE",flag:"🇻🇪",name:"Venezuela",lang:"es",tz:"America/Caracas",zone:"GMT-4"},{code:"MX",flag:"🇲🇽",name:"México",lang:"es",tz:"America/Mexico_City",zone:"CST"},{code:"US",flag:"🇺🇸",name:"United States",lang:"en",tz:"America/New_York",zone:"ET"},{code:"CA",flag:"🇨🇦",name:"Canada",lang:"en",tz:"America/Toronto",zone:"ET"},{code:"ES",flag:"🇪🇸",name:"España",lang:"es",tz:"Europe/Madrid",zone:"CET"},{code:"GB",flag:"🇬🇧",name:"United Kingdom",lang:"en",tz:"Europe/London",zone:"GMT"},{code:"FR",flag:"🇫🇷",name:"France",lang:"en",tz:"Europe/Paris",zone:"CET"},{code:"DE",flag:"🇩🇪",name:"Germany",lang:"en",tz:"Europe/Berlin",zone:"CET"},{code:"IT",flag:"🇮🇹",name:"Italy",lang:"en",tz:"Europe/Rome",zone:"CET"},{code:"PT",flag:"🇵🇹",name:"Portugal",lang:"en",tz:"Europe/Lisbon",zone:"WET"},{code:"NL",flag:"🇳🇱",name:"Netherlands",lang:"en",tz:"Europe/Amsterdam",zone:"CET"},{code:"CH",flag:"🇨🇭",name:"Switzerland",lang:"en",tz:"Europe/Zurich",zone:"CET"},{code:"AE",flag:"🇦🇪",name:"United Arab Emirates",lang:"en",tz:"Asia/Dubai",zone:"GMT+4"},{code:"JP",flag:"🇯🇵",name:"Japan",lang:"en",tz:"Asia/Tokyo",zone:"GMT+9"},{code:"AU",flag:"🇦🇺",name:"Australia",lang:"en",tz:"Australia/Sydney",zone:"AET"}
];
const exact:Record<string,string>={"Dashboard":"Dashboard","Publicar":"Publish","Cuentas":"Accounts","Historial":"History","Planes":"Plans","Preguntas frecuentes":"FAQ","Soporte 24/7":"24/7 Support","Cerrar sesión":"Log out","Nueva publicación":"New post","Descripción":"Caption","Privacidad":"Privacy","Seleccioná cuentas":"Select accounts","Centro de operaciones":"Operations center","Tu contenido. Multiplicado.":"Your content. Multiplied.","Últimos 30 días":"Last 30 days","Vistas":"Views","Seguidores":"Followers","Compartidos":"Shares","Distribución multicuentas":"Multi-account distribution","Ahora":"Now","Programar":"Schedule","Elegir fecha y hora":"Choose date and time","PUBLICACIÓN":"PUBLISHING","¿Cuándo querés publicarlo?":"When do you want to publish?","Publicar inmediatamente":"Publish immediately","Fecha y hora":"Date and time","Presioná para elegir el video que vas a distribuir.":"Click to choose the video you want to distribute."};
const originalText=new WeakMap<Text,string>();
function translatedText(v:string){const t=v.trim();return exact[t]?v.replace(t,exact[t]):v}
function walk(root:Node,lang:Lang){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n=w.nextNode() as Text|null;while(n){if(n.parentElement&&!["SCRIPT","STYLE"].includes(n.parentElement.tagName)){if(!originalText.has(n))originalText.set(n,n.nodeValue||"");const s=originalText.get(n)||"";n.nodeValue=lang==="en"?translatedText(s):s}n=w.nextNode() as Text|null}}
export default function LocaleController(){
 const [open,setOpen]=useState(false);const [code,setCode]=useState("AR");const [query,setQuery]=useState("");const observer=useRef<MutationObserver|null>(null);const current=countries.find(c=>c.code===code)||countries[0];
 function apply(next:string){const c=countries.find(x=>x.code===next)||countries[0];setCode(c.code);try{localStorage.setItem("vyral-country",c.code);localStorage.setItem("vyral-lang",c.lang);localStorage.setItem("vyral-timezone",c.tz)}catch{}document.documentElement.lang=c.lang;walk(document,c.lang);window.dispatchEvent(new CustomEvent("vyral:locale",{detail:{country:c.code,lang:c.lang,tz:c.tz,zone:c.zone,flag:c.flag,name:c.name}}))}
 useEffect(()=>{let saved="AR";try{saved=localStorage.getItem("vyral-country")||"AR"}catch{};apply(saved);observer.current=new MutationObserver(rs=>{let l:Lang="es";try{l=(localStorage.getItem("vyral-lang")||"es") as Lang}catch{};rs.forEach(r=>r.addedNodes.forEach(n=>walk(n,l)))});observer.current.observe(document.body,{childList:true,subtree:true});return()=>observer.current?.disconnect()},[]);
 const filtered=countries.filter(c=>(c.name+" "+c.code).toLowerCase().includes(query.toLowerCase()));
 return <div className="vyralLocaleDock"><button type="button" className="vyralLocaleTrigger" onClick={()=>setOpen(!open)}><span className="flag">{current.flag}</span><span>{current.code}</span><b>⌄</b></button>{open&&<div className="vyralLocalePanel"><small>PAÍS · IDIOMA · ZONA HORARIA</small><strong>{current.flag} {current.name}</strong><p>{current.lang==="es"?"VYRAL en español":"VYRAL in English"} · {current.zone}</p><input className="vyralCountrySearch" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar país…"/><div className="vyralCountryGrid">{filtered.map(c=><button key={c.code} className={c.code===code?"active":""} onClick={()=>{apply(c.code);setOpen(false);setQuery("")}}><span className="flag">{c.flag}</span><b>{c.name}</b><small>{c.lang==="es"?"Español":"English"} · {c.zone}</small></button>)}</div></div>}</div>
}
