"use client";

import {useEffect,useRef} from "react";

type Lang="es"|"en"|"pt"|"ar"|"fr"|"de"|"it"|"nl"|"ja";
type Dict=Record<string,string>;

const ES_KEYS=[
"FILTRAR ANALYTICS","Todas las redes","Últimos 7 días","Últimos 90 días","Fecha a fecha","Analytics que te dicen qué hacer después.","Pasá de mirar números a detectar patrones, oportunidades y decisiones accionables.","ESCALA · ACTIVO","EXCLUSIVO PLAN ESCALA","Analizando todas tus redes","todas tus redes","7 días","30 días","90 días","período personalizado","Basado en métricas + Top 5","Vista estratégica","Recomendaciones","Content Intelligence","Predicción","VIRAL MOMENTUM","puntos vs. período anterior","VELOCIDAD DE CRECIMIENTO","Tu contenido acelera por encima de tu media reciente.","MEJOR SEÑAL","Compartidos","Es la interacción que más está empujando alcance adicional.","OPORTUNIDAD","Repetir formato","Hay un patrón ganador listo para convertirse en serie.","Ver análisis","DESCRIPCIÓN GANADORA","Pregunta corta + curiosidad","score relativo","VYRAL compara captions, interacción y alcance para identificar qué estilo conviene repetir.","FORMATO CON MAYOR POTENCIAL","Hook visual + demostración","Detecta qué estructura de tus últimos videos está superando la media.","PROYECCIÓN DE VISTAS · PRÓXIMOS 7 DÍAS","Incremento estimado de vistas si mantenés la frecuencia y el formato actual.","vistas estimadas","ANALYTICS AVANZADAS","Desbloqueá VYRAL Intelligence.","Recomendaciones, patrones de captions, Viral Momentum, predicción, detección de formatos ganadores y próximas acciones están incluidos en Escala.","Cambiar a Escala","POR QUÉ VYRAL LO DETECTÓ","QUÉ HACER AHORA","QUÉ MIRAR DESPUÉS","Basado en rendimiento reciente + Top 5","Recomendaciones sincronizadas con el filtro activo y preparadas para VYRAL AI.","Plan Escala",
"Bienvenido a VYRAL","Te mostramos exactamente dónde está cada función. Podés omitir la guía cuando quieras.","Este es tu centro de operaciones: rendimiento, impacto, cuentas y accesos rápidos.","Acá subís el video, escribís la descripción, elegís privacidad y preparás la distribución.","Esta sección muestra y administra las cuentas que forman tu red de distribución.","Acá revisás envíos, estados, publicaciones completadas y errores.","Acá ves el impacto combinado, comparativas y rendimiento de todas tus cuentas.","Debajo de Analytics aparece la capa inteligente: patrones, recomendaciones y próximas acciones según tu plan.","Dentro de Publicar configurás comentario → respuesta → DM → oportunidad para Instagram y Facebook.","Listo","Ya conocés el recorrido. Podés conectar una cuenta y crear tu primera publicación.","Omitir","Localizando sección…","Atrás","Empezar","Siguiente","Volver a ver guía","Guía de VYRAL",
"Notificaciones","CENTRO VYRAL","TODO EN ORDEN","actualizaciones","Tu plan vence mañana","Tu plan vence pronto","Quedan","de acceso. Administrá tu suscripción para evitar interrupciones.","Administrar plan","Tu espacio VYRAL está listo","Ya podés distribuir tu próximo contenido.","Conectá tu primera cuenta y prepará tu próxima publicación.","Nueva publicación","Conectar cuenta","Créditos mensuales activos","ya tiene disponible su capacidad mensual de publicaciones.","Este mes","Ver mi plan","Analytics preparado","Cuando entren datos reales de tus redes, VYRAL va a concentrar el rendimiento de tus cuentas en una sola visión.","Cerrar",
"SOPORTE 24/7 · ACTUALIZACIÓN AUTOMÁTICA","ASISTENCIA DIRECTA","Estamos para ayudarte.","Sin vueltas.","Dejanos tu consulta. Esta conversación se actualiza sola cada 5 segundos cuando llega una respuesta.","Estado","Respondido","En revisión","Listo para recibir tu consulta","Consulta cerrada correctamente.","Si necesitás algo más, podés abrir una nueva consulta desde acá.","NUEVA CONSULTA","Asunto","Ej: Problema al conectar una cuenta","Mensaje","Contanos qué pasó, qué estabas intentando hacer y qué necesitás resolver.","Enviar consulta","Tu consulta queda registrada en tu cuenta y llega al panel interno de soporte.","CONVERSACIÓN ACTIVA · LIVE","Chat con VYRAL","mensajes","No tenés ninguna consulta abierta. Cuando envíes una nueva, la conversación aparecerá acá.","VYRAL SUPPORT","VOS",
"VYRAL CREATOR PROGRAM","Volver","Tu audiencia.","Tu ingreso recurrente.","Compartí VYRAL con tu comunidad y recibí el 10% de cada suscripción activa atribuida a tu código, mes a mes.","10% recurrente","Código personal","Panel de rendimiento","Convertite en Creator Viral.","Primero necesitás una cuenta VYRAL para solicitar tu código promocional.","Crear cuenta","Ya tengo cuenta","CREATOR VIRAL · APROBADO","Bienvenido al programa.","Tu código ya está activo. Compartilo en tus redes y empezá a construir una comisión recurrente.","TU CÓDIGO","Usuarios con tu código","Facturación atribuida","Comisión acumulada","KIT DE DIFUSIÓN","Beneficio para tu comunidad","Tu audiencia podrá acceder a promociones especiales usando","El descuento vigente se mostrará y validará en el checkout.","Usá el código","Publicá una vez. Multiplicá tu alcance.","Solicitud en revisión.","Recibimos tu solicitud. Cuando sea aprobada o rechazada vas a verlo automáticamente en tu panel.","Solicitud no aprobada.","Por el momento no pudimos activar tu código. Podés volver a solicitarlo más adelante cuando tu perfil tenga más actividad.","Solicitar nuevamente","SOLICITUD","Solicitá tu código promocional.","Contanos dónde creás contenido. Revisaremos tu perfil y, si es aprobado, VYRAL te asignará un código corto basado en tu nombre.","Solicitud enviada correctamente.","Usuario / nombre público","Red principal","Otra","Contanos brevemente sobre tu audiencia","Temática, comunidad, alcance aproximado...","Enviar solicitud",
"De comentario a oportunidad.","Configurá qué detecta VYRAL, qué responde y qué pasa después.","CONTENIDO VINCULADO","Esta publicación","Se asociará a la publicación que estás preparando.","Preparada","Disparador inteligente","Definí qué comentario activa el flujo.","Nombre interno","Coincidencia exacta","Contiene palabra","Intención con IA","Palabras clave","Escribí una palabra y Enter","No depende de una palabra exacta: interpreta si la persona está pidiendo el recurso, precio, información o acceso.","Excluir si el comentario contiene","Acciones","Qué hace VYRAL cuando detecta la intención.","Respuesta pública","Confirma que el mensaje fue enviado.","Mensaje privado automático","Texto + enlace asociado a esta publicación.","El plus: intención, contexto y control humano.","Respuesta con IA","Personaliza sin perder el objetivo del flujo.","Evita loops, duplicados y respuestas agresivas.","Escala conversaciones sensibles a una persona.","Marca quién mostró intención real.","Tono","Confianza mínima","Instrucciones para la IA","Ocultar controles avanzados","Abrir controles avanzados","Cooldown por usuario","Máximo de respuestas","Objetivo de conversión","Etiqueta del lead","DM iniciado","Click en enlace","Lead identificado","Sin objetivo","Simulador","Probá el flujo antes de publicarlo.","Comentario de prueba","Activaría la automatización","No activaría el flujo","Coincide con una exclusión.","La IA evaluará intención y contexto.","Modo:","exacto","contiene","Comentario","Respuesta pública","Mensaje privado","No solo responde.","Entiende qué oportunidad hay detrás.","Cada interacción puede quedar clasificada por intención, objetivo y etapa para medir qué contenido genera conversaciones reales.","INTERÉS","ALTO","Conexiones","Automatizaciones guardadas","IA por intención","Nueva","Guardando…","Guardar automatización","No se pudo guardar","Error al guardar","Automatización guardada.","guardada","guardadas"
];

function make(values:string[]):Dict{const d:Dict={};ES_KEYS.forEach((k,i)=>{if(values[i])d[k]=values[i]});return d}

const EN=make([
"FILTER ANALYTICS","All networks","Last 7 days","Last 90 days","Custom dates","Analytics that tell you what to do next.","Move from looking at numbers to detecting patterns, opportunities and actionable decisions.","SCALE · ACTIVE","SCALE PLAN EXCLUSIVE","Analyzing all your networks","all your networks","7 days","30 days","90 days","custom period","Based on metrics + Top 5","Strategic view","Recommendations","Content Intelligence","Forecast","VIRAL MOMENTUM","points vs. previous period","GROWTH VELOCITY","Your content is accelerating above your recent average.","STRONGEST SIGNAL","Shares","This interaction is driving the most additional reach.","OPPORTUNITY","Repeat format","A winning pattern is ready to become a series.","View analysis","WINNING CAPTION","Short question + curiosity","relative score","VYRAL compares captions, engagement and reach to identify which style is worth repeating.","HIGHEST-POTENTIAL FORMAT","Visual hook + demonstration","Detects which structure from your latest videos is outperforming your average.","VIEW FORECAST · NEXT 7 DAYS","Estimated view increase if you maintain your current frequency and format.","estimated views","ADVANCED ANALYTICS","Unlock VYRAL Intelligence.","Recommendations, caption patterns, Viral Momentum, forecasting, winning-format detection and next actions are included in Scale.","Switch to Scale","WHY VYRAL DETECTED IT","WHAT TO DO NOW","WHAT TO WATCH NEXT","Based on recent performance + Top 5","Recommendations synced with the active filter and ready for VYRAL AI.","Scale plan",
"Welcome to VYRAL","We'll show you exactly where every feature is. You can skip the guide anytime.","This is your operations center: performance, impact, accounts and shortcuts.","Upload the video, write the caption, choose privacy and prepare distribution here.","This section shows and manages the accounts in your distribution network.","Review deliveries, statuses, completed posts and errors here.","See combined impact, comparisons and performance across all your accounts here.","Below Analytics is the intelligence layer: patterns, recommendations and next actions based on your plan.","Inside Publish, configure comment → reply → DM → opportunity for Instagram and Facebook.","Ready","You know the flow. Connect an account and create your first post.","Skip","Locating section…","Back","Start","Next","Replay guide","VYRAL guide",
"Notifications","VYRAL CENTER","ALL SYSTEMS OK","updates","Your plan expires tomorrow","Your plan expires soon","There are","of access left. Manage your subscription to avoid interruptions.","Manage plan","Your VYRAL workspace is ready","You can now distribute your next content.","Connect your first account and prepare your next post.","New post","Connect account","Monthly credits active","now has its monthly publishing capacity available.","This month","View my plan","Analytics ready","When real network data arrives, VYRAL will consolidate account performance in one view.","Close",
"24/7 SUPPORT · AUTO REFRESH","DIRECT ASSISTANCE","We're here to help.","No runaround.","Send us your question. This conversation refreshes automatically every 5 seconds when a reply arrives.","Status","Answered","Under review","Ready for your request","Request closed successfully.","If you need anything else, you can open a new request here.","NEW REQUEST","Subject","Example: Problem connecting an account","Message","Tell us what happened, what you were trying to do and what you need resolved.","Send request","Your request is saved to your account and sent to the internal support panel.","ACTIVE CONVERSATION · LIVE","Chat with VYRAL","messages","You don't have an open request. When you send one, the conversation will appear here.","VYRAL SUPPORT","YOU",
"VYRAL CREATOR PROGRAM","Back","Your audience.","Your recurring income.","Share VYRAL with your community and receive 10% of every active subscription attributed to your code, month after month.","10% recurring","Personal code","Performance dashboard","Become a Viral Creator.","You need a VYRAL account first to request your promo code.","Create account","I already have an account","VIRAL CREATOR · APPROVED","Welcome to the program.","Your code is active. Share it on your networks and start building recurring commission.","YOUR CODE","Users with your code","Attributed revenue","Accumulated commission","SHARING KIT","Benefit for your community","Your audience can access special promotions using","The active discount will be shown and validated at checkout.","Use code","Publish once. Multiply your reach.","Application under review.","We received your application. Once approved or rejected, you'll see it automatically in your dashboard.","Application not approved.","We couldn't activate your code right now. You can apply again later when your profile has more activity.","Apply again","APPLICATION","Request your promo code.","Tell us where you create content. We'll review your profile and, if approved, VYRAL will assign a short code based on your name.","Application sent successfully.","Username / public name","Main network","Other","Tell us briefly about your audience","Topic, community, approximate reach...","Send application",
"From comment to opportunity.","Configure what VYRAL detects, what it replies and what happens next.","LINKED CONTENT","This post","It will be linked to the post you're preparing.","Ready","Smart trigger","Define which comment activates the flow.","Internal name","Exact match","Contains word","AI intent","Keywords","Type a word and press Enter","It doesn't depend on an exact word: it interprets whether the person is requesting a resource, price, information or access.","Exclude if comment contains","Actions","What VYRAL does when it detects intent.","Public reply","Confirms the message was sent.","Automatic private message","Text + link associated with this post.","The extra layer: intent, context and human control.","AI reply","Personalizes without losing the flow's objective.","Prevents loops, duplicates and aggressive replies.","Escalates sensitive conversations to a person.","Marks who showed real intent.","Tone","Minimum confidence","AI instructions","Hide advanced controls","Open advanced controls","Cooldown per user","Maximum replies","Conversion goal","Lead tag","DM started","Link click","Lead identified","No goal","Simulator","Test the flow before publishing.","Test comment","Would activate the automation","Would not activate the flow","Matches an exclusion.","AI will evaluate intent and context.","Mode:","exact","contains","Comment","Public reply","Private message","It doesn't just reply.","It understands the opportunity behind it.","Each interaction can be classified by intent, objective and stage to measure which content creates real conversations.","INTEREST","HIGH","Connections","Saved automations","AI by intent","New","Saving…","Save automation","Could not save","Save error","Automation saved.","saved","saved"
]);

const PT=make([
"FILTRAR ANÁLISES","Todas as redes","Últimos 7 dias","Últimos 90 dias","Data a data","Análises que dizem o que fazer depois.","Pare de apenas olhar números e detecte padrões, oportunidades e decisões acionáveis.","ESCALA · ATIVO","EXCLUSIVO DO PLANO ESCALA","Analisando todas as suas redes","todas as suas redes","7 dias","30 dias","90 dias","período personalizado","Baseado em métricas + Top 5","Visão estratégica","Recomendações","Content Intelligence","Previsão","VIRAL MOMENTUM","pontos vs. período anterior","VELOCIDADE DE CRESCIMENTO","Seu conteúdo está acelerando acima da média recente.","MELHOR SINAL","Compartilhamentos","É a interação que mais está impulsionando alcance adicional.","OPORTUNIDADE","Repetir formato","Há um padrão vencedor pronto para virar série.","Ver análise","LEGENDA VENCEDORA","Pergunta curta + curiosidade","score relativo","O VYRAL compara legendas, interação e alcance para identificar qual estilo vale repetir.","FORMATO COM MAIOR POTENCIAL","Hook visual + demonstração","Detecta qual estrutura dos seus últimos vídeos supera sua média.","PROJEÇÃO DE VISUALIZAÇÕES · PRÓXIMOS 7 DIAS","Aumento estimado de visualizações se você mantiver frequência e formato atuais.","visualizações estimadas","ANÁLISES AVANÇADAS","Desbloqueie o VYRAL Intelligence.","Recomendações, padrões de legendas, Viral Momentum, previsão, detecção de formatos vencedores e próximas ações estão incluídos no Escala.","Mudar para Escala","POR QUE O VYRAL DETECTOU","O QUE FAZER AGORA","O QUE OBSERVAR DEPOIS","Baseado em desempenho recente + Top 5","Recomendações sincronizadas com o filtro ativo e prontas para VYRAL AI.","Plano Escala",
"Bem-vindo ao VYRAL","Mostramos exatamente onde fica cada função. Você pode pular o guia quando quiser.","Este é o seu centro de operações: desempenho, impacto, contas e atalhos.","Aqui você envia o vídeo, escreve a descrição, escolhe a privacidade e prepara a distribuição.","Esta seção mostra e gerencia as contas da sua rede de distribuição.","Aqui você revisa envios, status, publicações concluídas e erros.","Aqui você vê impacto combinado, comparações e desempenho de todas as contas.","Abaixo de Analytics fica a camada inteligente: padrões, recomendações e próximas ações conforme seu plano.","Dentro de Publicar, configure comentário → resposta → DM → oportunidade para Instagram e Facebook.","Pronto","Você já conhece o fluxo. Conecte uma conta e crie sua primeira publicação.","Pular","Localizando seção…","Voltar","Começar","Próximo","Ver guia novamente","Guia do VYRAL",
"Notificações","CENTRAL VYRAL","TUDO EM ORDEM","atualizações","Seu plano vence amanhã","Seu plano vence em breve","Restam","de acesso. Gerencie sua assinatura para evitar interrupções.","Gerenciar plano","Seu espaço VYRAL está pronto","Você já pode distribuir seu próximo conteúdo.","Conecte sua primeira conta e prepare sua próxima publicação.","Nova publicação","Conectar conta","Créditos mensais ativos","já tem sua capacidade mensal de publicações disponível.","Este mês","Ver meu plano","Analytics pronto","Quando entrarem dados reais das suas redes, o VYRAL concentrará o desempenho das contas em uma única visão.","Fechar",
"SUPORTE 24/7 · ATUALIZAÇÃO AUTOMÁTICA","ATENDIMENTO DIRETO","Estamos aqui para ajudar.","Sem enrolação.","Envie sua dúvida. A conversa atualiza automaticamente a cada 5 segundos quando chega uma resposta.","Status","Respondido","Em análise","Pronto para receber sua solicitação","Solicitação encerrada com sucesso.","Se precisar de algo mais, você pode abrir uma nova solicitação aqui.","NOVA SOLICITAÇÃO","Assunto","Ex: Problema ao conectar uma conta","Mensagem","Conte o que aconteceu, o que você estava tentando fazer e o que precisa resolver.","Enviar solicitação","Sua solicitação fica registrada na sua conta e chega ao painel interno de suporte.","CONVERSA ATIVA · LIVE","Chat com VYRAL","mensagens","Você não tem nenhuma solicitação aberta. Quando enviar uma nova, a conversa aparecerá aqui.","VYRAL SUPPORT","VOCÊ",
"VYRAL CREATOR PROGRAM","Voltar","Sua audiência.","Sua renda recorrente.","Compartilhe o VYRAL com sua comunidade e receba 10% de cada assinatura ativa atribuída ao seu código, mês a mês.","10% recorrente","Código pessoal","Painel de desempenho","Torne-se um Creator Viral.","Primeiro você precisa de uma conta VYRAL para solicitar seu código promocional.","Criar conta","Já tenho conta","CREATOR VIRAL · APROVADO","Bem-vindo ao programa.","Seu código já está ativo. Compartilhe nas redes e comece a construir comissão recorrente.","SEU CÓDIGO","Usuários com seu código","Faturamento atribuído","Comissão acumulada","KIT DE DIVULGAÇÃO","Benefício para sua comunidade","Sua audiência poderá acessar promoções especiais usando","O desconto vigente será mostrado e validado no checkout.","Use o código","Publique uma vez. Multiplique seu alcance.","Solicitação em análise.","Recebemos sua solicitação. Quando for aprovada ou rejeitada, você verá automaticamente no painel.","Solicitação não aprovada.","Por enquanto não foi possível ativar seu código. Você poderá solicitar novamente quando seu perfil tiver mais atividade.","Solicitar novamente","SOLICITAÇÃO","Solicite seu código promocional.","Conte onde você cria conteúdo. Revisaremos seu perfil e, se aprovado, o VYRAL atribuirá um código curto baseado no seu nome.","Solicitação enviada com sucesso.","Usuário / nome público","Rede principal","Outra","Conte brevemente sobre sua audiência","Tema, comunidade, alcance aproximado...","Enviar solicitação",
"De comentário a oportunidade.","Configure o que o VYRAL detecta, o que responde e o que acontece depois.","CONTEÚDO VINCULADO","Esta publicação","Será associado à publicação que você está preparando.","Pronto","Gatilho inteligente","Defina qual comentário ativa o fluxo.","Nome interno","Correspondência exata","Contém palavra","Intenção com IA","Palavras-chave","Digite uma palavra e Enter","Não depende de uma palavra exata: interpreta se a pessoa está pedindo recurso, preço, informação ou acesso.","Excluir se o comentário contiver","Ações","O que o VYRAL faz quando detecta intenção.","Resposta pública","Confirma que a mensagem foi enviada.","Mensagem privada automática","Texto + link associado a esta publicação.","O diferencial: intenção, contexto e controle humano.","Resposta com IA","Personaliza sem perder o objetivo do fluxo.","Evita loops, duplicados e respostas agressivas.","Encaminha conversas sensíveis para uma pessoa.","Marca quem demonstrou intenção real.","Tom","Confiança mínima","Instruções para a IA","Ocultar controles avançados","Abrir controles avançados","Cooldown por usuário","Máximo de respostas","Objetivo de conversão","Etiqueta do lead","DM iniciado","Clique no link","Lead identificado","Sem objetivo","Simulador","Teste o fluxo antes de publicar.","Comentário de teste","Ativaria a automação","Não ativaria o fluxo","Coincide com uma exclusão.","A IA avaliará intenção e contexto.","Modo:","exato","contém","Comentário","Resposta pública","Mensagem privada","Não apenas responde.","Entende a oportunidade por trás.","Cada interação pode ser classificada por intenção, objetivo e etapa para medir qual conteúdo gera conversas reais.","INTERESSE","ALTO","Conexões","Automações salvas","IA por intenção","Nova","Salvando…","Salvar automação","Não foi possível salvar","Erro ao salvar","Automação salva.","salva","salvas"
]);

const AR=make([
"تصفية التحليلات","كل الشبكات","آخر 7 أيام","آخر 90 يوماً","من تاريخ إلى تاريخ","تحليلات تخبرك بما يجب فعله بعد ذلك.","انتقل من مجرد قراءة الأرقام إلى اكتشاف الأنماط والفرص والقرارات القابلة للتنفيذ.","التوسع · نشط","حصري لخطة التوسع","تحليل كل شبكاتك","كل شبكاتك","7 أيام","30 يوماً","90 يوماً","فترة مخصصة","استناداً إلى المقاييس + أفضل 5","عرض استراتيجي","التوصيات","Content Intelligence","التوقع","VIRAL MOMENTUM","نقطة مقارنة بالفترة السابقة","سرعة النمو","محتواك يتسارع فوق متوسطك الأخير.","أقوى إشارة","المشاركات","هذا التفاعل هو الأكثر دفعاً للوصول الإضافي.","فرصة","تكرار التنسيق","هناك نمط ناجح جاهز للتحول إلى سلسلة.","عرض التحليل","الوصف الأفضل","سؤال قصير + فضول","درجة نسبية","يقارن VYRAL بين الأوصاف والتفاعل والوصول لتحديد الأسلوب الذي يستحق التكرار.","التنسيق الأعلى إمكاناً","Hook بصري + عرض","يكتشف أي بنية من فيديوهاتك الأخيرة تتجاوز متوسطك.","توقع المشاهدات · الأيام السبعة القادمة","زيادة تقديرية في المشاهدات إذا حافظت على التكرار والتنسيق الحاليين.","مشاهدات تقديرية","تحليلات متقدمة","افتح VYRAL Intelligence.","التوصيات وأنماط الأوصاف وViral Momentum والتوقع واكتشاف التنسيقات الناجحة والخطوات التالية مشمولة في خطة التوسع.","التغيير إلى التوسع","لماذا اكتشف VYRAL ذلك","ماذا تفعل الآن","ما الذي تراقبه لاحقاً","استناداً إلى الأداء الأخير + أفضل 5","توصيات متزامنة مع الفلتر النشط وجاهزة لـ VYRAL AI.","خطة التوسع",
"مرحباً بك في VYRAL","سنريك مكان كل وظيفة بدقة. يمكنك تخطي الدليل في أي وقت.","هذا هو مركز عملياتك: الأداء والتأثير والحسابات والاختصارات.","هنا ترفع الفيديو وتكتب الوصف وتختار الخصوصية وتجهز التوزيع.","يعرض هذا القسم الحسابات التي تشكل شبكة التوزيع ويديرها.","هنا تراجع الإرسالات والحالات والمنشورات المكتملة والأخطاء.","هنا ترى التأثير المجمّع والمقارنات وأداء جميع حساباتك.","تحت Analytics تظهر طبقة الذكاء: الأنماط والتوصيات والخطوات التالية حسب خطتك.","داخل النشر يمكنك إعداد تعليق ← رد ← رسالة خاصة ← فرصة لـ Instagram وFacebook.","جاهز","أصبحت تعرف المسار. اربط حساباً وأنشئ أول منشور.","تخطي","جارٍ تحديد القسم…","السابق","ابدأ","التالي","عرض الدليل مجدداً","دليل VYRAL",
"الإشعارات","مركز VYRAL","كل شيء يعمل بشكل طبيعي","تحديثات","تنتهي خطتك غداً","تنتهي خطتك قريباً","متبقي","من الوصول. أدر اشتراكك لتجنب الانقطاع.","إدارة الخطة","مساحة VYRAL الخاصة بك جاهزة","يمكنك الآن توزيع محتواك التالي.","اربط حسابك الأول وجهّز منشورك التالي.","منشور جديد","ربط حساب","الأرصدة الشهرية نشطة","أصبحت سعة النشر الشهرية متاحة الآن.","هذا الشهر","عرض خطتي","Analytics جاهز","عند وصول بيانات حقيقية من شبكاتك سيجمع VYRAL أداء حساباتك في رؤية واحدة.","إغلاق",
"دعم 24/7 · تحديث تلقائي","مساعدة مباشرة","نحن هنا لمساعدتك.","بلا تعقيد.","أرسل استفسارك. تتحدث المحادثة تلقائياً كل 5 ثوانٍ عند وصول رد.","الحالة","تم الرد","قيد المراجعة","جاهز لاستقبال استفسارك","تم إغلاق الاستفسار بنجاح.","إذا احتجت إلى شيء آخر يمكنك فتح استفسار جديد من هنا.","استفسار جديد","الموضوع","مثال: مشكلة في ربط حساب","الرسالة","أخبرنا بما حدث وما الذي كنت تحاول فعله وما الذي تحتاج إلى حله.","إرسال الاستفسار","يتم تسجيل استفسارك في حسابك ويصل إلى لوحة الدعم الداخلية.","محادثة نشطة · LIVE","محادثة مع VYRAL","رسائل","ليس لديك أي استفسار مفتوح. عند إرسال استفسار جديد ستظهر المحادثة هنا.","VYRAL SUPPORT","أنت",
"برنامج منشئي VYRAL","رجوع","جمهورك.","دخلك المتكرر.","شارك VYRAL مع مجتمعك واحصل على 10% من كل اشتراك نشط منسوب إلى رمزك شهراً بعد شهر.","10% متكرر","رمز شخصي","لوحة الأداء","كن منشئ VYRAL.","تحتاج أولاً إلى حساب VYRAL لطلب رمزك الترويجي.","إنشاء حساب","لدي حساب بالفعل","منشئ VYRAL · تمت الموافقة","مرحباً بك في البرنامج.","رمزك نشط الآن. شاركه على شبكاتك وابدأ ببناء عمولة متكررة.","رمزك","مستخدمون برمزك","إيرادات منسوبة","عمولة متراكمة","حزمة المشاركة","ميزة لمجتمعك","يمكن لجمهورك الوصول إلى عروض خاصة باستخدام","سيظهر الخصم الحالي ويتم التحقق منه عند الدفع.","استخدم الرمز","انشر مرة واحدة. ضاعف وصولك.","الطلب قيد المراجعة.","استلمنا طلبك. عند الموافقة أو الرفض سيظهر ذلك تلقائياً في لوحتك.","لم تتم الموافقة على الطلب.","تعذر تفعيل رمزك حالياً. يمكنك التقديم مجدداً لاحقاً عندما يصبح ملفك أكثر نشاطاً.","التقديم مجدداً","الطلب","اطلب رمزك الترويجي.","أخبرنا أين تنشئ المحتوى. سنراجع ملفك وإذا تمت الموافقة سيمنحك VYRAL رمزاً قصيراً مبنياً على اسمك.","تم إرسال الطلب بنجاح.","اسم المستخدم / الاسم العام","الشبكة الرئيسية","أخرى","أخبرنا باختصار عن جمهورك","الموضوع والمجتمع والوصول التقريبي...","إرسال الطلب",
"من تعليق إلى فرصة.","اضبط ما يكتشفه VYRAL وما يرد به وما يحدث بعد ذلك.","المحتوى المرتبط","هذا المنشور","سيتم ربطه بالمنشور الذي تجهزه.","جاهز","مشغل ذكي","حدد التعليق الذي يفعّل المسار.","اسم داخلي","تطابق تام","يحتوي كلمة","نية بالذكاء الاصطناعي","كلمات مفتاحية","اكتب كلمة واضغط Enter","لا يعتمد على كلمة محددة: يفسر ما إذا كان الشخص يطلب مورداً أو سعراً أو معلومات أو وصولاً.","استبعاد إذا احتوى التعليق","الإجراءات","ما يفعله VYRAL عندما يكتشف النية.","رد عام","يؤكد إرسال الرسالة.","رسالة خاصة تلقائية","نص + رابط مرتبط بهذا المنشور.","الطبقة الإضافية: النية والسياق والتحكم البشري.","رد بالذكاء الاصطناعي","يخصص الرد دون فقدان هدف المسار.","يمنع التكرار والحلقات والردود العدوانية.","يصعّد المحادثات الحساسة إلى شخص.","يحدد من أظهر نية حقيقية.","النبرة","الحد الأدنى للثقة","تعليمات الذكاء الاصطناعي","إخفاء الإعدادات المتقدمة","فتح الإعدادات المتقدمة","فترة انتظار لكل مستخدم","الحد الأقصى للردود","هدف التحويل","وسم العميل المحتمل","بدأت رسالة خاصة","نقرة على الرابط","تم تحديد العميل المحتمل","بدون هدف","المحاكي","اختبر المسار قبل النشر.","تعليق تجريبي","سيتم تفعيل الأتمتة","لن يتم تفعيل المسار","يطابق استبعاداً.","سيقيّم الذكاء الاصطناعي النية والسياق.","الوضع:","تطابق تام","يحتوي","تعليق","رد عام","رسالة خاصة","لا يكتفي بالرد.","يفهم الفرصة خلف التفاعل.","يمكن تصنيف كل تفاعل حسب النية والهدف والمرحلة لقياس المحتوى الذي يولد محادثات حقيقية.","اهتمام","مرتفع","الاتصالات","الأتمتات المحفوظة","ذكاء اصطناعي حسب النية","جديد","جارٍ الحفظ…","حفظ الأتمتة","تعذر الحفظ","خطأ في الحفظ","تم حفظ الأتمتة.","محفوظة","محفوظة"
]);

const DICTS:Record<string,Dict>={en:EN,pt:PT,ar:AR};
const reverse=Object.values(DICTS).flatMap(d=>Object.entries(d).map(([es,to])=>[to,es] as [string,string])).filter(([a,b])=>a!==b).sort((a,b)=>b[0].length-a[0].length);
const forwardCache=new Map<string,[string,string][]>();
function currentLang():Lang{try{return(localStorage.getItem("vyral-lang")||"es") as Lang}catch{return"es"}}
function canonical(s:string){let out=s;for(const[to,es]of reverse)if(out.includes(to))out=out.split(to).join(es);return out}
function translate(s:string,l:Lang){let out=canonical(s);if(l==="es")return out;const dict=DICTS[l]||EN;let list=forwardCache.get(l);if(!list){list=Object.entries(dict).sort((a,b)=>b[0].length-a[0].length) as [string,string][];forwardCache.set(l,list)}for(const[es,to]of list)if(out.includes(es))out=out.split(es).join(to);return out}

export default function LocaleFeatureCoverage(){
 const timer=useRef<number|null>(null);
 useEffect(()=>{
  const run=()=>{const l=currentLang();const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n=walker.nextNode() as Text|null;while(n){const el=n.parentElement;if(el&&!el.closest(".vyralLocaleDock")&&!["SCRIPT","STYLE"].includes(el.tagName)){const next=translate(n.nodeValue||"",l);if(next!==n.nodeValue)n.nodeValue=next}n=walker.nextNode() as Text|null}document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>("input,textarea").forEach(el=>{if(el.closest(".vyralLocaleDock"))return;const next=translate(el.placeholder||"",l);if(next!==el.placeholder)el.placeholder=next})};
  const schedule=()=>{if(timer.current!==null)clearTimeout(timer.current);timer.current=window.setTimeout(()=>{run();requestAnimationFrame(run)},70)};
  const onLocale=()=>schedule();window.addEventListener("vyral:locale",onLocale);const obs=new MutationObserver(schedule);obs.observe(document.body,{childList:true,subtree:true,characterData:true});schedule();
  return()=>{window.removeEventListener("vyral:locale",onLocale);obs.disconnect();if(timer.current!==null)clearTimeout(timer.current)};
 },[]);
 return null;
}
