"use client";

import {useEffect,useMemo,useState} from "react";
import "./locale-controller.css";

type Lang="es"|"en"|"ar"|"pt"|"fr"|"de"|"it"|"nl"|"ja";
type Country={code:string;flag:string;name:string;lang:Lang;tz:string;zone:string};
const countries:Country[]=[
{code:"AR",flag:"🇦🇷",name:"Argentina",lang:"es",tz:"America/Argentina/Buenos_Aires",zone:"GMT-3"},{code:"BR",flag:"🇧🇷",name:"Brasil",lang:"pt",tz:"America/Sao_Paulo",zone:"GMT-3"},{code:"CL",flag:"🇨🇱",name:"Chile",lang:"es",tz:"America/Santiago",zone:"GMT-3"},{code:"UY",flag:"🇺🇾",name:"Uruguay",lang:"es",tz:"America/Montevideo",zone:"GMT-3"},{code:"PY",flag:"🇵🇾",name:"Paraguay",lang:"es",tz:"America/Asuncion",zone:"GMT-3"},{code:"BO",flag:"🇧🇴",name:"Bolivia",lang:"es",tz:"America/La_Paz",zone:"GMT-4"},{code:"PE",flag:"🇵🇪",name:"Perú",lang:"es",tz:"America/Lima",zone:"GMT-5"},{code:"CO",flag:"🇨🇴",name:"Colombia",lang:"es",tz:"America/Bogota",zone:"GMT-5"},{code:"EC",flag:"🇪🇨",name:"Ecuador",lang:"es",tz:"America/Guayaquil",zone:"GMT-5"},{code:"VE",flag:"🇻🇪",name:"Venezuela",lang:"es",tz:"America/Caracas",zone:"GMT-4"},{code:"MX",flag:"🇲🇽",name:"México",lang:"es",tz:"America/Mexico_City",zone:"CST"},{code:"US",flag:"🇺🇸",name:"United States",lang:"en",tz:"America/New_York",zone:"ET"},{code:"CA",flag:"🇨🇦",name:"Canada",lang:"en",tz:"America/Toronto",zone:"ET"},{code:"ES",flag:"🇪🇸",name:"España",lang:"es",tz:"Europe/Madrid",zone:"CET"},{code:"GB",flag:"🇬🇧",name:"United Kingdom",lang:"en",tz:"Europe/London",zone:"GMT"},{code:"FR",flag:"🇫🇷",name:"France",lang:"fr",tz:"Europe/Paris",zone:"CET"},{code:"DE",flag:"🇩🇪",name:"Deutschland",lang:"de",tz:"Europe/Berlin",zone:"CET"},{code:"IT",flag:"🇮🇹",name:"Italia",lang:"it",tz:"Europe/Rome",zone:"CET"},{code:"PT",flag:"🇵🇹",name:"Portugal",lang:"pt",tz:"Europe/Lisbon",zone:"WET"},{code:"NL",flag:"🇳🇱",name:"Nederland",lang:"nl",tz:"Europe/Amsterdam",zone:"CET"},{code:"CH",flag:"🇨🇭",name:"Schweiz",lang:"de",tz:"Europe/Zurich",zone:"CET"},{code:"AE",flag:"🇦🇪",name:"الإمارات العربية المتحدة",lang:"ar",tz:"Asia/Dubai",zone:"GMT+4"},{code:"SA",flag:"🇸🇦",name:"المملكة العربية السعودية",lang:"ar",tz:"Asia/Riyadh",zone:"GMT+3"},{code:"QA",flag:"🇶🇦",name:"قطر",lang:"ar",tz:"Asia/Qatar",zone:"GMT+3"},{code:"KW",flag:"🇰🇼",name:"الكويت",lang:"ar",tz:"Asia/Kuwait",zone:"GMT+3"},{code:"BH",flag:"🇧🇭",name:"البحرين",lang:"ar",tz:"Asia/Bahrain",zone:"GMT+3"},{code:"OM",flag:"🇴🇲",name:"عُمان",lang:"ar",tz:"Asia/Muscat",zone:"GMT+4"},{code:"JO",flag:"🇯🇴",name:"الأردن",lang:"ar",tz:"Asia/Amman",zone:"GMT+3"},{code:"EG",flag:"🇪🇬",name:"مصر",lang:"ar",tz:"Africa/Cairo",zone:"GMT+3"},{code:"MA",flag:"🇲🇦",name:"المغرب",lang:"ar",tz:"Africa/Casablanca",zone:"GMT+1"},{code:"DZ",flag:"🇩🇿",name:"الجزائر",lang:"ar",tz:"Africa/Algiers",zone:"GMT+1"},{code:"TN",flag:"🇹🇳",name:"تونس",lang:"ar",tz:"Africa/Tunis",zone:"GMT+1"},{code:"LB",flag:"🇱🇧",name:"لبنان",lang:"ar",tz:"Asia/Beirut",zone:"GMT+3"},{code:"IQ",flag:"🇮🇶",name:"العراق",lang:"ar",tz:"Asia/Baghdad",zone:"GMT+3"},{code:"JP",flag:"🇯🇵",name:"日本",lang:"ja",tz:"Asia/Tokyo",zone:"GMT+9"},{code:"AU",flag:"🇦🇺",name:"Australia",lang:"en",tz:"Australia/Sydney",zone:"AET"}
];
const names:Record<Lang,string>={es:"Español",en:"English",ar:"العربية",pt:"Português",fr:"Français",de:"Deutsch",it:"Italiano",nl:"Nederlands",ja:"日本語"};

export default function LocaleSelector(){
 const[open,setOpen]=useState(false);const[code,setCode]=useState("AR");const[query,setQuery]=useState("");
 const current=countries.find(c=>c.code===code)||countries[0];
 const emit=(c:Country)=>{
  setCode(c.code);
  try{localStorage.setItem("vyral-country",c.code);localStorage.setItem("vyral-lang",c.lang);localStorage.setItem("vyral-timezone",c.tz);document.cookie=`vyral-country=${c.code}; path=/; max-age=31536000; samesite=lax`}catch{}
  document.documentElement.lang=c.lang;document.documentElement.dir="ltr";document.body.dataset.vyralLang=c.lang;
  window.dispatchEvent(new CustomEvent("vyral:locale",{detail:{country:c.code,lang:c.lang,tz:c.tz,zone:c.zone,flag:c.flag,name:c.name}}));
 };
 useEffect(()=>{let saved="AR";try{saved=localStorage.getItem("vyral-country")||"AR"}catch{}const c=countries.find(x=>x.code===saved)||countries[0];emit(c)},[]);
 const filtered=useMemo(()=>countries.filter(c=>(`${c.name} ${c.code} ${names[c.lang]}`).toLowerCase().includes(query.toLowerCase())),[query]);
 const labels=current.lang==="ar"?{title:"الدولة · اللغة · المنطقة الزمنية",search:"ابحث عن دولة…"}:current.lang==="pt"?{title:"PAÍS · IDIOMA · FUSO HORÁRIO",search:"Buscar país…"}:current.lang==="en"?{title:"COUNTRY · LANGUAGE · TIME ZONE",search:"Search country…"}:{title:"PAÍS · IDIOMA · ZONA HORARIA",search:"Buscar país…"};
 return <div className="vyralLocaleDock"><button type="button" className="vyralLocaleTrigger" onClick={()=>setOpen(v=>!v)} aria-label="Country and language"><span className="flag">{current.flag}</span><span>{current.code}</span><b>⌄</b></button>{open&&<div className="vyralLocalePanel"><small>{labels.title}</small><strong>{current.flag} {current.name}</strong><p>{names[current.lang]} · {current.zone}</p><input className="vyralCountrySearch" value={query} onChange={e=>setQuery(e.target.value)} placeholder={labels.search}/><div className="vyralCountryGrid">{filtered.map(c=><button type="button" key={c.code} className={c.code===code?"active":""} onClick={()=>{emit(c);setOpen(false);setQuery("")}}><span className="flag">{c.flag}</span><b>{c.name}</b><small>{names[c.lang]} · {c.zone}</small></button>)}</div></div>}</div>
}
